### ISSUE TITLE
Is there any constraint on the usage of Q-transform of Gwpy?

### ISSUE THREAD

**Issue by lupin0lin** [gwpy/gwpy#1002]
To whom will concern it,

I would like to ask that whether there is any constraint on the usage of the Q-transform from gwpy or pycbc?
In the attached docx file, I present my code and the related output.
I load the data in the 2nd pool and convert it into pycbc time series in the 3rd pool.
However, it seems that the sampling rate of the pycbc time series cannot be smaller than 1, and I do not ensure whether it caused the problem to gain the power spectral density (psd).
In the 4th pool, I convert the data into gwpy time series, and then I can successfully gain the psd in the 5th pool.
The dynamical power spectrum can also be obtained in the 6th pool.
But when I considered to perform the Q-transform, I met the problem.
Is this problem due to the current constraint to use the GWPY Q-transform? 

[Q-transform.docx](https://github.com/gwpy/gwpy/files/2693364/Q-transform.docx)

**Comment by duncanmmacleod** [comment]
@lupin0lin, I'm sorry it took so long for me to respond to this. I will take a look at your issue, and will post here whether I find a specific issue that can be fixed.

**Comment by duncanmmacleod** [comment]
actually, can you post your original data file, so that I can reproduce the issue myself?

**Comment by lupin0lin** [comment]
Dear Duncan,

In my test, I did not really use the gravitational wave data such as shown in my attachement.
In the attached file, the first column is the recording time, the second time is the cts (can be treated as the strain), and the third column is the error of the 2nd column.
The data is in evenly sampling, but I still want to ask whether the Q-transform package supported by pycbc or gwpy can deal with unevenly sampling data oor not?
In my attached file, you can see the separation of each data point is 5 second, consistent with the sampling rate of 0.2.
In my personal tests, I changes the sampling rate from 0.2 to 512 when I read the time series with GWPY.
Under such a condidtion, I can see the signal when I constrain a low range of Q (<5).
But comparing with the power spectrum obtained from dynamical FFT, the signal pattern is still different and I suspect that the choice of Q might be lower than 1.
The smallest Q I can set is 0.1, and I will see the bug if I set a Q value lower than it.
Even though I set such a low Q,  I still cannot get the expected pattern... 

[real_newrebin5.txt](https://github.com/gwpy/gwpy/files/2766511/real_newrebin5.txt)

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1002, please join us on gitlab to continue your contribution!
