### ISSUE TITLE
No module named nds2

### ISSUE THREAD

**Issue by matxil** [gwpy/gwpy#1019]
Hi, 
I tried to get data, using GWpy, with the following line in my code: 
`   ts_get_restricted_H1 = TimeSeries.get('H1:GDS-CALIB_STRAIN', starttime, endtime)`
But I get the following error: 
`  No module named nds2`
According to another issue on this forum, since I am a member of Virgo, I should be able to install "nds2", but when I try this with apt-get, I get informed that that does not exist (I am on an Ubuntu). So, how do I proceed?

Best regards, 

Machiel

**Comment by duncanmmacleod** [comment]
Hi @matxil, sorry for the delay (again) in replying. Officially we (LIGO-Virgo) don't provide packages for Ubuntu, so you likely can't install `nds2` with that. I recommend using [conda](https://conda.io) and install things from the `conda-forge` channel. You can find some information on https://docs.ligo.org/lscsoft/conda/, but the short version is:

1. Install conda
1. Configure the `conda-forge` channel:

   ```
   conda config --add channels conda-forge
   ```
1. Install NDS2:

   ```
   conda install python-nds2-client
   ```

**Comment by matxil** [comment]
Hi Duncan, 

Thank you very much for your reply. I will try conda in the following days.

> Officially we (LIGO-Virgo) don't provide packages for Ubuntu, so you likely can't install nds2 with that.

This surprised me a bit. Is there a particular type of Linux that you favour?
I am thinking of going to the Paris workshop of 8 - 10 April and was thinking about buying a new laptop for that. I thought the obvious choice would be to install Ubuntu (since it is the most common version of Linux nowadays) but do you recommend something else? I am assuming python 2.7 is still necessary?

As a matter of fact, I just saw that you will be giving a talk on that workshop too. I hope you don't mind if I ask you a few questions about this workshop too. I am working at IFAE and since a few months we are a member of the Virgo collaboration. I have been looking at some of the pages of GWOSC and already played with some tutorials both for PyCbc and GWpy. It would be interesting for me to know how more advanced the workshop in Paris will be. Will the workshop explain the software as it used officially inside the Virgo collaboration?

One question that is not really clear for why both PyCbc and GWpy are used, since they seem very similar. Are both discussed during the workshop? How to choose which one to use? In some Virgo articles, I also saw GSTlal mentioned, will GSTlal be explained in Paris too?

Best regards, 

Machiel Kolstein
