### ISSUE TITLE
Defaults on q_transform method result in large-memory objects

### ISSUE THREAD

**Issue by tjma12** [gwpy/gwpy#1050]
If I use the `TimeSeries.q_transform()` method with the default settings, the resulting arrays are sometimes taking up several GB of memory. I was able to push this down by tuning the arguments, would it be possible to tweak the defaults so that the average user doesn't run into memory issues if they're making several Q-transforms?

**Comment by alurban** [comment]
@duncanmmacleod, how do you feel about log-sampling the frequency axis by default to address @tjma12's point?

**Comment by duncanmmacleod** [comment]
Can we first think about explicitly using `float32` for the returned Q-transform objects? I think we don't need a 64-bit float in most circumstances.

**Comment by alurban** [comment]
Sure, I'll take a look.
