### ISSUE TITLE
timeseries.spectrogram2 seems to plot with reduced time resolution

### ISSUE THREAD

**Issue by areeda** [gwpy/gwpy#108]
Example:
gwpy-plot spectrogram --chan H1:CAL-DELTAL_EXTERNAL_DQ --start 1118051496 --duration 10 --out whistles.png --secpfft 0.300 --overlap 0.900 --nologf --fmin 3 --fmax 50 --imin 0.2 --norm --interactive

spectorgram2 result has shape (332, 2458) but image looks much coarser that it should.  Either many of the FFTs are (almost) the same or there is a problem in plotting:

![whistles](https://cloud.githubusercontent.com/assets/7607564/8379808/3973e4d0-1bd7-11e5-9a37-6e73f2e5ad64.png)

**Comment by areeda** [comment]
Just a note.  If your run that command in ipython the --interactive flag will leave
The time series object in data and the calculated spectrogram object in result.

**Comment by duncanmmacleod** [comment]
I'm now not convinced by this example. The frequency resolution is so low, that I think the eye is being fooled into thinking the time resolution is also bad. However, perhaps just some interpolation is needed to make the whole problem go away.

**Comment by duncanmmacleod** [comment]
this hasn't been touched in a while, will close and can be reopened later if still an issue.
