### ISSUE TITLE
Can't read gwf files

### ISSUE THREAD

**Issue by Cyberface** [gwpy/gwpy#1084]
Hey Duncan,

I'm trying to read some gwf files, from GWOS actually, with gwpy but running into some problems.

I installed via conda

```
conda create --name gwpy
conda activate gwpy
conda install -c conda-forge gwpy
conda install -c conda-forge ldas-tools-framecpp
```

Then I try to read some gwf frame file and I get the following error.
Any ideas?

```
data = TimeSeries.read(
    'H-H1_GWOSC_4KHZ_R1-1126259447-32.gwf',
    'H1:GWOSC-4KHZ_R1_STRAIN'
)
```

```
ImportError: no GWF API available, please install a third-party GWF library (framecpp, lalframe) and try again
```

**Comment by alurban** [comment]
Hi Sebastian, I believe the package you want is python-ldas-tools-framecpp, which is the one that has python bindings. Please try installing that and see if it resolves your problem.

**Comment by Cyberface** [comment]
YES THAT WORKED! Thanks so much @alurban !!

**Comment by Cyberface** [comment]
For future reference this is what I did

```
conda install -c conda-forge python-ldas-tools-framecpp
```
Not sure if this is in the docs but if not should it be somewhere?

**Comment by alurban** [comment]
@Cyberface, I just glanced over the gwpy docs and didn’t explicitly spot it anywhere, but it is documented in the LSCSoft conda docs: https://docs.ligo.org/lscsoft/conda/environments/environment-py37.html (requires LIGO.ORG credentials).

@duncanmmacleod, perhaps we can update the gwpy documentation to explicitly tell users to install python-ldas-tools-framecpp when installing with conda?

**Comment by duncanmmacleod** [comment]
@alurban, @Cyberface, the reason we don't just have gwpy depend on python2-ldas-tools-framecpp in the first place is that it isn't available for windows. I have attempted to reference `LDAStools.frameCPP` anywhere in the docs that talks about reading GWF files, so please open other tickets if that should be made more explicit. I am always happy to improve the documentation.

**Comment by Cyberface** [comment]
Is it possible to install a gwf frame package with only pip?

**Comment by duncanmmacleod** [comment]
@Cyberface, if you `pip install lalsuite`, `gwpy` will use `lalframe` for GWF reading. That interface is not fully-featured, so some actions are not available - but, simple `TimeSeries.read` will work. This does not work on MSWindows.

**Comment by Cyberface** [comment]
thanks!
