### ISSUE TITLE
NameError: name 'CachedDetectors' is not defined

### ISSUE THREAD

**Issue by eagoetz** [gwpy/gwpy#1095]
Installing gwpy using pip or with Macports with python-3.6, the import fails with the following output below. Happy to provide any other details you need to help resolve this issue. Thanks!

```
$ python3.6
Python 3.6.8 (default, Dec 30 2018, 13:04:41) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gwpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gwpy/__init__.py", line 35, in <module>
    from . import (
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gwpy/plot/__init__.py", line 27, in <module>
    from . import (
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gwpy/plot/gps.py", line 37, in <module>
    from ..time import (to_gps, from_gps)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gwpy/time/__init__.py", line 36, in <module>
    from lal import LIGOTimeGPS
  File "/opt/lscsoft/lib/python3.6/site-packages/lal/__init__.py", line 18, in <module>
    cached_detector_by_prefix = dict((cd.frDetector.prefix, cd) for cd in CachedDetectors)
NameError: name 'CachedDetectors' is not defined
```

**Comment by duncanmmacleod** [comment]
Your `lal` install is broken, how did you install it?

**Comment by duncanmmacleod** [comment]
Side note, I'm not really maintaining macports for gwpy, and in general macports is being phased out in favour of conda. So, I recommend you try that to see if it works for you.

**Comment by eagoetz** [comment]
@duncanmmacleod I have not installed any version of lal for python. Is that required? If so, it was not listed in the dependencies. What do you recommend? Thanks!

**Comment by duncanmmacleod** [comment]
`lal` is not a requirement for gwpy, but if it is installed, gwpy will try to use it. Your problem here is that `lal` is present, but the installation is broken. So, either remove it, or reinstall it.

**Comment by eagoetz** [comment]
I see, ok. I checked and PYTHONPATH is pointing to `/opt/lscsoft/lib/python3.6/site-packages:` so I rebuilt LAL, making sure that swig was enabled. All went fine but I still get the same error message when trying to import gwpy. Do I need to reload something? Sorry for the hassle!

**Comment by duncanmmacleod** [comment]
It looks like you have installed gwpy with macports, I recommend just installing lalsuite with macports. You can do that via

```shell
sudo port install lalapps
```

or, if you just want the useful bits:

```shell
sudo port install py36-lal py36-lalsimulation
```

**Comment by eagoetz** [comment]
@duncanmmacleod Thanks for your help. Yes, I had installed gwpy with macports; sorry if that was unclear. I tried the just the useful bits (py36-lal and py36-lalsimulation) and still found the same error. So that didn't fix the issue.

I then installed lalapps via macports as your first suggestion (unclear why I need to do this in addition to my own install, but, ok, trying anyway), but this also had the same error trying to import gwpy.

Any other suggestions? Seems like pip and macports both have the same problem, but really unclear why.

**Comment by eagoetz** [comment]
@duncanmmacleod I removed all trace of swig-wrapped lalsuite in my self-compiled lalsuite lib directory and now I can import gwpy successfully. So, yes, my lal build was somehow broken and making gwpy import fail. I'll work on that issue separately, so I think this issue can be closed. Thanks again for your help to diagnose this issue!
