### ISSUE TITLE
TimeSeries.find gets too much minute trend data

### ISSUE THREAD

**Issue by andrew-lundgren** [gwpy/gwpy#1106]
Using the ligo-py37 environment (in Jupyter on CIT):

```python
from gwpy.timeseries import TimeSeries
tmp3f = TimeSeries.find('H1:IMC-VCO_FREQUENCY.rms,m-trend',\
                                '2019-04-29 05:00:00',\
                                '2019-04-29 22:00:00',\
                                frametype='H1_M', nproc=6)
print(tmp3f.duration, (22-5)*3600)
```
gives 64800.0 s 61200

It's getting a whole extra hour of data, maybe because it's just taking everything in the last frame? It gives the correct result when using `.fetch`.

Also, it takes over a minute to get 4 kb, even after repeated accesses. This may be a problem with the filesystem though.

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1106, please join us on gitlab to continue your contribution!
