### ISSUE TITLE
gwpy.segments takes a very long time to load

### ISSUE THREAD

**Issue by jrollins** [gwpy/gwpy#1118]
```
jameson.rollins@ldas-pcdev1:~ 0$ time python -c 'import gwpy.segments'

real    0m4.958s
user    0m4.640s
sys     0m5.101s
jameson.rollins@ldas-pcdev1:~ 0$ 
```
5 seconds is a very long time to load a single module.

**Comment by duncanmmacleod** [comment]
@jrollins, thanks for the report, this has been a long-standing annoyance. The main issue here is that the top-level `gwpy.__init__` module imports `gwpy.plot` to register the gwpy `Axes` as the default axes for all matplotlib operations. This then cascades to importing basically everything, including astropy, h5py, matplotlib, numpy, scipy.signal, which each take 0.2-0.5s to load.

Without restructuring the code a lot, there isn't a clean way to decouple these things, but I will leave this ticket open as a reminder to try and improve things where we can.
