### ISSUE TITLE
Time axis formatting occasionally malformed

### ISSUE THREAD

**Issue by alurban** [gwpy/gwpy#1130]
When using matplotlib-3.1+ and the latest head of gwpy `master`, I occasionally see formatting issues on time axes:

![H1-GDS_CALIB_STRAIN-qscan_whitened-4](https://user-images.githubusercontent.com/5273800/60907092-491fbe80-a23e-11e9-9fc9-994382556197.png)

**Comment by duncanmmacleod** [comment]
@aurban, are you able to post a minimal working example to reproduce the issue?

**Comment by duncanmmacleod** [comment]
I was **not** able to reproduce this using the following code, please advise:

```python
from gwpy.timeseries import TimeSeries

gps = 1246080201.53123

data = TimeSeries.get("H1:GDS-CALIB_STRAIN", gps-16, gps+16, verbose=True)
qscan = data.q_transform(outseg=(gps-2, gps+2))

plot = qscan.plot(yscale="log", ylabel="Frequency [Hz]")
ax = plot.gca()
ax.set_epoch(gps)
ax.colorbar(clim=(0, 15), label="Normalized energy")
plot.show()
```

**Comment by alurban** [comment]
@duncanmmacleod, curiously, I'm also no longer able to reproduce the issue using the latest `HEAD` of gwdetchar and gwpy with matplotlib-3.1.1:

https://ldas-jobs.ligo.caltech.edu/~alexander.urban/wdq/Network_1246080201.53/

Shall I close this ticket?
