### ISSUE TITLE
ModuleNotFoundError: No module named 'gwpy.plotter'

### ISSUE THREAD

**Issue by iarat** [gwpy/gwpy#1133]
I get an error when I try to plot a spectrogram of both interferometers following the steps present here: https://github.com/gw-odw/odw-2018/blob/master/gwpy/3%20-%20Q-transforms%20in%20GWpy.ipynb
The error is this one:
```pytb
ModuleNotFoundError
Traceback (most recent call last)
<ipython-input-19-607227e983fb> in <module>
      5 # create the figure and plot the data on separate axes
      6 from matplotlib import pyplot
----> 7 from gwpy.plotter import TimeSeriesPlot
      8 
      9 plot = pyplot.figure(figsize=(8, 8), FigureClass=TimeSeriesPlot)

ModuleNotFoundError: No module named 'gwpy.plotter'
```

It seems to me that I am not importing properly 'from gwpy.plotter import TimeSeriesPlot'

I have tried to updated my gwpy and did not work out.
I am using jupyter notebook.

**Comment by duncanmmacleod** [comment]
@iarat, the workbooks from the 2018 open data workshop are out-of-date, gwpy has moved past them. You can either install an old copy of gwpy (prior to `0.12.0`, I think), or try instead looking at the 2019 open data workshop notebooks:

https://github.com/gw-odw/odw-2019/

In general, the `gwpy.plotter` module was renamed `gwpy.plot` and a bunch of objects renamed or removed, so you want to replace:

```
from gwpy.plotter import TimeSeriesPlot
```

with

```
from gwpy.plot import Plot
```

More documentation on how to plot in recent version of gwpy can be found here:

https://gwpy.github.io/docs/stable/plot/
