### ISSUE TITLE
errors with FrAdcData stream and FrHeader structure when reading frame data

### ISSUE THREAD

**Issue by laurelvwhite** [gwpy/gwpy#1135]
When I run TimeSeriesDict.find(channels, start, end) on the O2 channels with start and end times from O2, some times fail with an error similar to one of the following:

RuntimeError: After reading object of type: FrAdcData stream is no longer in good state. ( Frmae: 0 ChannelType: H1:NGN-CS_L4C_Z_9_OUT_DQ offset: 1543791589)

RuntimeError: Failed to read the core of the FrHeader structure. (18446744073709551615[0:18446744073709551615] != 7)

I am running on CIT pcdev-6 with numpy==1.7.1, gwpy==0.15.0, and astropy==1.3.2. I am using a long channel list, but that does not seem to be the problem since many times succeed in getting data from all channels. The times that fail and the channel list are attached.
[failed_times.txt](https://github.com/gwpy/gwpy/files/3383841/failed_times.txt)
[channels.txt](https://github.com/gwpy/gwpy/files/3383875/channels.txt)

**Comment by duncanmmacleod** [comment]
@laurelvwhite, unfortunately, I think this looks like an issue with corrupt GWF files, or simply transient errors in reading them (i.e. if you run the same command again, it might pass).

Can you please post a minimal working example of code to reproduce the failure for one of the failed times?

**Comment by laurelvwhite** [comment]
@duncanmmacleod Seems like they were transient errors after all. I had tried repeatedly before and encountered the same errors, but everything is running fine today.

**Comment by duncanmmacleod** [comment]
I'm happy that it's now working for you.
