### ISSUE TITLE
qtransform 'out' variable referenced before assignment

### ISSUE THREAD

**Issue by avivajpeyi** [gwpy/gwpy#1144]
The [QTiling.transform()](https://github.com/gwpy/gwpy/blob/ac2d494d2045ac0afdbfda12486087a7e305db5d/gwpy/signal/qtransform.py#L166) assigns a variable 'out' in an 'if' statement. This can lead to the following error:

`UnboundLocalError: local variable 'out' referenced before assignment`

Example stacktrace:
```
 qax.imshow(data.q_transform())

  File "/home/avi.vajpeyi/.conda/envs/timeshifts/lib/python3.7/site-packages/gwpy/timeseries/timeseries.py", line 2108, in     q_transform
    mismatch=mismatch, search=search)

  File "/home/avi.vajpeyi/.conda/envs/timeshifts/lib/python3.7/site-packages/gwpy/signal/qtransform.py", line 686, in q_scan
    frange=frange).transform(data, **kwargs)

  File "/home/avi.vajpeyi/.conda/envs/timeshifts/lib/python3.7/site-packages/gwpy/signal/qtransform.py", line 202, in transform
    return (out, nind * weight / nplanes)

UnboundLocalError: local variable 'out' referenced before assignment

```
Maybe `out` should be initialised to some value? Or is it the case that if `out` is not set, then an exception should be raised (because `out` should always be set in the if statement)?

**Comment by avivajpeyi** [comment]
Example code to reproduce:

```
import gwpy
import matplotlib
import matplotlib.pyplot
from gwpy.plot import Plot
from gwpy.segments import DataQualityFlag
from gwpy.timeseries import TimeSeries
import argparse

matplotlib.use("Agg")


def get_time_data(start_time, end_time, ifo):
    channel = "{}:GDS-CALIB_STRAIN_CLEAN".format(ifo)
    print("Getting {}: {}-{}".format(channel, start_time, end_time))
    return TimeSeries.get(channel, start_time, end_time)


def data_plot(det, data):
    """
    Code adapted from: https://gwpy.github.io/docs/latest/plot/colorbars.html#another-example

    Saves a timeseries and Q-transform spectrogram plot of the detector's data.

    Parameters
    ----------
    det: str
        The detector name corresponding to the key in data-dict
    data: gwpy.TimeSeries
        the timeseries strain data of a detector

    Returns
    -------
    None

    save a figure of the data

    """
    det_color = {"H1": "gwpy:ligo-hanford", "L1": "gwpy:ligo-livingston"}
    plot, axes = matplotlib.pyplot.subplots(nrows=2, sharex=True, figsize=(8, 6))
    tax, qax = axes  # timeseries axis, q-transform spectogram axis
    tax.plot(data, color=det_color[det])
    tax.set_xlabel("")
    tax.set_xscale("auto-gps")
    tax.set_ylabel("Strain amplitude")
    qax.imshow(data.q_transform())
    qax.set_yscale("log")
    qax.set_ylabel("Frequency [Hz]")
    qax.colorbar(label="Normalised energy")
    plot.savefig("{}_data.png".format(det))


def main():
    start_time = 1241336560.65
    end_time = start_time + 4

    for det in ["H1", "L1"]:
        channel = "{}:GDS-CALIB_STRAIN_CLEAN".format(det)
        print("Getting {}: {}-{}".format(channel, start_time, end_time))
        data = TimeSeries.get(channel, start_time, end_time)
        print("Plotting data")
        data_plot(det, data)


if __name__ == "__main__":
    main()
```

**Comment by alurban** [comment]
@avivajpeyi, thank you for spotting this and apologies for the delay getting back to you, we likely should include some sort of more informative error message to catch this corner case. I can fix that for the next release. In the meantime, I notice that you're only reading in 4 seconds of data, and trying to compute a Q-transform on that; in general, it's better to do something like the following:

* Read in a longer record of data (say, 64 seconds)
* Measure an ASD based on this longer record
* Whiten based on this ASD
* Compute the Q-transform
* Crop down to the 4 seconds you want to plot

The good news is, every single one of these steps is done for you by the `TimeSeries.q_transform()` method, including (optionally) the last one. You need only change 5 lines and add two global variables to make this happen:

```python
START = 1241336560.65
END = START + 4

...

def data_plot(det, data):
    ...
    qax.imshow(data.q_transform(outseg=(START, END)))
    ...

def main():
    for det in ["H1", "L1"]:
        ...
        print("Getting {}: {}-{}".format(channel, START - 30, END + 30))
        data = TimeSeries.get(channel, START - 30, END + 30)
        ...
```

Please give this a shot, and let me know if it works for you.

**Comment by alurban** [comment]
@avivajpeyi, ignore my earlier comment, after reproducing your error I now understand what the issue is:

```python
>>> data = TimeSeries.get('H1:GDS-CALIB_STRAIN_CLEAN', 1241336560.65, 1241336564.65)
>>> print(data)
<TimeSeries([nan, nan, nan, ..., nan, nan, nan]
            unit=Unit(dimensionless),
            t0=<Quantity 1.24133656e+09 s>,
            dt=<Quantity 6.10351562e-05 s>,
            name='H1:GDS-CALIB_STRAIN_CLEAN',
            channel=<Channel("H1:GDS-CALIB_STRAIN_CLEAN" [reduced], 16384.0 Hz) at 0x1163cc710>)>
```

The data for `H1:GDS-CALIB_STRAIN_CLEAN` during this time is all `nan`s, which leads to an error when trying to compare that to a dummy variable set to zero. That's the corner case I'll have to capture. On your end, the only thing I can immediately think of is that you might want to double check that both H1 and L1 are in observing mode at the time you're trying to analyze.
