### ISSUE TITLE
Using numpy's truth methods with timeseries

### ISSUE THREAD

**Issue by SeanDS** [gwpy/gwpy#1149]
I'd like to get a truthiness array for my timeseries. Since numpy is used to store the underlying data, I figured I could use `np.where`, but it's not working. It seems like `astropy` is causing the trouble:
```python
>>> np.where(data > 20)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/astropy/units/quantity.py", line 408, in __array_prepare__
    .format(function.__name__))
astropy.units.core.UnitsError: Can only apply 'greater' function to dimensionless quantities when other argument is not a quantity (unless the latter is all zero/infinity/nan)
```
(`data` is a `TimeSeries`)
I can get around this by casting to an `np.ndarray`:
```python
data = np.array(data)
```
...but I'd rather not have to do this (to preserve units and other metadata). Is there a way to get access to the underlying data without this astropy error?

**Comment by alurban** [comment]
@SeanDS, could you try:

```python
>>> print(data > 20 * data.unit)
```

For context, gwpy's `TimeSeries` class _does_ give you access to the underlying data, _including_ units and other metadata (emphasis intended for clarity's sake). So when arithmetically manipulating a `TimeSeries` object, it's important (though often frustrating) to include the units.

**Comment by alurban** [comment]
Btw, in case it's helpful, you can also get a data-quality flag by thresholding a `TimeSeries`:

```python
>>> highdata = data > 20 * data.unit
>>> flag = highdata.to_dqflag(round=True)
>>> print(flag)
```

**Comment by SeanDS** [comment]
Thanks. I decided just to check `data.value` as per your suggestion since I am just checking the data, not manipulating it.

Your data quality flag example sounds intriguing. I'm not familiar with how this works. I'm an experimentalist and just want to check if some data from the lab is above threshold. I'm essentially just counting how many times the data is above or below some value and returning true or false if it's more than half of the time. I'm not e.g. building frames with special flags. Is this data quality flag stuff useful for this sort of application or would you suggest just continuing to do what I'm doing?

For reference, [here](https://git.ligo.org/sean-leavey/pemwatch/blob/396b776d12e83ef57fe804b55b10c7dbb4a787f9/pemwatch/watchdog.py#L122) is some of my code that checks the data. If you have a suggestion for how to use the data quality flag stuff with this, I'd be glad to hear it!

**Comment by alurban** [comment]
@SeanDS, if I understand your application correctly, it may be more computationally efficient to convert to a data-quality flag and do your calculation that way:

```python
def is_saturated(data, threshold):
    """Determines whether a given data series saturates a given threshold
    more than 50% of the time
    """
    highdata = data > threshold * data.unit
    flag = highdata.to_dqflag(round=True)
    return abs(flag.active) / abs(flag.known) > 0.5
```

The last line compares how much time is spent above the threshold (`flag.active`) against the total duration of the timeseries (`flag.known`). Does that make sense for your needs?

**Comment by SeanDS** [comment]
Yeah, that looks great! Where can I learn more about data quality flags? Can they do more advanced stuff? Is there a repository somewhere with code examples?

**Comment by alurban** [comment]
@SeanDS, gwpy isn't generally used by searches -- much more often, it's used for detector characterization, which is why we like to keep things modularized and general-purpose. Here's a fairly complete accounting of what `DataQualityFlag` objects can do:

https://gwpy.github.io/docs/stable/segments/index.html#the-dataqualityflag

One of the biggest advantages of `DataQualityFlag` is that it allows you to do segment logic in an easy and intuitive way, which is another way of saying that taking intersections and unions is our bread and butter.

As a side note, related objects are the `Segment` and `SegmentList`. The latter is an iterable over the former, and the `DataQualityFlag` attributes `.active` and `.known` return a `SegmentList`.

**Comment by alurban** [comment]
(Are you working at the 40-meter prototype? If so, say hi to Rana and Alan for me)

**Comment by SeanDS** [comment]
This stuff is so cool. It's great when you discover someone else solved your problem already! I think this is exactly what I need. I just need to think about how to combine a binary tree of operations as defined in our watchdog config files into one `DataQualityFlag`, i.e. convert this...
```yaml
      and:
        - channel: G2:PEM-BASE_T.rms,m-trend
          is_changing: true
        - or:
          - channel: G2:PEM-BASE_T.rms,m-trend
            value: 22
            fraction_above: 0.5
          - channel: G2:PEM-BASE_T.rms,m-trend
            value: 19
            fraction_below: 0.5
```
...into a `DataQualityFlag`.

Follow-on question: is it possible to take an existing `DataQualityFlag` and ask it to fetch passing/failing data?

Regarding your question: I'm at a prototype, but not the 40 m. I'm at the AEI 10 m prototype.

**Comment by SeanDS** [comment]
Are there some special methods to plot `DataQualityFlags` on top of their corresponding data? Like something that adds e.g. shading of the background during which the flags are active? I see lots of plot methods everywhere in the code but they don't appear to do this.

**Comment by alurban** [comment]
This example walks through how to display data-quality segments, both separately and together with other data products:

https://gwpy.github.io/docs/stable/examples/miscellaneous/open-data-spectrogram.html

The example given is of a spectrogram, but the same principle applies for anything that would have a time axis.

I believe `SegmentList` objects (like regular lists) have an `append` method that lets you add on additional segments, and perhaps an `extend` method that lets you extend the duration of `known` segments. If you're familiar with the summary pages (which I'm now in charge of), this architecture is used frequently under-the-hood to grab and display segments based on timeseries data.

You also have the option of querying for data-quality flags from the segment database, but I'm much less familiar with GEO segments than I am with LIGO ones, so I'm not sure if e.g. the watchdogs are already populated there. On the other hand, if you're interested in having summary pages, I can try to hook you up with that once I get back to the U.S. from Japan.

**Comment by SeanDS** [comment]
Again that looks very useful, thanks!

RE querying: I'm not using any GEO data, nor any predefined watchdogs, this is a completely new enterprise for the AEI prototype with no existing segment databases.

RE summary pages: I'm setting up our system to post plots to our logbook, so no need for separate summary pages. Thanks for the offer though.

**Comment by duncanmmacleod** [comment]
Can this ticket be closed?

**Comment by SeanDS** [comment]
Yes - closing.
