### ISSUE TITLE
Date ticks

### ISSUE THREAD

**Issue by SeanDS** [gwpy/gwpy#1150]
I'd like to plot a timeseries with real dates as the x-axis, like "2019-09-01 12:00:00" instead of the usual epoch + offset style. Is this possible with a parameter in the call to `gwpy.plot.Plot(...)`?

**Comment by alurban** [comment]
@SeanDS, gwpy is only using matplotlib under-the-hood, so you can freely customize your axis labels in the usual way:

```python
plot = data.plot()  # a call to gwpy.plot.Plot() will also work
ax = plot.gca()
ax.set_xticklabels(...)
```

**Comment by SeanDS** [comment]
Thanks - but is there some way to do this automagically? The `dtt` CDS tool for example can do this and it would be nice if there was feature parity.

**Comment by alurban** [comment]
At present, no, there's no way to get automagic CDS-style date formatting. You're actually the second person I've heard express a desire for it though, so maybe we should consider including it in a future release (likely **not** in time for 1.0.0).

@duncanmmacleod, what do you think?

**Comment by SeanDS** [comment]
There's also an [open issue](https://git.ligo.org/cds/ndscope/issues/122) (from me) about this for [ndscope](https://git.ligo.org/cds/ndscope) too. Maybe there could be some code added to a shared dependency that can handle this conversion.

Paging @jrollins too...

**Comment by SeanDS** [comment]
This is still something I'd like to have available in gwpy so I looked into this a little further. Matplotlib has [handling](https://matplotlib.org/gallery/text_labels_and_annotations/date.html) for display of dates, including an auto-formatter and auto-locator, but it needs to be supplied dates in its silly datenum format (days since 0001-01-01 UTC, plus 1...).

The only way I've figured out how to do this so far with gwpy data is to bypass the gwpy plotting methods and do the conversion manually:

```python
    import matplotlib.pyplot as plt
    from matplotlib.dates import date2num, AutoDateFormatter, AutoDateLocator
    from gwpy.time import from_gps

    data = TimeSeries.get(...)

    locator = AutoDateLocator()
    formatter = AutoDateFormatter(locator)

    fig, ax = plt.subplots()
    ax.plot(date2num([from_gps(t) for t in data.times.value]), data.value)
    ax.xaxis.set_major_locator(locator)
    ax.xaxis.set_major_formatter(formatter)
    fig.autofmt_xdate()  # Rotate date tick text so they don't take up so much horizontal space.
    plt.show()
```

For a 10 day date span, it looks like this:
![Figure_1](https://user-images.githubusercontent.com/5225190/92388812-6f254500-f107-11ea-8071-aa806c7dce84.png)

Zooming in further, the date ticks change automatically:
![Figure_2](https://user-images.githubusercontent.com/5225190/92388917-91b75e00-f107-11ea-8c1c-fce723a2cdd8.png)
![Figure_3](https://user-images.githubusercontent.com/5225190/92388923-94b24e80-f107-11ea-95fb-7c7236d8838e.png)

The default date formats for each zoom level are a bit weird to me, showing only the hour but not minute and day but not month or year. These are defined in `matplotlib.rcParams` (see `matplotlib.dates`) and can be overridden.

Ideally I'd like to be able to plot something in gwpy with `date.plot(..., xscale='auto-gps-date')` or similar, and have it behave like Matplotlib's date plotting, rescaling depending on zoom levels. One way could be to have something in the gwpy plotting methods to detect if this scale is set and do the above date conversion before calling the actual plotting method, and just use the matplotlib locators and formatters.

Another approach could be to completely reimplement the `matplotlib.dates` module in `gwpy` but in a way that handles GPS times. This would be far more work but would allow finer control over formatting and so on.

Is this something that gwpy could support one day?

**Comment by rutujagurav** [comment]
This would be an excellent feature! 
I often grab some data using `TimeSeries.get()` and want to know a human readable date-time for a particular timestep that I hover my mouse over. It is easy enough to do with matplotlib widgets in VS Code notebooks or Jupyter Notebooks and it shows me the (x,y) values - see figure below. But the x values are GPS timestamps.  

<img width="795" alt="image" src="https://github.com/gwpy/gwpy/assets/14856287/4e3d032e-d83a-46e0-a720-29fde247f02a">

**Comment by duncanmmacleod** [comment]
I would be more than happy to receive a pull requests that implements an alternative `xscale` (as matplotlib calls it, I think). I am unlikely to get to this soon, but hopefully won't forget for another 4 years like last time.

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1150, please join us on gitlab to continue your contribution!
