### ISSUE TITLE
Importing matplotlib hijacks main axes class

### ISSUE THREAD

**Issue by lpsinger** [gwpy/gwpy#1187]
I appreciate gwpy's lovely and convenient builtin visualization capabilities. However I was recently shocked to find out that importing gwpy hijacks the Matplotlib axes class and makes a whole bunch of stylistic changes, *some of which I cannot undo by calling `plt.rcdefaults()`*. Here's an example where it makes all of the linestyles in the legends appear extra-thick. This is not an rcparam settings; it's baked into the `gwpy.axes.Axes` class and so I cannot get rid of it!

Please at least register `gwpy.axes.Axes` with a projection name so that it does not globally monkeypatch Matplotlib.

![Screen Shot 2019-11-25 at 21 25 24](https://user-images.githubusercontent.com/728407/69594470-704b1280-0fca-11ea-82f7-93083b0c0a7c.png)

**Comment by duncanmmacleod** [comment]
@lpsinger, thanks for your report. You are seeing the combination of two modified legend defaults, both of which can be undone relatively easily (IMO), those are (1) the handle length (the horizontal extent of the legend lines), and (2) the linewidth (the vertical extent of those lines).

1. you can do any of the things you've already done: use`rcdefaults()`, set `legend.handlelength` in RC manually, or set the environment variable `GWPY_RCPARAMS` to something falsy, e.g. `GWPY_RCPARAMS=false` to disable GWpy's custom RC setting entirely. See here for documentation of that variable:

   https://gwpy.github.io/docs/stable/env.html

2. GWpy uses a custom default handler for lines in legends, which can be undone by passing `handler_map=None` to the `ax.legend` call, as documented here:

   https://gwpy.github.io/docs/stable/plot/legend.html

   Unfortunately `legend.linewidth` is not an rc setting anywhere, so it can't be customised in the standard way. Using a custom handler is the least invasive way I can think of to modify the default legend appearance.

So, the following should allow you to get back to default matplotlib visuals:

```python
import os
os.environ('GWPY_RCPARAMS', 'false')

import numpy
from matplotlib import pyplot

t = numpy.linspace(0, 2 * numpy.pi)
pyplot.plot(t, numpy.sin(t), '-', label='sin')
pyplot.plot(t, numpy.cos(t), '--', label='cos')
pyplot.plot(t, 0 * t, ':', label='zeros')
pyplot.legend(handler_map=None)
pyplot.show()
```

I'm happy to hear suggestions on how to minimise the impact, or improve the documentation, of gwpy's plot customisations. They used to be significantly more aggressive, but have been scaled back and integrated in cleverer ways than they used to, so everything should be 'trivially' undoable.

**Comment by lpsinger** [comment]
The legend behavior is one clear example where it would be better to submit a patch upstream to matplotlib.

**Comment by lpsinger** [comment]
The GPS time axis support could be handled without monkey patching in a manner similar to `astropy.visualization.units.quantity_support`.

**Comment by thuiop** [comment]
Bumping this, I am not sure why the Axes are monkeypatched rather than simply being a projection. It does not make sense to me that a user who may only be interested in e.g. TimeSeries (and the convenient way it can be used to access data) should have to deal with undoing the modifications made to matplotlib. Especially since the intended basic use seems to be to use the `.plot()` methods of the objects, which should be able to take care of creating the correct Axes with the correct rcparams...

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1187, please join us on gitlab to continue your contribution!
