### ISSUE TITLE
FrqeuencySeries read from LIGO-LW XML document has incorrect f0

### ISSUE THREAD

**Issue by lpsinger** [gwpy/gwpy#1189]
When a FrequencySeries is read from a LIGO-LW document, it has an incorrect f0.

```pycon
>>> import lal.series
>>> import glue.ligolw.utils
>>> from gwpy.frequencyseries import FrequencySeries
>>> psds = lal.series.read_psd_xmldoc(glue.ligolw.utils.load_filename('O3_HLV.xm
l', contenthandler=lal.series.PSDContentHandler))
>>> psd = psds['H1']
>>> psd.f0
10.0
>>> psd = FrequencySeries.from_lal(psd)
>>> psd.f0
<Quantity 10. Hz>
>>> psd.frequencies[0]
<Quantity 10. Hz>
>>> psd = FrequencySeries.read('O3_HLV.xml', instrument='H1')
>>> psd.f0
<Quantity 0. Hz>
>>> psd.frequencies[0]
<Quantity 0. Hz>
```

**Comment by lpsinger** [comment]
For the sample file O3_HLV.xml above, see https://gist.github.com/lpsinger/9f31d63372e700a0860d5db7a4c372ed.

**Comment by duncanmmacleod** [comment]
Thanks @lpsinger, this looks like an easy fix. I'm a little confused however; the document you link includes a complete frequency array alongside the amplitude values. However, it looks like [`lal.series` is completely ignoring the existing frequency array](https://github.com/lscsoft/lalsuite/blob/ab851e9f24764197954e6b4635df95bf8fa8605f/lal/python/lal/series.py#L97-L105), and only using the `Start` and `Scale` parameters of the containing `<Dim>`.

Should that dimensional array be respected, or can gwpy just rely entirely on the `Start` and `Scale` as well?

**Comment by duncanmmacleod** [comment]
Actually, this makes me wonder if the example document is actually compliant with the standard - can you confirm whether the `Stream` elements are supposed to be relative to the dimension properties, or absolute?

**Comment by lpsinger** [comment]
I don't know, but this was produced by `lal.series`.

**Comment by duncanmmacleod** [comment]
I know, I'm just not sure whether this is a bug in `gwpy`, or a bug in `lal.series`. There seems to be no documentation of the `Start` and `Scale` attributes of the `<Dim>` tag.

**Comment by lpsinger** [comment]
This is the same code that gstlal uses to prepare psd.xml.gz files for GraceDB. So can we ask Kipp?

**Comment by lpsinger** [comment]
Where is the standard?

**Comment by duncanmmacleod** [comment]
I've emailed you, Kipp, and John Z to try and work out the answer.

The closest thing I can find to policy is https://dcc.ligo.org/LIGO-T980091, but that seems impressively out-of-date.
