### ISSUE TITLE
qtransform.transform variable "out" not always assigned before being referenced

### ISSUE THREAD

**Issue by geoffreymo** [gwpy/gwpy#1190]
https://github.com/gwpy/gwpy/blob/master/gwpy/signal/qtransform.py#L203,

which results in errors such as these in gwcelery's qtransforms:
https://sentry.io/organizations/ligo-caltech/issues/1358378586/events/8b0470bfa25d457bb5749c68551f4553/?environment=production&project=1425216

**Comment by duncanmmacleod** [comment]
@alurban, didn't we fix this already?

**Comment by duncanmmacleod** [comment]
Ping @alurban.

**Comment by alurban** [comment]
@geoffreymo, apologies for the delay responding. I believe @duncanmmacleod is correct, we caught and fixed this error in the gwpy-1.0.0 release, but I see from the link provided that your environment has gwpy-0.15.0. If you update to 1.0.0 and try again, I believe the problem should resolve.

There are also newer versions of gwdetchar, hveto, and gwsumm available, if those packages are interesting to you.

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1190, please join us on gitlab to continue your contribution!
