### ISSUE TITLE
Problem in TimeSeries.fetch_open_data()

### ISSUE THREAD

**Issue by kderakhshani** [gwpy/gwpy#1194]
When I execute:

**h1 = TimeSeries.fetch_open_data('H1', 1126259457, 1126259467)**

(from https://gwpy.github.io/docs/stable/overview.html)
I get the ten-second data in less than 10s.
However, when I choose another ten-second segment: (ex)

**h1 = TimeSeries.fetch_open_data('H1', 1126250000, 1126250010)**

after a long time(~3 minutes) and ~25MB download, I get this error:

  **File "/home/master/miniconda3/lib/python3.7/site-packages/astropy/utils/data.py", line 1097, in download_file
    raise urllib.error.URLError(e)
URLError: urlopen error The read operation timed out**

**Comment by duncanmmacleod** [comment]
Hi @kderakhshani, thanks for the report. The 25Mb download is normal, and equates to 1 4096-second file that is required to get the 10 seconds you requested (currently that's the smallest chunk size that can be accessed). You can see more details by adding `verbose=True` to your request:

```
>>> from gwpy.timeseries import TimeSeries
>>> print(TimeSeries.fetch_open_data('H1', 1126250000, 1126250010, verbose=True))"
Fetched 1 URLs from www.gw-openscience.org for [1126250000 .. 1126250010))
Downloading https://www.gw-openscience.org/archive/data/O1/1126170624/H-H1_LOSC_4_V1-1126248448-4096.hdf5
|==============================================================|  25M/ 25M (100.00%)        12s
Reading data... [Done]
TimeSeries([nan, nan, nan, ..., nan, nan, nan]
           unit: dimensionless,
           t0: 1126250000.0 s,
           dt: 0.000244140625 s,
           name: Strain,
           channel: None)
```

The `URLError` is not something we can really diagnose in GWpy, since it's just the result of an issue communicating between your machine and the Open Data host (gw-openscience.org). Can you confirm whether the issue is reproducible?

**Comment by kderakhshani** [comment]
Hi @duncanmmacleod 
Thank you for your reply.
The error is apparently not reproducible. I've just checked it again and I've downloaded it without error. Now, my questions are:
1) What is the difference between your 10s download (I mean ('H1', 1126259457, 1126259467) in 
https://gwpy.github.io/docs/stable/overview.html   with about 0.5MB download) and mine ('H1', 1126250000, 1126250010) that downloads a total 25MB chunk?
The only thing I found is that the former one is around an event: GW150914. Does that make a difference?

2) When I Timeseries.read() the downloaded 25MB file and then TimeSeries.write() it in hdf5 format, I get a 11KB file. For the.gwf format, it is about 8KB. This is not so efficient. Where is the rest of 25MB? Is it lost? How can I save ALL data included in a fetched file(ex. for future use)?

**Comment by duncanmmacleod** [comment]
@kderakhshani,

1. This is all down to the way that data are distributed across different _datasets_ by GWOSC; data associated with GW detection events are stored in their own 'event' datasets (which are quite short), while all data for the O1 and O2 data-taking epochs are stored in longer files that cover the entire period. `gwosc` (the python package) attempts to minimise the download size by selecting the dataset that includes the shortest files. This is typically an event dataset, so the 10s download is discovered as part of the `GW150914` dataset, in a file that is only 32-seconds long, while the other segment (1126250000, 1126250010) is only available in part of a 4096-second file:

  ```python
>>> from gwosc.datasets import find_datasets
>>> print(find_datasets(detector='H1', segment=(1126259457, 1126259467)))
['GW150914', 'GWTC-1-confident', 'GWTC-1-marginal', 'O1', 'O1_16KHZ']
>>> print(get_urls('H1', start=1126259457, end=1126259467, dataset='GW150914'))
['https://www.gw-osc.org/catalog/GWTC-1-confident/data/GW150914/H-H1_GWOSC_4KHZ_R1-1126259447-32.hdf5', 'https://www.gw-osc.org/catalog/GWTC-1-confident/data/GW150914/H-H1_GWOSC_4KHZ_R1-1126257415-4096.hdf5']
>>> print(get_urls('H1', start=1126259457, end=1126259467, dataset='O1'))
['https://www.gw-openscience.org/archive/data/O1/1126170624/H-H1_LOSC_4_V1-1126256640-4096.hdf5']
>>> print(get_urls('H1', start=1126250000, end=1126250010))
['https://www.gw-openscience.org/archive/data/O1/1126170624/H-H1_LOSC_4_V1-1126248448-4096.hdf5']
  ```
  [the `-32.hdf5` and `-4096.hdf5` file extensions tell you how many seconds of data are stored in the file, 32 s and 4096 s respectively.]

2. There are multiple datasets stored in each HDF5 file provided by GWOSC, so it's most likely that you are only reading a single dataset, then writing only that to the file. Are you also restricting the GPS times in `TimeSeries.read`?

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1194, please join us on gitlab to continue your contribution!
