### ISSUE TITLE
When plotting integer timeseries, y-axis labels require math to understand

### ISSUE THREAD

**Issue by jrsmith02** [gwpy/gwpy#120]
When plotting a time series of a channel that happens to be an integer during the time plotted, the y-axis labels get strange. Here is a snippet of code: 
```bash
/usr/local/ldvw/bin/gwpy-plot timeseries --chan 'H1:OMC-DCPD_B_GAIN' --start 1117831923 --duration 3 --out '/usr/local/tomcat_base/temp/ldvw5084635943129869409.png'
```
and here's the ligoDV-web output: 
https://ldvw.ligo.caltech.edu/ldvw/view?act=getImg&imgId=78247
Notice the +9.99x10^2 in the top left corner. The integer is 1000, but it plots it as 1.0+9.99x10^2.

P.S. I think this also happens with time series that have a large DC offset, and small variation, but I do not have a code snippet to prove it. I mention that because I don't think fixing this only for integers is the thing to do.

**Comment by duncanmmacleod** [comment]
The above example can be reproduced on any machine as

```bash
gwpy-plot timeseries --chan 'H1:OMC-DCPD_B_GAIN' --start 1117831923 --duration 3 --interactive
```

with the offset 'feature'.

**Comment by duncanmmacleod** [comment]
Incidentally, for me, that plot comes up with a 2.9s duration, rather than the 3s request on the command line. @areeda: I presume this a separate bug?

**Comment by areeda** [comment]
I'm not sure it's a bug.  That channel is acquired at 16Hz so the last sample read is at 2.94s and gets printed at 2.9.

I guess it's a question of data limits vs requested time.  Or start of sample vs end of sample.

**Comment by duncanmmacleod** [comment]
IMHO, the timeseries plot should run to the end of the last sample, or similarly, the duration of the plot requested by the user.

**Comment by areeda** [comment]
I agree that is more obvious what's happening, although adjusting plots to the data makes it non trivial as we have discovered.

I'll look into it.

**Comment by duncanmmacleod** [comment]
the `TimeSeries` object you get back will have a `span` attribute that gives the enclosing GPS segment for the data: `[t_0, t_n+dt)`, you should be able to use that for the `xlim`, or the union of all such `span` segments when plotting multiple channels.

**Comment by areeda** [comment]
Thanks.  That will work when subsecond limits are not specified, in which case we can use what they asked for.

**Comment by duncanmmacleod** [comment]
Agreed, thanks @areeda.
