### ISSUE TITLE
Concatenating discontiguous TimeSeries segments smoothly.

### ISSUE THREAD

**Issue by rutujagurav** [gwpy/gwpy#1205]
I have a TimeSeriesList that I am trying to smoothly join. None of the TimeSeries in the TimeSeriesList are contiguous, so when I join them with gap argument, it raises a ValueError. 

I cannot use gap='ignore' because I get big concatenation artifacts in my resulting TimeSeries value. I cannot use gap='pad' because my discontiguous TimeSeries segments can be really far from each other and that blows up the size of my array. 
I would like to smoothly concatenate/join discontiguous TimeSeries in the TimeSeriesList. Or at least be able to pad with n random number like -
`sig = TimeSeriesList(*sigs).join(gap=np.random.uniform(10))`

Right now, this causes an error - 

```pytb
Traceback (most recent call last):
  File "plot-interactive.py", line 49, in <module>
    sig = TimeSeriesList(*sigs).join(gap=np.random.uniform(10))
  File "/usr/lib/python3.6/site-packages/gwpy/timeseries/core.py", line 1627, in join
    out.append(series, gap=gap, pad=pad)
  File "/usr/lib/python3.6/site-packages/gwpy/types/series.py", line 750, in append
    type(self).__name__, self.xspan, other.xspan))
ValueError: Cannot append discontiguous TimeSeries
    TimeSeries 1 span: [1164605507.3734741 ... 1164605508.40448)
    TimeSeries 2 span: [1164606042.3944702 ... 1164606043.425476)
```

**Comment by duncanmmacleod** [comment]
Hi @rutujagurav, sorry for the delaying in getting to this. I think you might just be using the wrong keyword argument, you should use `pad=<>` to specify what to pad with:

```python
TimeSeriesList(*sigs).join(pad=numpy.random.uniform(10))
```

However, I don't think that will totally solve your problem, as I'm not sure we (currently) support padding with arbitrary-sized arrays, only a single float will be used.

I think in this case the easiest solution would be to manually concatenate your data:

```python
data = sig[0].copy()
for sig in sigs[1:]:
    data.append(np.random.uniform(10))
    data.append(sig, gap='ignore')
```

Please let me know if something like that works for you.

**Comment by rutujagurav** [comment]
Thanks, that works.
