### ISSUE TITLE
IO/OS Error with TimeSeries.read()

### ISSUE THREAD

**Issue by adrianhelmlingcornell** [gwpy/gwpy#1216]
I have been trying to pull some O2 data with gwpy. Using Python 2.7.5/gwpy 1.0.1 and Python 3.6/gwpy 0.15.0 I get the following error when looking for PEM data around GW170817:

`TimeSeries.read('/archive/frames/O2/raw/H1/H-H1_R-11870/H-H1_R-1187008832-64.gwf', 'H1:PEM-CS_ACC_BEAMTUBE_MCTUBE_Y_DQ')`

>OSError                                   Traceback (most recent call last)
><ipython-input-5-4ff08a8204a0> in <module>
>----> 1 TimeSeries.read('/archive/frames/O2/raw/H1/H-H1_R-11870/H-H1_R-1187008832-64.gwf', 'H1:PEM-CS_ACC_BEAMTUBE_MCTUBE_Y_DQ')
>
>/cvmfs/ligo-containers.opensciencegrid.org/lscsoft/conda/latest/envs/ligo-py36/lib/python3.6/site-packages/gwpy/timeseries/core.py in read(cls, source, *args, **kwargs)
>    308         -----"""
>    309         from .io.core import read as timeseries_reader
>--> 310         return timeseries_reader(cls, source, *args, **kwargs)
>    311 
>    312     def write(self, target, *args, **kwargs):
>
>/cvmfs/ligo-containers.opensciencegrid.org/lscsoft/conda/latest/envs/ligo-py36/lib/python3.6/site-packages/gwpy/timeseries/io/core.py in read(cls, source, *args, **kwargs)
>     31     """
>     32     # if reading a cache, read it now and sieve
>---> 33     if io_cache.is_cache(source):
>     34         from .cache import preformat_cache
>     35         source = preformat_cache(source, *args[1:],
>
>/cvmfs/ligo-containers.opensciencegrid.org/lscsoft/conda/latest/envs/ligo-py36/lib/python3.6/site-packages/gwpy/io/cache.py in is_cache(cache)
>    279     if isinstance(cache, string_types + FILE_LIKE):
>    280         try:
>--> 281             return bool(len(read_cache(cache)))
>    282         except (TypeError, ValueError, UnicodeDecodeError, ImportError):
>    283             # failed to parse cache
>
>/cvmfs/ligo-containers.opensciencegrid.org/lscsoft/conda/latest/envs/ligo-py36/lib/python3.6/site-packages/gwpy/io/cache.py in read_cache(cachefile, coltype, sort, segment)
>    178     # open file
>    179     if not isinstance(cachefile, FILE_LIKE):
>--> 180         with open(file_path(cachefile), 'r') as fobj:
>    181             return read_cache(fobj, coltype=coltype, sort=sort,
>    182                               segment=segment)
>
>OSError: [Errno 116] Stale file handle: '/archive/frames/O2/raw/H1/H-H1_R-11870/H-H1_R-1187008832-64.gwf'

In Python 2.7.5, this is listed as an IOError, but the same problem occurs. Using the same line of code for the frame file located at `/hdfs/frames/O3/raw/H1/H-H1_R-12670/H-H1_R-1267092160-64.gwf`results in the code working as expected. Is there a problem with using read() on archived data?

Thanks,
Adrian Helmling-Cornell

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1216, please join us on gitlab to continue your contribution!
