### ISSUE TITLE
Using "Jet" colormap in spectrograms can mislead the eye

### ISSUE THREAD

**Issue by e-q** [gwpy/gwpy#122]
The current default colormap in matplotlib is "jet," which has the potential to mislead the eye into seeing features that the data may not contain. When we look at a colormap, we expect changes in lightness to be proportional to changes in the data, but this isn't the case in jet. This strikes me as especially important when looking for transients/glitches in our interferometer data. 

Because of this issue with jet, matplotlib itself is going to be changing their default colormap in v1.5, and they've put together a page with more detail about this issue, with examples of the new default: http://bids.github.io/colormap/

So, for users that upgrade themselves to matplotlib 1.5, this will automatically change. However, it may be advantageous to specify a more perceptually uniform colormap within the gwpy code for user who do not.

**Comment by duncanmmacleod** [comment]
Thanks for bringing this up @e-q. I was already planning to make some test images using the new viridis colour map, and if people like it, I'm open to changing the default. It will take some convincing to get it past some users more resistant to change.
