### ISSUE TITLE
Where can I find the cache file from TimeSeries.fetch_open_data()

### ISSUE THREAD

**Issue by WuShichao** [gwpy/gwpy#1227]
Where can I find the cache file from TimeSeries.fetch_open_data()

**Comment by duncanmmacleod** [comment]
Hi @WuShichao, `TimeSeries.fetch_open_data` uses the cache functionality from `astropy.utils`, you can see the documentation here:

http://docs.astropy.org/en/stable/utils/data.html

The short version is that the data will be cached under `~/.astropy/cache` unless you have configured astropy manually.

**Comment by WuShichao** [comment]
> 
> 
> Hi @WuShichao, `TimeSeries.fetch_open_data` uses the cache functionality from `astropy.utils`, you can see the documentation here:
> 
> http://docs.astropy.org/en/stable/utils/data.html
> 
> The short version is that the data will be cached under `~/.astropy/cache` unless you have configured astropy manually.

Thank you very much!
