### ISSUE TITLE
Change default PSD averaging method

### ISSUE THREAD

**Issue by alurban** [gwpy/gwpy#1228]
@duncanmmacleod, now that we require scipy version 1.2.0 or better, do we also want to change the default PSD averaging method from ‘mean’ (standard Welch averaging) to ‘median’?

**Progressive argument:** gwpy is intended for gravitational wave data analysis, and every existing ground-based interferometer has nonstationary noise with loud, transient glitches, which median averaging is very good at mitigating. We already recommend that users employ this method; after all, it was the motivation for requiring at least scipy-1.2.0. So it is the natural default to use if we adopt the philosophy that sensible defaults should make the code work out-of-the-box.

**Conservative argument:** the default has always been Welch averaging, it is both the simplest method available and the first one most people see when they learn about PSDs. It is also still the default used by scipy, so it is the natural default for gwpy to continue using if cross-package consistency is a higher priority.

Anyone who knows where I land politically will be entirely unsurprised to hear that I personally favor the progressive argument.

cc @tjma12, @dethodav, @areeda, and any others who may have strong feelings

**Comment by tdent** [comment]
Median is *quite* good at mitigating glitches .. as long as enough independent samples are used.

Does the standard median method include the median bias correction? 

In terms of implications, what standard results/products/plots would be affected by the change? And would any of them be affected 'for the worse'?

**Comment by duncanmmacleod** [comment]
> Does the standard median method include the median bias correction?

@tdent: yes, this was implemented in https://github.com/scipy/scipy/pull/8970

**Comment by alurban** [comment]
Salient points as ever @tdent, I know that all of the production services downstream of gwpy already use median averaging where appropriate (particularly the summary pages) as do many users, at least in LIGO DetChar. To be cautious and minimize adverse impact, we can raise a loud `UserWarning` signaling that the default behaviour will change in a future minor release.
