### ISSUE TITLE
Remove support for HACR triggers

### ISSUE THREAD

**Issue by duncanmmacleod** [gwpy/gwpy#1233]
I don't think the HACR trigger I/O was ever picked up by the GEO600 group, and if not, nobody is using it, so I would like to remove it, since there isn't a good way to test that it works properly with current GEO600 triggers.

@borjasor should comment here if the GEO600 group is actually using GWpy's HACR I/O interface.

**Comment by borjasor** [comment]
GEO Summary Pages does not use gwpy to get HACR triggers, but instead uses older code 'geoUtils'. Duncan has advised to use gwpy.HACR instead. A possible long-term solution is for the HACR code to be pulled out of gwpy into its own library that can be maintained independently of gwpy.

**Comment by Nikhil-Mukund** [comment]
@borjasor  Do you know how much of GEO Summary pages use geoUtils vs. gwpy? If it's mostly gwpy, then porting to HACR makes perfect sense keeping in mind the expected long term support.

**Comment by borjasor** [comment]
@Nikhil-Mukund , GEO Summary pages does not currently use gwpy at all. The only use of geoUtils on the summary pages is to interact with the HACR database and process that information accordingly. What it is proposed here is to make use of the newer code of gwpy.HACR respect to the older geoUtils and only for the interaction with the HACR glitches.

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1233, please join us on gitlab to continue your contribution!
