### ISSUE TITLE
Glue documentation broken 

### ISSUE THREAD

**Issue by GCArullo** [gwpy/gwpy#1241]
The gwf reading [documentation](https://gwpy.github.io/docs/v0.1/timeseries/gwf.html#reading-a-timeseries-from-gwf-files) has two broken links to the glue package: [1](https://computing.docs.ligo.org/daswgweb/projects/glue/doc/glue-module.html), [2](https://computing.docs.ligo.org/daswgweb/projects/glue/doc/glue.datafind-module.html)

**Comment by duncanmmacleod** [comment]
This was fixed a while ago.
