### ISSUE TITLE
Spectrogram computation takes much longer (possibly forever) on filtered timeseries

### ISSUE THREAD

**Issue by SeanDS** [gwpy/gwpy#1250]
I have a curious issue with a timeseries:

(Using IPython shell)
```bash
> from gwpy.timeseries import TimeSeries
> data = TimeSeries.read("mydata.hdf5")
> %timeit -n1 -r1 spec1 = data.spectrogram(10, 10, 5)
1min 46s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
> filtered_data = data.bandpass(0.5, 15)
> %timeit -n1 -r1 spec2 = filtered_data.spectrogram(10, 10, 5)
```

I waited 30 minutes and the last line was still running.

Is it expected that filtered data should take much longer for spectrogram computation? I'm not very familiar with the algorithm but I thought it took roughly the same time regardless of the data composition.

The data has 885 million points, 5 days of data sampled at 2048 Hz. The machine I'm running it on has loads of cores and memory, so that shouldn't be an issue (and I'd expect an out of memory error in the latter case).

**Comment by areeda** [comment]
Sean,
I can't speak to the magnitude of your job but I don't think the problem is as simple as filtered vs unfiltered. 

LDVW has had that feature for a while. Here's a 30min example https://ldvw.ligo.caltech.edu/ldvw/view?act=getImg&imgId=281993 (requires LVK credentials) took less than 20 sec including reading the data and web overhead.

**Comment by alurban** [comment]
@SeanDS, can you say more about the data you're reading (or point me to the data file, if it exists on an LDAS cluster)?

In trying to reproduce this issue with mock data, I was able to run spectrograms with only very minor (about 2 sec) difference in runtime.

```python
In [1]: import numpy

In [2]: from gwpy.timeseries import TimeSeries

In [3]: data = TimeSeries(numpy.random.normal(loc=1, scale=.5, size=884736000), sample_rate=2048)

In [4]: %timeit -n1 -r1 spec1 = data.spectrogram(10, 10, 5)
2min 16s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)

In [5]: filtered_data = data.bandpass(0.5, 15)

In [6]: %timeit -n1 -r1 spec2 = filtered_data.spectrogram(10, 10, 5)
2min 18s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
```

**Comment by SeanDS** [comment]
I can't recall exactly which data I was trying to analyse back in June, but trying those commands again with some data that could conceivably have been it, the times are almost the same. So, perhaps it was some weird memory problem on the machine I was using. Since it can't be reproduced I guess I'll just close this.

**Comment by SeanDS** [comment]
@alurban thanks for your help anyway!
