### ISSUE TITLE
Gwpy reading issues on win-10

### ISSUE THREAD

**Issue by LaBadda** [gwpy/gwpy#1251]
Hi!
I have installed gwpy using Anaconda on windows 10 and within python 3. Now I was trying to read a .gwf file. I had the following error:

no GWF API available, please install a third-party GWF library (framecpp, lalframe) and try again

So I tried to install the package python-ldas-tools-framecpp following: [this](https://github.com/gwpy/gwpy/issues/1084) But I had a PackagesNotFoundError. And then I have seen [here](https://anaconda.org/conda-forge/python-ldas-tools-framecpp/) that it doesn't seem to be possible to install it in windows.

Is it possible that I cannot read gwf files in windows or did I make some error (I bet this is the answer)? 
Could someone help me, please?

**Comment by duncanmmacleod** [comment]
Hi @LaBadda, thanks for your query. Right now, you can't use gwpy to read GWF files on Windows, however we are preparing gwpy-2.0.0, which _will_ support GWF reading on that platform. If you're happy to wait a week or so, we are close to being able to make that release.

**Comment by LaBadda** [comment]
yes! I can wait! Thank you very much for the info!

**Comment by duncanmmacleod** [comment]
@LaBadda, this should now work, if you install gwpy >=2.0.0 and python-framel:

```
conda install -c conda-forge "gwpy>=2.0.0" python-framel
```

Please let me know if you have any problems.

**Comment by LaBadda** [comment]
Wow, thank you! It works perfectly!!!  👍 :-D
