### ISSUE TITLE
Veto definer padding not correctly applied

### ISSUE THREAD

**Issue by dethodav** [gwpy/gwpy#1268]
When using `DataQualityDict.from_veto_definer_file()`, if a single flag in the veto definer file includes multiple definitions with different padding, the padding is applied differently depending on the time period queried.

If a time period covering multiple flag definitions is used when ingesting the veto definer, only the first padding definition is used for all segments when queried. 

This behavior should be resolved or a warning should be presented to let users know of this unexpected behavior. 
Here is a minimal code and file example which shows padding being applied in only one of the two cases. (Only works using LSC resources)

```
from gwpy.segments import Segment,SegmentList,DataQualityFlag,DataQualityDict
veto_definer = 'vdf_ex.xml'
start = 1164585617
end = 1164672017
mid = 1164670017
flags_cut = DataQualityDict.from_veto_definer_file(veto_definer,start=mid,end=end)
flags_cut.populate(segments=SegmentList([Segment(mid,end)]))
flags = DataQualityDict.from_veto_definer_file(veto_definer,start=start,end=end)
flags.populate(segments=SegmentList([Segment(mid,end)]))
print(flags_cut['H1:DMT-ANY_PI_HIGH_RMS:1'].active - flags['H1:DMT-ANY_PI_HIGH_RMS:1'].active)
```

```
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE LIGO_LW SYSTEM "http://ldas-sw.ligo.caltech.edu/doc/ligolwAPI/html/ligolw_dtd.txt">
<LIGO_LW>
	<Table Name="veto_definer:table">
		<Column Name="veto_definer:category" Type="int_4s"/>
		<Column Name="veto_definer:comment" Type="lstring"/>
		<Column Name="veto_definer:end_pad" Type="int_4s"/>
		<Column Name="veto_definer:end_time" Type="int_4s"/>
		<Column Name="veto_definer:ifo" Type="lstring"/>
		<Column Name="veto_definer:name" Type="lstring"/>
		<Column Name="veto_definer:process_id" Type="ilwd:char"/>
		<Column Name="veto_definer:start_pad" Type="int_4s"/>
		<Column Name="veto_definer:start_time" Type="int_4s"/>
		<Column Name="veto_definer:version" Type="int_4s"/>
		<Stream Delimiter="," Name="veto_definer:table" Type="Local">
			1,"High RMS in a PI mode",0,1164670017,"H1","DMT-ANY_PI_HIGH_RMS","process:process_id:1",0,1164585617,1,
			1,"High RMS in a PI mode",5,1164672017,"H1","DMT-ANY_PI_HIGH_RMS","process:process_id:2",-5,1164670017,1
		</Stream>
	</Table>
</LIGO_LW>
```

**Comment by duncanmmacleod** [comment]
Thanks @dethodav, I think I understand what is going on here, and will try and work around a fix. Thank you especially for the minimal XML example to use in testing.

**Comment by dethodav** [comment]
@duncanmmacleod Has there been progress on addressing this bug? This has popped up again as an issue for ongoing use of gwpy.

**Comment by duncanmmacleod** [comment]
Sorry @dethodav, I dropped the ball on this, but am looking at it now. Trying to manipulate the `DataQualityFlag` to handle variable padding is going to be a mess, but **today** you can get what you need by using a `Table` as the veto definer object, then manually populate each row as a flag as follows:

```python
from collections import namedtuple
from gwpy.segments import (DataQualityDict, DataQualityFlag)
from gwpy.table import Table

vetodefiner = Table.read('vdf.xml', tablename="veto_definer")
vetoes = DataQualityDict()

for row in vetodefiner:
    rowobj = namedtuple("Veto", row.colnames)(*row.values())
    flag = DataQualityFlag.from_veto_def(rowobj)
    key = str(flag)
    tmp = DataQualityDict()
    tmp[flag.name] = flag
    tmp.populate()
    vetoes += tmp
```

I appreciate that this is ugly as hell, but it works. I will post some updates to `gwpy.segments` to make this easier, and am toying with the idea of providing a `VetoDefinerTable` object with its own `populate` method that does this for you.

**Comment by camurria** [comment]
Hi, it's Agata. I'm trying to use this piece of code for the O3a release but I get the following error:

**AttributeError: 'Row' object has no attribute 'values'**

I did just copy and paste of your code using as vdf the cbc.xml and the burst.xml that you can find in our git: https://git.ligo.org/official-gwosc-projects/timeseries/-/tree/master/pipeline_losc/O3_Bulk_Data

The environment I am using is the one specific for gwosc described by this xml file: https://wiki.ligo.org/pub/LOSC/FAQ/gwosc_v2.yml (python version 3.6 and gwpy version 1.0.1)

I tried locally with an higher version of python (3.8) and gwpy (2.0.2) and for the same veto definer files and I get a different error:

  **File "/Users/agata/miniconda3/envs/tensorflow/lib/python3.8/site-packages/gwpy/segments/flag.py", line 654, in from_veto_def
    veto.end_time = +inf
AttributeError: can't set attribute**

**Comment by duncanmmacleod** [comment]
Ok, according to https://github.com/astropy/astropy/commit/6275bee6ff24c4db5eeb50802d21960083a74262 you should be able to use `Row.values()` with astropy >=4.1, are you able to upgrade on the remote?

**Comment by camurria** [comment]
I updated astropy on losc-data (sorry it took a bit to update all the related packages) but it got updated to the version 4.0.4, so I forced it to an update to the version 4.1 (with conda install). At this point I get the error I had locally:

    **flag = DataQualityFlag.from_veto_def(rowobj).populate()
  File "/home/agata.trovato/anaconda3/envs/gwosc/lib/python3.6/site-packages/gwpy/segments/flag.py", line 657, in from_veto_def
    veto.end_time = +inf
AttributeError: can't set attribute**

But at least one step is done :-)

**Comment by duncanmmacleod** [comment]
Ah, yes this likely needs an actual code patch. This is it (in case you can just apply it on-the-fly):

```patch
diff --git a/gwpy/segments/flag.py b/gwpy/segments/flag.py
index 1b32b814..bb040b49 100644
--- a/gwpy/segments/flag.py
+++ b/gwpy/segments/flag.py
@@ -650,9 +650,8 @@ class DataQualityFlag(object):
             name += ':%d' % int(veto.version)
         except TypeError:
             pass
-        if veto.end_time == 0:
-            veto.end_time = +inf
-        known = Segment(veto.start_time, veto.end_time)
+        end_time = veto.end_time or +inf
+        known = Segment(veto.start_time, end_time)
         pad = (veto.start_pad, veto.end_pad)
         return cls(name=name, known=[known], category=veto.category,
                    description=veto.comment, padding=pad)
```

**Comment by camurria** [comment]
It seems it works in this way!!! Thanks!

**Comment by duncanmmacleod** [comment]
@camurria, what versions of `python-ligo-lw` and `lscsoft-glue` do you have in that environment?

**Comment by camurria** [comment]
ok

**Comment by dethodav** [comment]
@duncanmmacleod What is the indented behavior for this line in the case where there are multiple rows in the veto definer with the same flag name?
```
    vetoes += {flag.name: flag}
```

Should this line be combining segments from all rows with the same name, or adding another seperate entry to the data quality dict?

**Comment by duncanmmacleod** [comment]
That line should store the union of segments with the same flag name.

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1268, please join us on gitlab to continue your contribution!
