### ISSUE TITLE
Example for making and writing a LIGOLw XML table

### ISSUE THREAD

**Issue by andrew-lundgren** [gwpy/gwpy#127]
There's currently no example for how to create a new XML table (like a SnglBurstTable), add rows to it, and write it. There are a few steps where it's not obvious (how to create a new row, and how to create the table with New so it supports writing).

**Comment by duncanmmacleod** [comment]
@andrew-lundgren, now that GWpy supports only the `EventTable` (subclass of `astropy.table.Table`) and not the `glue.ligolw` objects directly, can this issue be closed? Detailed examples of how to create and write are linked from the [`EventTable` docs](https://gwpy.github.io/docs/stable/table/).
