### ISSUE TITLE
Getting Error While Fetching Data using flag dq.query_str from module pycbc

### ISSUE THREAD

**Issue by tanazza** [gwpy/gwpy#1271]
@duncanmmacleod As you have helped me previously and I do not know who else to write for this error. I am getting following error while running the flag mentioned in the subject line.

RuntimeError: Could not find a RFC 3820 compliant proxy credential. Please run 'grid-proxy-init -rfc' and try again. 

As much as I know, you suggested me to run "kinit username@LIGO-ORG" to check for my credentials. It comes out error free.

However, as mentioned in the error, I tried to run 'grid-proxy-init -rfc' which gives me following error:  Error: Couldn't find valid credentials to generate a proxy.
Use -debug for further information.

I will appreciate any help. Thanks,
Tanazza

**Comment by duncanmmacleod** [comment]
Hi @tanazza, since this is a pycbc issue (according) to the subject line, you should report directly on the [PyCBC issue tracker](https://github.com/gwastro/pycbc/issues/). 

The short version is that you need to generate a LIGO.ORG X.509 credential to query the segment database.
