### ISSUE TITLE
DataQualityDict plot method not labelling correctly

### ISSUE THREAD

**Issue by AlexisMV** [gwpy/gwpy#1274]
Hi all

I have been doing some plots of segments using the DataQualityDict class and found that the labels in the y-axis are usually not correct. I made a small example where you can see this:

```
import numpy as np
import gwpy.segments
import matplotlib.pyplot as plt
from gwpy.plot import Plot

Seg=gwpy.segments.DataQualityDict()

a = gwpy.segments.DataQualityFlag(known=[(0, 5), (10, 15)], active=[(1, 5), (10, 12)])
b = gwpy.segments.DataQualityFlag(known=[(0, 12)], active=[(3, 7), (10, 12)])
c = gwpy.segments.DataQualityFlag(known=[(8, 16)], active=[(1,5),(14,15)])

Seg['a']=a
Seg['b']=b
Seg['c']=c

Seg.plot(label='Name_Random')

plt.show()
```
In the documentation it says that by using a value of label different than 'key' or 'name' it should write the same 'y' label in all of them but as far as I have seen it doesn't. Neither using 'key' writes the key correctly in all of them. I believe that the problem is in https://github.com/gwpy/gwpy/blob/109b8ce5ac97db39438f86ce779a7b79a121b752/gwpy/segments/flag.py#L1831 For each segment you have two different collections, the red squares and the green squares, so by iterating over them to assign the labels you first assign a label to the green and in the next iteration to the red so, at the end, the figures are not correctly labelled.

I managed to bypass this problem by taking only the even values of the artists list but I am not sure if that is the real problem or the proper solution.

(Same in python 3.6+)
```
Python 2.7.5
>>> gwpy.__version__
u'1.0.1'
>>> import numpy, scipy, astropy
>>> numpy.__version__
'1.16.6'
>>> scipy.__version__
'1.2.3'
>>> astropy.__version__
u'2.0.16'
```
Regards
Alexis

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1274, please join us on gitlab to continue your contribution!
