### ISSUE TITLE
Matplotlib colormaps have deprecated behavior

### ISSUE THREAD

**Issue by alurban** [gwpy/gwpy#1289]
In downstream service software (particularly `gwsumm` and `gwdetchar.omega`) I am seeing the following warnings:

```
/path/to/lib/python3.8/site-packages/gwpy/plot/plot.py:395: MatplotlibDeprecationWarning: The 'cmap' parameter to Colorbar has no effect because it is overridden by the mappable; it is deprecated since 3.3 and will be removed two minor releases later.
    cbar = super().colorbar(mappable, **kwargs)
```

Matplotlib's [release notes](https://matplotlib.org/3.3.0/api/prev_api_changes/api_changes_3.3.0/deprecations.html#effectless-parameters-of-figure-colorbar-and-matplotlib-colorbar-colorbar) are somewhat confusing on the matter of how to address this, but AFAICT it appears we have to set the colormap from the mappable directly, something like:

```python
mappable.set_cmap(cmap)
cbar = ax.colorbar(mappable, **kwargs)
```

**Comment by duncanmmacleod** [comment]
@alurban, thanks for acting on this - I had seen the warning, and ignored it until now. I have a hunch (untested) that the only change required is this:

```diff
diff --git a/gwpy/plot/colorbar.py b/gwpy/plot/colorbar.py
index f12f09f5..db8b6411 100644
--- a/gwpy/plot/colorbar.py
+++ b/gwpy/plot/colorbar.py
@@ -59,7 +59,7 @@ def process_colorbar_kwargs(figure, mappable=None, ax=None, use_axesgrid=True,

     norm, kwargs = format_norm(kwargs, mappable.norm)
     mappable.set_norm(norm)
-    mappable.set_cmap(kwargs.setdefault('cmap', mappable.get_cmap()))
+    mappable.set_cmap(kwargs.pop('cmap', mappable.get_cmap()))

     # -- set tick formatting
```

We are already setting the `cmap` for the mappable, but are duplicating that for the `colorbar()` func, which we apparently shouldn't do anymore.

**Comment by alurban** [comment]
@duncanmmacleod, thanks for this suggestion, I've opened #1290 to try this out. Running unit tests on my laptop is encouraging, we'll have to see how the full build tests shake out.
