### ISSUE TITLE
inspiral_range should use cosmologically-corrected ranges

### ISSUE THREAD

**Issue by jrollins** [gwpy/gwpy#1292]
It looks like the inspiral_range function will now be using the [inspiral_range package](https://git.ligo.org/gwinc/inspiral-range) to calculate ranges, which is good.  However, it looks like it's still just calculating the "sensemon" range, which is inaccurate at cosmological distances.  It would be good if by default it used the cosmologically-corrected [range](https://git.ligo.org/gwinc/inspiral-range/-/blob/master/inspiral_range/inspiral_range.py#L205) function, or at least make the other functions available to users so they're not limited to just the sensemon range.

Another possibility would be to deprecate the gwpy.astro.inspiral_range package and to just point users to the external inspiral_range package, which may in some way be cleaner and less confusing.  At the very least this package should be referenced for people looking for a more accurate range estimate.

**Comment by duncanmmacleod** [comment]
I believe this will be resolved by #1248.

**Comment by jrollins** [comment]
@duncanmmacleod That is the PR I was referring to.  But it looks like it will be replacing the existing sensemon range calculation with the one from the inspiral_range package.  It's the sensemon_range calculation itself that I think should be deprecated, or at least the cosmologically-corrected ranges should be offered (or just advertise the inspiral_range package itself).

**Comment by duncanmmacleod** [comment]
Ah right, I understand now. @alurban, are you able to include the modification to use the cosmologically-corrected range function in your PR?

Maybe include a wrapper around `sensemon_range` for users who prefer it (for whatever reason)?

**Comment by duncanmmacleod** [comment]
@jrollins, we probably can't just tell people to use the `inspiral_range` functions directly because we want to munge the input and output into `gwpy` objects. But the wrappers should be very light and all of the docstrings and documentation pages should defer credit to the `inspiral_range` package.

**Comment by jrollins** [comment]
I'm not worried about credit, just flexibility and not having to duplicate too much code.  A light wrapper around inspiral_range sounds reasonable, something that gives as much access as possible to all the functionality of that library.  Or maybe there are modifications to the inspiral_range that could make it more interoperable with gwpy without having to maintain a whole interoperability module in gwpy...

**Comment by alurban** [comment]
@duncanmmacleod / @jrollins, I'm happy to include the cosmologically-corrected range function, my question is about how. For example, downstream consumers of the (network [1]) summary pages are used to seeing a representation of the SenseMon range based on median-averaged spectrograms, which comes from the gwpy function. I would argue that even if that display changes to include redshift corrections, the old functionality should be conserved for backwards compatibility.

I think there is a straightforward compromise, though. I can include a redshift argument that defaults to `None` (or `0` or similar), which uses the SenseMon range under the default use case, but would call the redshift-corrected function if this argument is nonzero. Is that agreeable?

[1] The IFO-specific summary pages display the _actual_ SenseMon range, i.e. the one computed by the DMT, which uses Welch-averaged spectrograms.

**Comment by jrollins** [comment]
@alurban imho sensemon should just be deprecated unless there is a need for a very fast imprecise estimation of the range.  But I honestly don't know of where that would be necessary.  the inspiral_range package can calculate the cosmologically-corrected ranges fast enough for any use case I can imagine.

**Comment by alurban** [comment]
@jrollins, we need the `gwpy.astro` module regardless, because we maintain a burst range calculator whose functionality isn't replaced by other packages (as far as I know). So to my mind the cleanest division of labor is to keep the functions we have, but make them light wrappers around `inspiral_range`, which is what #1284 tries to accomplish.

**Comment by jrollins** [comment]
the burst range calculation could be incorporated into the inspiral_range package...?
