### ISSUE TITLE
Segmentation fault on Mac OS 11

### ISSUE THREAD

**Issue by jkanner** [gwpy/gwpy#1299]
I'm having trouble getting gwpy to run on my mac since updating the OS to Big Sur (Version 11.2).

I've installed gwpy into a conda enviornment with pip, and I get segmentation faults immediately on importing gwpy.  Probably due to a mistake I'm making, but I've got no idea how to debug this.  

Python 3.8.6 | packaged by conda-forge | (default, Jan 25 2021, 23:22:12) 
[Clang 11.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gwpy
Segmentation fault: 11

**Comment by duncanmmacleod** [comment]
What `numpy` version do you have installed? If it's `1.20.0` then that is known to cause issues with LAL, please downgrade to `1.19.x`. If it's something else, please post the output of `conda list` and/or `pip list installed`.

**Comment by jkanner** [comment]
Thank you!  I will try this.  -jonah

On Feb 5, 2021, at 10:50 AM, Duncan Macleod <notifications@github.com<mailto:notifications@github.com>> wrote:



What numpy version do you have installed? If it's 1.20.0 then that is known to cause issues with LAL, please downgrade to 1.19.x. If it's something else, please post the output of conda list and/or pip list installed.

**Comment by jkanner** [comment]
Yep, that resolved the issue.  Thanks, Duncan!
