### ISSUE TITLE
Reading the data of state vector with unit "state" by parallel processing makes error

### ISSUE THREAD

**Issue by yuzuri** [gwpy/gwpy#1300]
Hi,

Thank you for continuous development of useful package!
I got the following error. 

## Environment
- OS : Debian 9
- conda : 4.9.1
- python : 3.7
- gwpy 1.0
- on cgi-bin

## on cgi-bin
When I read the state vector, whose unit is set as `state`, by parallel processing (nproc=4), I got the following the error.

```
ValueError: StateVector units do not match: state vs state. 
      args = ('StateVector units do not match: state vs state.',) 
      with_traceback = <built-in method with_traceback of ValueError object>
```

Initially I thought that we can avoid this error by reading the state vector as `TimeSeries` and convert to `StateVector`. But, it failed.

If I remove the option of parallel processing (nproc=4), it works well. Do you know the other solution to read the state vector with unit `state` by parallel processing?
I guess the combination of `nproc` and unregistered unit makes this problem.

## on python shell

Note that when I do same things on `python` shell, I got the following warning and no error.

```
>>> from gwpy.timeseries import StateVector
>>> a = StateVector.read('V1.cache', 'V1:DQ_ANALYSIS_STATE_VECTOR', start=1261641918, end=1261642998, nproc=4)
WARNING: UnitsWarning: state is not a valid unit. Did you mean statA or statC? Mathematical operations using this unit should work, but conversions to oth
units will not. [gwpy.detector.units]
>>> a.unit
Unit("state")
```

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1300, please join us on gitlab to continue your contribution!
