### ISSUE TITLE
Importing `gwpy` messes up `matplotlib` plot settings

### ISSUE THREAD

**Issue by francois-rozet** [gwpy/gwpy#1335]
Even though I only use a single module of `gwpy`, unrelated to plots, importing it completely messes up the settings of my `matplotlib` plots. For instance,

```python
>>> import matplotlib.pyplot as plt
>>> plt.rcParams['axes.axisbelow'] = True
>>> from gwpy.timeseries import TimeSeries
>>> print(plt.rcParams['axes.axisbelow'])
False
```

In my opinion, `gwpy` should not modify these settings globaly, or at least only if `gwpy.plot` is actually used. 
A solution is to import `gw.plot` **within** the functions that require it. This would **not** increase the running time, because imports are only executed the first time by the interpreter.

Another solution is to encapsulate the modifications in a function (*e.g.* `gw.plot.set_rc_params()`) and let the user the option to do the call if needed.

**Comment by duncanmmacleod** [comment]
@francois-rozet, I'm sorry that this is inconvenient for you, my preference is to keep the customisation on by default. However, you can opt-out of the customisation from the environment by setting the `GWPY_RCPARAMS` environment variable to something 'falsey', e.g.

```bash
export GWPY_RCPARAMS=false
```

Ref: [_Configuring GWpy from the environment_](https://gwpy.github.io/docs/stable/env.html)

Please confirm that this works for you, then close the ticket if you're happy.

**Comment by francois-rozet** [comment]
Thanks @duncanmmacleod, it works like a charm!

> P.S. I searched the documentation prior to writing this issue, but it didn't occurred to me that "Configuring GWpy from the environment" would be the solution 😅

**Comment by duncanmmacleod** [comment]
> P.S. I searched the documentation prior to writing this issue, but I didn't think that "Configuring GWpy from the environment" would be the solution 😅

Yes, it took me a while to find it as well, and I wrote it! I'll think about how to make that easier to discover.
