### ISSUE TITLE
GWpy bandpass filter

### ISSUE THREAD

**Issue by westinhuang** [gwpy/gwpy#1336]
I design a simple bandpass filter. The center of frequency is 79.7 Hz. The detail code is following,

```
from gwpy.signal.filter_design import bandpass
bp = bandpass(79.6,79.8,4096.)
from gwpy.plot import BodePlot
plot = BodePlot(bp,sample_rate=4096.)
plot.show()
```
The question is according the bandpass filter, the center of frequency, 79.7 Hz should be located in 0 degree in Bodeplot.
But from the fig.1, the center of frequency, 79.7 Hz isn't in 0 degree in Bodeplot. 
<img width="551" alt="attachment_1" src="https://user-images.githubusercontent.com/47237624/118847725-a12ab000-b900-11eb-9573-57aaaf5f38c1.png">

Do anyone know how to fix this or where does this come from ?

Another question is bandpass's filter parameter " gpass" seems it doesn't work well to suppression at corner frequencies (79.6 and 79.8Hz) compare to fig.2(gpass=2) and fig.3(gpass=25) 
<img width="549" alt="attachment_2" src="https://user-images.githubusercontent.com/47237624/118847760-adaf0880-b900-11eb-9caf-28677744a05d.png">
<img width="563" alt="attachment_3" src="https://user-images.githubusercontent.com/47237624/118847769-aee03580-b900-11eb-8160-29faf70ace7d.png">
```
from gwpy.signal.filter_design import bandpass
bp = bandpass(79.6,79.8,4096., gpass=25)
from gwpy.plot import BodePlot
plot = BodePlot(bp,sample_rate=4096.)
plot.show()
```
Do anyone know how to fix this?

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1336, please join us on gitlab to continue your contribution!
