### ISSUE TITLE
DataQualityFlag.query_dqsegdb Should try internal connection to DB before X509 Auth

### ISSUE THREAD

**Issue by rpfisher** [gwpy/gwpy#1337]
While working at CIT in gwpy, the DataQualityFlag.query_dqsegdb function will fail if there is not a ligo-proxy-init command previously run on the command line, asking for credentials.  This particularly happens when using gwpy through JupiterLab.  The dqsegdb should allow an internal connection from within CIT that will not require this.  This may require tag-teaming with Robert Bruntz.

**Comment by robertbruntz** [comment]
I talked to @rpfisher and confirmed: the desired behavior is that the the DataQualityFlag.query_dqsegdb function should check if it is on a CIT-network machine, and if so, use the internal network over http, which does not require authentication (and thus the function should not check for or try to use any authentication).  If it is not running on a CIT-network machine, then it should fall back to X509 authentication over https.  Note that LHO and LLO clusters, etc., are not part of the CIT network, and thus they do require X509 over https.

**Comment by duncanmmacleod** [comment]
The `gwpy.segments.flag` just calls out to `dqsegdb2.query`, which decides upon the authentication (or not), however the key piece of information is the `url` argument being passed to `DataqualityFlag.query_dqsegdb`. The default for that is as follows (https://github.com/gwpy/gwpy/blob/v2.0.4/gwpy/segments/flag.py#L67-L68):

```python
DEFAULT_SEGMENT_SERVER = os.getenv('DEFAULT_SEGMENT_SERVER',
                                   'https://segments.ligo.org')
```

So, if you want to bypass the authentication, you should pass the local IP of the segdb host as an `http` URL (not `https`). However, the `DEFAULT_SEGMENT_SERVER` should be being set by the login profile for all users at CIT:

```console
$ grep DEFAULT_SEGMENT_SERVER= /etc/profile.d/*
/etc/profile.d/ligo.sh:                DEFAULT_SEGMENT_SERVER=http://segments.ldas.cit
```

so you should automatically be querying over the local network only.

However however, if I log in to jupyter.ligo.caltech.edu, I don't see that variable set in my python session. All told, I suspect this is a jupyter configuration issue, please [open a helpdesk ticket](https://git.ligo.org/computing/helpdesk/-/issues/new?issuable_template=Jupyterhub) to resolve that.

**Comment by duncanmmacleod** [comment]
Ping @robertbruntz @rpfisher.
