### ISSUE TITLE
SnglBurstTable.read needs format argument

### ISSUE THREAD

**Issue by lauranuttall** [gwpy/gwpy#135]
The following example will no longer work:

https://gwpy.github.io/docs/stable/examples/table/scatter.html

You need to put a format argument in the SnglBurstTable.read function otherwise you with get an error complaining about the ending of the file, i.e.:

```python
events = SnglBurstTable.read('../../gwpy/tests/data/H1-LDAS_STRAIN-968654552-10.xml.gz', format='ligolw')
```

**Comment by duncanmmacleod** [comment]
@lauranuttall: I can run the above line with and without the format argument and both run just fine, using the latest installation on the LDAS `gwpysoft` virtualenv. I can also run the linked example end-to-end without any problems.

Which version of GWpy are you using, and on which machine? Can you also post the full traceback of the command that failed?

**Comment by lauranuttall** [comment]
Ok sorry bad example. I have found the example works because it is reading one xml file. When you try and read multiple xml files from a cache file (or from globbing many) the above example will stop working. 

I am always using the detchar install on LLO/LHO

**Comment by duncanmmacleod** [comment]
@lauranuttall, is this still a problem for you?

**Comment by lauranuttall** [comment]
If I remember the issue I think I have to put a format when you read in a xml file now, like 'ligolw' which is fine

**Comment by duncanmmacleod** [comment]
can you provide a way to reproduce the bug?

**Comment by lauranuttall** [comment]
does the example on:

https://gwpy.github.io/docs/stable/examples/table/scatter.html

still not work?

**Comment by duncanmmacleod** [comment]
it works just fine for me.

**Comment by duncanmmacleod** [comment]
@lauranuttall, can you confirm this is an issue for you? If so, please post a code snippet to reproduce.
