### ISSUE TITLE
Add smoothing to the list of methods in TimeSeries.

### ISSUE THREAD

**Issue by guillermo-valdes** [gwpy/gwpy#1359]
Is it possible to add smoothing (a running average) to the list of methods in gwpy's [TimeSeries](https://gwpy.github.io/docs/stable/api/gwpy.timeseries.TimeSeries.html)?
Something similar to [rolling.mean()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.window.rolling.Rolling.mean.html) in pandas.

We think [LASSO's](https://ldas-jobs.ligo-la.caltech.edu/~detchar/summary/day/20200106/detchar/lasso/) results (in its current version) will improve when using the smooth version of the TimeSeries.

Thanks.

**Comment by duncanmmacleod** [comment]
@guillermo-valdes, sorry it has taken more than a year to respond. Is this still a feature you're interested in. If so, I encourage you to have a go at implementing it yourself, I would be happy to help guide you.

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1359, please join us on gitlab to continue your contribution!
