### ISSUE TITLE
Modify documentation code snippets' syntax highlighting for better visibility?

### ISSUE THREAD

**Issue by Yash-10** [gwpy/gwpy#1364]
Hello, first of all, thank you for this project!

It seems that code blocks throughout the documentation become too light in color at some points. For example, as seen below:

![Screenshot from 2021-07-03 20-16-10](https://user-images.githubusercontent.com/68844397/124357994-d6365c00-dc3b-11eb-98d1-73d6098025c6.png)

I wondered if there would be a choice to modify the syntax highlighting for better readability of code snippets?

Also, this issue didn't seem to be in the `stable` docs

Thanks!

**Comment by duncanmmacleod** [comment]
The syntax highlighting issue is a misconfiguration of the custom CSS used in the docs. The online documentation needs a major overhaul that I don't have time for right now, unfortunately.

**Comment by duncanmmacleod** [comment]
This was corrected by 9e9b1a888c51eff0aa68ecc62c85abe7897cb8b7.
