### ISSUE TITLE
Add "TransferFunctionGram" to TimeSeries Class

### ISSUE THREAD

**Issue by jeffrey-kissel** [gwpy/gwpy#1413]
A year or so ago Alex added the coherence and the coherencegrams to the timeseries class in support of plots made for the  summary pages. These are sweet! Evan just recently submitted a pull request to add a basic transfer function (https://github.com/gwpy/gwpy/pull/1406) that I hope gets approved soon. But -- these leaves an obvious extension to be added -- the TransferFunctionGram. 

Let's add it!

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1413, please join us on gitlab to continue your contribution!
