### ISSUE TITLE
whitening method default looks like it is not median

### ISSUE THREAD

**Issue by VasSkliris** [gwpy/gwpy#1429]
Hi, so I recently noted that I was getting triggers when a glitch was inside the PSD interval I was using to whiten my noise segments, without analysing the glitch time itself. The TimeSeries.whiten method has the method options: bartlett', 'weltch' and 'median', with the default being 'median'. I noticed that in practice the default is 'weltch'.

## Example

So here is the timeseries `t`: 16 second of white noise with a 10Hz glitch at the beginning.

![image_16s](https://user-images.githubusercontent.com/22641206/140301852-6c0e1e0f-e952-4c68-9ef2-67f1901d4cae.png)

Then I apply whitening on it with three different methods:
```python
w_mean=t.whiten(4,2,method='welch')
w_median=t.whiten(4,2,method='median')
w_default=t.whiten(4,2)
```
and their plots respectively: 

![w_mean](https://user-images.githubusercontent.com/22641206/140302537-e3d67256-6128-4860-b081-40b6ce54252f.png)

![w_median](https://user-images.githubusercontent.com/22641206/140302632-5dc27cbc-2524-41fe-86d4-29a7664903dc.png)

![w_default](https://user-images.githubusercontent.com/22641206/140302812-f37afe7f-87f3-4f12-8d88-e789357181a7.png)

As you can see the default whitening method is the same with the 'welch'

**Comment by duncanmmacleod** [comment]
@VasSkliris, what version of GWpy are you using to generate this issue?

**Comment by VasSkliris** [comment]
@duncanmmacleod  it was <=2.0.2. I realised that in the latest version the default has changed to median and I hadn't updated the version. For people that use ML algorithms this change can have very serious implications (training vs testing). I suggest to note it as an important change if is there is such a thing.
