### ISSUE TITLE
Problem to check and save the GWdata in binary format

### ISSUE THREAD

**Issue by linlupin** [gwpy/gwpy#1464]
Dear Duncan,
 
Sorry to spend you some more time on my questions about the binary format of GW data.
You have replied my E-mail about how to read the frame or channel name of a ".hdf5" file.
I tried both "h5ls" and "h5dump" commands, however, I cannot find out the channel name of the hdf5 file downloaded from GWOSC.
It seems that I may misunderstand the contents of binary format in gwf and hdf5.
Only gwf file has the channel name to correspond the strain.
But if the above description is correct, then I cannot understand why we need to read the data as the following code:
(based on https://gwpy.github.io/docs/stable/timeseries/io/)
`data = TimeSeries.read('HLV-HW100916-968654552-1.hdf', 'L1:LDAS-STRAIN')`
What does "L1:LDAS-STRAIN" mention? I originally thought it as the channel name.

I need the function to append the data because I am generating a great data base for deep learning.
In order to save the time and memory in data generation, I do not want to transfer all the time series to one file at the same time. 
Therefore, the hdf5 format may satisfy my purpose since it can write a TimeSeries to an existing file, using `append=True`. 
(ref.  https://gwpy.github.io/docs/stable/timeseries/io/)
However, I met a problem to create an hdf5 file using my code (Tohdf5.py) following the usage described in the document of gwpy (https://gwpy.github.io/docs/stable/timeseries/io/).
(The way to run Tohaf5.py: python Tohdf5.py -f GWBNS.dat -s 4096 -d 8 -ch strain )
The error message is "TypeError: write() missing 1 required positional argument: 'target'.
Do you have any better idea to revise the code "Tohdf5.py"?
It seems that the error is due to the usage to write the data in hdf5 format.

Can you provide some hints to solve my question?

[code.zip](https://github.com/gwpy/gwpy/files/7814806/code.zip)

**Comment by duncanmmacleod** [comment]
> Sorry to spend you some more time on my questions about the binary format of GW data. You have replied my E-mail about how to read the frame or channel name of a ".hdf5" file. I tried both "h5ls" and "h5dump" commands, however, I cannot find out the channel name of the hdf5 file downloaded from GWOSC. It seems that I may misunderstand the contents of binary format in gwf and hdf5. Only gwf file has the channel name to correspond the strain. But if the above description is correct, then I cannot understand why we need to read the data as the following code: (based on https://gwpy.github.io/docs/stable/timeseries/io/) `data = TimeSeries.read('HLV-HW100916-968654552-1.hdf', 'L1:LDAS-STRAIN')` What does "L1:LDAS-STRAIN" mention? I originally thought it as the channel name.

Yes, in GWF files the `L1:LDAS-STRAIN` identifier is the name of the channel. However, GWOSC stores data in HDF5 files in a custom format, as documented at https://gwpy.github.io/docs/stable/timeseries/io/#hdf5-gwosc.

The `HLV-HW100916-968654552-1.hdf` example file **is not a GWOSC-format HDF5 data file** and uses a different schema, so is not a good example file for this use case.

> 
> I need the function to append the data because I am generating a great data base for deep learning. In order to save the time and memory in data generation, I do not want to transfer all the time series to one file at the same time. Therefore, the hdf5 format may satisfy my purpose since it can write a TimeSeries to an existing file, using `append=True`. (ref. https://gwpy.github.io/docs/stable/timeseries/io/) However, I met a problem to create an hdf5 file using my code (Tohdf5.py) following the usage described in the document of gwpy (https://gwpy.github.io/docs/stable/timeseries/io/). (The way to run Tohaf5.py: python Tohdf5.py -f GWBNS.dat -s 4096 -d 8 -ch strain ) The error message is "TypeError: write() missing 1 required positional argument: 'target'. Do you have any better idea to revise the code "Tohdf5.py"? It seems that the error is due to the usage to write the data in hdf5 format.
> 
> Can you provide some hints to solve my question?
> 
> [code.zip](https://github.com/gwpy/gwpy/files/7814806/code.zip)

Your code can be simplified by using GWpy's capability to read ASCII Files as `TimeSeries`:

```python
from gwpy.timeseries import TimeSeries
data = TimeSeries.read('GWBNS.dat', format='txt')
data.write('abc.hdf5', path='strain')
```

In the above code, `path='strain'` is required because your `TimeSeries` object doesn't have a populated `name` attribute; this denotes the path inside the new HDF5 at which to store the data.

In the case of reading multiple files and writing to a single file, you should just pass `append=True` and make sure that each `.write()` call is given a unique `path` value.

Please let me know if that works for you.

**Comment by duncanmmacleod** [comment]
Regarding the above code, there is currently a bug reported as #1473 that might cause you issues, I should have that merged and a fixed version released soon.

**Comment by linlupin** [comment]
Dear Duncan,

Thanks for you to clarify my questions about the hdf5 format.
For the purpose of deep learning, I am now trying to generate the data with long time or to combine more data sets.
For example, we would like to combine the data of d.hdf5 and dd.hdf5 (or append the contents of dd.hdf5 to d.hdf5, please refer to data.zip).
[data.zip](https://github.com/gwpy/gwpy/files/7861162/data.zip)
Following the usage provided in the document (https://gwpy.github.io/docs/stable/timeseries/io/#hdf5-gwosc.) and your previous response, I wrote the following code:
`rr=TimeSeries.read("dd.hdf5")
 rr.write("d.hdf5",path="strain",append=True,overwrite=True)
 rr=TimeSeries.read("d.hdf5")
 print(rr)`
However, I found that the contents of d.hdf5 will be totally replaced by dd.hdf5.
But my original purpose is to include the contents/information of dd.hdf5 in d.hdf5.
It means that the length/size of d.hdf5 is expected to be double after running the code.
If I did not include `overwrite=True` in the above code, then I will obtain the following error message:

> File "/Users/rickychang/odw-2021/test/test1.py", line 26, in <module>
>     rr.write("d.hdf5",path="strain",append=True)
>   File "/Users/rickychang/miniconda3/envs/igwn-py38/lib/python3.8/site-packages/gwpy/timeseries/core.py", line 327, in write
>     return io_registry.write(self, target, *args, **kwargs)
>   File "/Users/rickychang/miniconda3/envs/igwn-py38/lib/python3.8/site-packages/astropy/io/registry.py", line 566, in write
>     writer(data, *args, **kwargs)
>   File "/Users/rickychang/miniconda3/envs/igwn-py38/lib/python3.8/site-packages/gwpy/types/io/hdf5.py", line 232, in write_hdf5_series
>     return write_hdf5_array(series, output, path=path, attrs=attrs, **kwargs)
>   File "/Users/rickychang/miniconda3/envs/igwn-py38/lib/python3.8/site-packages/gwpy/io/hdf5.py", line 126, in decorated_func
>     return func(obj, h5f, *args, **kwargs)
>   File "/Users/rickychang/miniconda3/envs/igwn-py38/lib/python3.8/site-packages/gwpy/types/io/hdf5.py", line 185, in write_hdf5_array
>     dset = io_hdf5.create_dataset(h5g, path, overwrite=overwrite,
>   File "/Users/rickychang/miniconda3/envs/igwn-py38/lib/python3.8/site-packages/gwpy/io/hdf5.py", line 162, in create_dataset
>     return parent.create_dataset(path, **kwargs)
>   File "/Users/rickychang/miniconda3/envs/igwn-py38/lib/python3.8/site-packages/h5py/_hl/group.py", line 139, in create_dataset
>     self[name] = dset
>   File "/Users/rickychang/miniconda3/envs/igwn-py38/lib/python3.8/site-packages/h5py/_hl/group.py", line 373, in __setitem__
>     h5o.link(obj.id, self.id, name, lcpl=lcpl, lapl=self._lapl)
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "h5py/h5o.pyx", line 202, in h5py.h5o.link
> OSError: Unable to create link (name already exists)

Do I misunderstand any usage in appending the data provided in https://gwpy.github.io/docs/stable/timeseries/io/#hdf5-gwosc?

**Comment by linlupin** [comment]
I just found that I can append the data with the following usage:
`data1=TimeSeries.read("d.hdf5")`
`data2=TimeSeries.read("dd.hdf5")`
`data1.append(data2)`

Such an usage is different from the descriptions put in the document (https://gwpy.github.io/docs/stable/timeseries/io/#hdf5-gwosc), is it really the correct usage?

**Comment by duncanmmacleod** [comment]
@linlupin, I think I misunderstood your goal. 

I originally thought you wanted to read independent `TimeSeries` objects from different files, and just store them side-by-side in a new file.

Are you actually trying to concatenate all of these `TimeSeries` objects into a single TimeSeries, and then save that one object to a new file? If so then your usage of `TimeSeries.append` is correct.

**Comment by linlupin** [comment]
Dear Duncan,

Thanks for your confirmation.
AS you mentioned, if I would to read independent `TimeSeries` objects from different files and save them into a single new file. How can I deal with it?
Without including `overwrite=True`, I will obtain the error message if I just use the following usage:
`CM.write("d.hdf5",path="strain",append=True)`
(CM is a new timeseries to be append to an old hdf5 file (i.e., d.hdf5).)

**Comment by duncanmmacleod** [comment]
@linlupin, sorry for the delay, I am struggling for time to maintain GWpy these days.

> If I have a data (hdf5 file) of 24-s, is there any way to replace the strain of the data in 8-16 second ?

To do this you would have to load the full 24-second `TimeSeries` from the HDF5 file, manually replace the data in the middle, then write the new full object back to HDF5 - the `TimeSeries.write` method isn't smart enough to do all of that for you.

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1464, please join us on gitlab to continue your contribution!
