### ISSUE TITLE
Request: new methods for SnglBurst tables with multiple channels

### ISSUE THREAD

**Issue by areeda** [gwpy/gwpy#147]
**The problem**
There is a move to include multiple channels in SnglBurst tables that can greatly reduce the number of files produced by ETGs.  The current implementation of the gwpy.table.lsctables.SnglBurstTable could be augmented to aid in the use of these ligolw XML files.  It's likely that all producers of these tables will eventually store multiple channels in each XML file.  The question is how to use GWpy to efficiently consume them.

Currently the get_column can only return numeric data.  

**Use case**
Hveto currently uses Omicron triggers which have one channel per XML files.  Internal arrays that contain time, central frequency and SNR are created for each channel then the channels are compared each other.  

Other uses of these triggers such as plotting only the Strain channels can use the filter option efficiently if they only need triggers from one or two channels.

**Proposal**

This may be a bit self serving but as far as Hveto goes the ideal call would return a dictionary where the keys are channel names and the values are a list of tuples of columns specified in the call.

read_dict for lack of a better name would take the same arguments as read with the addition of an optional list of channel names.

**Comment by duncanmmacleod** [comment]
This issue has been open untouched for a long time, and I don't think such multi-channel `sngl_burst` XML files have ever become widely used. I am closing this issue, but it can be reopened if required.
