### ISSUE TITLE
Inconsistency in Q-transform plot when `logf=True`

### ISSUE THREAD

**Issue by Parth92** [gwpy/gwpy#1485]
`gwpy version: 2.0.1`

While trying to get the Q-transform data slices using log spaced freq bins, the usual `xx.plot()` command gives a map that is elevated in freqs. However, the `xx.plot(method='pcolormesh')` shows the correct one. 
An example script - 
```
data = TimeSeries.fetch_open_data('L1', 1126259460, 1126259464, verbose=True)
q_trans = data.q_transform(qrange=(4, 64),
                              frange=(10, 700),
                              tres=1/4096,
                              logf=True,
                              fres=200,
                              whiten=True)
```
Now plotting the Q-transform with `plot = q_trans[8192:-4096].plot()` gives a map that is elevated in freqs
![image](https://user-images.githubusercontent.com/24393713/158245183-8d1e7e4f-9f85-4fd7-a2a6-939425cff822.png)
Whereas, using `plot = q_trans[8192:-4096].plot(method='pcolormesh')` gives the correct map that looks like this,
![image](https://user-images.githubusercontent.com/24393713/158245532-8f63819b-d61a-46b7-97e0-9940e9678e55.png)
This difference doesn't occur if we set `logf=False, fres=1`.
Probably, using `logf=True` is creating the plot with a logarithmic scale, but the yticks are not being shown in log.
Forcing an explicit log yscale as,
```
plot = q_trans[8192:-4096].plot()
plt.yscale('log')
```
gives the exact same plot as first one but with the correct logarithmic ticks,
![image](https://user-images.githubusercontent.com/24393713/158246651-93c8093f-cd38-4d04-83b9-2d1c830da9a8.png)

**Comment by duncanmmacleod** [comment]
@Parth92, thanks for your report, sorry for the delay in responding.

Can you post the version of GWpy you are using, as well as the version of Matplotlib?

**Comment by duncanmmacleod** [comment]
> @Parth92, thanks for your report, sorry for the delay in responding.
> 
> Can you post the version of GWpy you are using, as well as the version of Matplotlib?

Sorry, I see that you already posted the version as 2.0.1...

**Comment by duncanmmacleod** [comment]
Are you able to reproduce this with the latest GWpy (2.1.3)?

**Comment by duncanmmacleod** [comment]
I think this will be automatically fixed in the next release, where the default rendering will use `pcolormesh` all of the time.

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1485, please join us on gitlab to continue your contribution!
