### ISSUE TITLE
plot method of SnglBurstTable uses a fraction-of-a-second reference time

### ISSUE THREAD

**Issue by tdent** [gwpy/gwpy#149]
For me (on ligo-la) this results in an x-axis with a fraction-of-a-second reference time (i.e. time in minutes from that time) and having the first axis tick at a fractional value, i.e. -2.98..... e-07 minutes. 

```python
sep15trigs = SnglBurstTable.fetch('L1:GDS-CALIB_STRAIN', 'omicron', 1127217617,1127239217)
oplot = sep15trigs.plot('time', 'central_freq', color='snr', edgecolor='none')
oplot.add_colorbar(clim=[3,50], label='SNR', cmap='hot_r')
oplot.savefig('public_html/detchar/ER8/ETMY_bounce/Omicron_STRAIN-Sep_15_12:00_18:00.png')
```

**Comment by tdent** [comment]
It's probably connected to this: if I do 

    sep15trigs = SnglBurstTable.fetch('L1:GDS-CALIB_STRAIN', 'omicron', 1126353617,1126375217)

then the first trigger is actually before the requested start time

    min([x.get_peak() for x in sep15trigs])
    Out[135]: LIGOTimeGPS(1126353081,460814952)

**Comment by duncanmmacleod** [comment]
So, I can reproduce the weird fractional value, and will fix. The issue with returned triggers having times outside of the requested interval is a separate issue that I have opened as #150.
