### ISSUE TITLE
GWPY resampling issue

### ISSUE THREAD

**Issue by kietphm** [gwpy/gwpy#1493]
There is an issue with the coherence function of gwpy.timeseries. It produces the larger than 1 coherence.
Besides, I tried to calculate coherence between DARM(H1:GDS-CALIB_STRAIN) and a channel (H1:SUS-OM1_M1_DAMP_L_IN1_DQ) with sampling frequency of 256Hz, and GWpy gives the frequencies series of up to ~8000 Hz. 

I dont think it makes sense to have information >128 Hz
I think there is an issue with resampling process in coherence calculation of GWPY.

```
from gwpy.timeseries import TimeSeriesDict
data = TimeSeriesDict.get(
    ['H1:GDS-CALIB_STRAIN', 'H1:SUS-OM1_M1_DAMP_L_IN1_DQ'],
    1245204018,
    1245204018 + 1800,
)
hoft = data['H1:GDS-CALIB_STRAIN']
acc = data['H1:SUS-OM1_M1_DAMP_L_IN1_DQ']
###Calculate coherence here
coh = hoft.coherence(acc, fftlength=2, overlap=0.5)
```
<img width="469" alt="image" src="https://user-images.githubusercontent.com/37116807/164055658-1cdd8e67-b8e5-4325-ac77-19223cc3827a.png">

I tried to go through the gwpy code and I think the issue came from the scipy.signal.resample() in line 955 at

https://github.com/gwpy/gwpy/blob/b5f791105efc5f78ce51f35455bcde8a5d36cef3/gwpy/timeseries/timeseries.py

I tried to use 'scipy.signal.decimate()' for resampling, and scipy.signal.coherence for coherence calculation and it gives a reasonable results. I tested out two filter provided by 'scipy.signal.decimate()', which are FIR AND IIR.

```
fsdown_darm = 16384
down_factor = int(16384//256)

###For FIR filter
downdata = sig.decimate(darm_data, down_factor,
                                ftype = 'fir',
                                zero_phase = True)
ftemp, Cxytemp = sig.coherence(test_data, downdata, fs = 256, nperseg=512)


                                
###For IIR filter
downdata2 = sig.decimate(darm_data, down_factor,
                                ftype = 'iir',
                                zero_phase = True)
ftemp, Cxytemp = sig.coherence(test_data, downdata2, fs = 256, nperseg=512)

```

Here are the results, they looks reasonable: 

<img width="481" alt="image" src="https://user-images.githubusercontent.com/37116807/164056748-8df6cda9-5175-4960-a62c-dd65477eece3.png">
<img width="443" alt="image" src="https://user-images.githubusercontent.com/37116807/164056824-07b92b78-ad8c-43a4-ba23-ff7eef52ee26.png">

In particular, the FIR filter does recover the 120Hz peak. 

I tested the conventional method of calculating coherence (FFT first -> clipped off the frequencies in the FFT -> PSD and CSD calculation -> Coherence). I manually write code for PSD and CSD calculation using the fft results of 'gwpy.timeseries.fftgram'.  It produced the same results compared to the FIR filter version of resampling.

**Comment by duncanmmacleod** [comment]
@kietphm, @asouthgate fixed this in #1611, which will be released as part of GWpy 3.0.5.
