### ISSUE TITLE
Bug with irregular sampling rate

### ISSUE THREAD

**Issue by artem-basalaev** [gwpy/gwpy#1506]
Hello! I found what looks like a bug in GWpy v2.1.3. 
Here's how to reproduce. This code works:

```python
import gwpy
import math
import numpy

a=numpy.zeros(500)
t=numpy.zeros(500)
for k in range(500):
    t[k]=k/100.
    a[k] = math.cos(50*float(k))+ 0.1*math.cos(float(k))


from gwpy.timeseries import TimeSeries
ts = TimeSeries(a, t0 = 1337089517.154, sample_rate = 100)
#ts.plot()
downsampled_ts = ts.resample(10)
downsampled_ts.plot()
downsampled_ts.psd()
```

And this code results in error ``AttributeError("This series has an irregular x-axis " "index, so 'dx' is not well defined")``
```python
import gwpy
import math
import numpy

a=numpy.zeros(500)
t=numpy.zeros(500)
for k in range(500):
    t[k]=k/100.
    a[k] = math.cos(50*float(k))+ 0.1*math.cos(float(k))


from gwpy.timeseries import TimeSeries
ts = TimeSeries(a, t0 = 1337089517.154, sample_rate = 100)
#Note this line below is UNCOMMENTED
ts.plot()
downsampled_ts = ts.resample(10)
downsampled_ts.plot()
downsampled_ts.psd()
```
Note just one line uncommented - to plot the time series, which supposedly should not _change_ anything further on, even if AttributeError is expected in some cases.

P.S.: Sorry if I formatting of this report is wrong (and please let me know why), this is the first time I'm opening an Issue.

**Comment by duncanmmacleod** [comment]
@artem-basalaev, apologies the delay in getting to this. I can reproduce this. I believe it to be a float precision issue in Python/Numpy where the check to see whether the X-axis index is 'regular' (monotonically increasing at constant rate) is too strict.

**Comment by duncanmmacleod** [comment]
The minimal reproducer can be simplified to:

```python
from astropy.units import Quantity
from gwpy.types import Index

a = Index.define(Quantity(1000000000, 's'), Quantity(0.01, 's'), 100)
assert a.is_regular()
assert a[::10].is_regular()
```
