### ISSUE TITLE
Add tolerance to `gwpy.testing.utils.assert_quantity_sub_equal`

### ISSUE THREAD

**Issue by meyers-academic** [gwpy/gwpy#1515]
It would be helpful to be able to pass a tolerance to the testing suite functions that compare whether two arrays are nearly equal:

Currently, `almost_equal` is a valid keyword argument ([see here](https://github.com/gwpy/gwpy/blob/main/gwpy/testing/utils.py#L174)) but the tolerance, even if passed as a keyword argument, doesn't appear to be used ([see here](https://github.com/gwpy/gwpy/blob/main/gwpy/testing/utils.py#L174)). However, `rtol` is a valid keyword argument for the `numpy.testing.assert_allclose` function that is used ([docs](https://numpy.org/doc/stable/reference/generated/numpy.testing.assert_allclose.html)).
 
 We are having issues with `pygwb` because our arrays are ending up "close enough" for us (within a relative tolerance of ~1e-6) but we are unable to set that tolerance ourselves and so some of our tests are occasionally failing.

@a-renzini

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1515, please join us on gitlab to continue your contribution!
