### ISSUE TITLE
Fetch HVeto round winners

### ISSUE THREAD

**Issue by rutujagurav** [gwpy/gwpy#1520]
Hello, 

Is there any way to fetch HVeto round winners for a given period of time from GWpy?

I can currently see HVeto round winners by visiting the summer pages (example - https://ldas-jobs.ligo-la.caltech.edu/~detchar/summary/day/20190601/detchar/hveto/) but it would be great if I can just fetch that top table in-script using GWpy.

**Comment by areeda** [comment]
I do not think GWpy has any specific support for this but the round summary is saved in a txt and a json file. At LLO or LHO from your account you could do something like:
```
ls /home/detchar/public_html/hveto/day/202002*/latest/summary-stats.{txt,json}
```
to get a list of all those files from Feb 2020.

**Comment by rutujagurav** [comment]
Thank you!
