### ISSUE TITLE
Possible bug with DataQualityFlag.fetch_open_data

### ISSUE THREAD

**Issue by jacobgolomb** [gwpy/gwpy#1527]
There seems to be a bug when grabbing a list of segments from O3 that includes O3a and O3b. Finding the active segments from a time period that includes all of O3 gives a segment list that ends at the end of O3a:

```
>>> from gwpy.segments import DataQualityFlag
>>> DataQualityFlag.fetch_open_data('V1_DATA', 'Apr 1 2019', 'Mar 27 2020').active.coalesce()[-1]
Segment(1253944467, 1253977218)
>>> gwpy.time.from_gps(1253977218)
datetime.datetime(2019, 10, 1, 15, 0)
```
This indicates that the final segment ends in October 2019, whereas I would expect the final segment to end in March 2020.

**Comment by duncanmmacleod** [comment]
@jacobgolomb, the issue here is that the data you require straddles multiple independent datasets and the GWOSC client doesn't know how to return to you all of the data you want. This is actually an issue with the GWOSC client, so I will open a new issue on that project.

**Comment by duncanmmacleod** [comment]
See https://git.ligo.org/gwosc/client/-/issues/85.
