### ISSUE TITLE
Rayleigh Specgram

### ISSUE THREAD

**Issue by rxa254** [gwpy/gwpy#1528]
For the Rayleigh grams, in addition to the useful Rayleigh specgram, I would like to make a Rayleigh spectrum overlayed on the instantaneous ASD. 

Do you have a reference for the origin of this code? I first saw a version written by Patrick Sutton back in ~2002.

**Comment by duncanmmacleod** [comment]
The Rayleigh spectrum code is here:

https://github.com/gwpy/gwpy/blob/a02196321919938a8fac019ab91af8abbff2d2c1/gwpy/signal/spectral/_scipy.py#L93-L134

I wrote that block, but apparently did not include a reference to the calculation itself. I could easily have taken my lead from Sutton's code, but can't remember.

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1528, please join us on gitlab to continue your contribution!
