### ISSUE TITLE
Request for example documentation on reading/writing `gwf` files

### ISSUE THREAD

**Issue by GregoryAshton** [gwpy/gwpy#1551]
As a user, that `name` gets used to set the `channel` attribute on write has confused me several times. It would be useful to add some documentation explaining this.

@duncanmmacleod I will try to submit an MR for this shortly.

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1551, please join us on gitlab to continue your contribution!
