### ISSUE TITLE
Inspiral range calculations without an fmax set below the Nyquist are wrong

### ISSUE THREAD

**Issue by eagoetz** [gwpy/gwpy#1573]
Inspiral range calculations give incorrect results unless `fmax` is set below the Nyquist frequency. Below is a simple example showing the time series calculation. The first two are incorrect, the third is set 10 Hz below the Nyquist and gives a sensible output.

```python
>>> from gwpy.timeseries import TimeSeries
>>> h1 = TimeSeries.get('H1:GDS-CALIB_STRAIN', 'feb 29 2020 00:00:00', 'feb 29 2020 00:05:00')
>>> import gwpy.astro as astro
>>> astro.range_timeseries(h1, stride=60, fftlength=10, overlap=5, fmin=10)
<TimeSeries([184.01153865, 168.89645704, 181.75185037,
             179.10572224, 165.1965439 ]
            unit=Unit("Mpc"),
            t0=<Quantity 1.26696962e+09 s>,
            dt=<Quantity 60. s>,
            name='H1:GDS-CALIB_STRAIN',
            channel=<Channel("H1:GDS-CALIB_STRAIN" [reduced], 16384.0 Hz) at 0x16441bc10>)>
>>> astro.range_timeseries(h1, stride=60, fftlength=10, overlap=5, fmin=10, fmax=16384/2)
<TimeSeries([184.01153865, 168.89645704, 181.75185037,
             179.10572224, 165.1965439 ]
            unit=Unit("Mpc"),
            t0=<Quantity 1.26696962e+09 s>,
            dt=<Quantity 60. s>,
            name='H1:GDS-CALIB_STRAIN',
            channel=<Channel("H1:GDS-CALIB_STRAIN" [reduced], 16384.0 Hz) at 0x16441bc10>)>
>>> astro.range_timeseries(h1, stride=60, fftlength=10, overlap=5, fmin=10, fmax=16384/2-10)
<TimeSeries([117.94742378, 117.82970783, 117.79845777,
             116.12951017, 115.57842847]
            unit=Unit("Mpc"),
            t0=<Quantity 1.26696962e+09 s>,
            dt=<Quantity 60. s>,
            name='H1:GDS-CALIB_STRAIN',
            channel=<Channel("H1:GDS-CALIB_STRAIN" [reduced], 16384.0 Hz) at 0x16441bc10>)>
```

**Comment by duncanmmacleod** [comment]
@eagoetz, I can reproduce this. Fundamentally I believe this is because the PSD of real LIGO data drops off after 7kHz because of the DAQ anti-aliasing/downsampling.

Since this would (should?) not be true of simulated data, and GWpy is designed to be as generic as possible, I would like to consider keeping the current defaults of 'do nothing', but can be convinced otherwise.

**Comment by duncanmmacleod** [comment]
If the defaults are not to be changed, I recommend at least adding a note in the docstring for the `range_timeseries` function along the lines of

> If given a `TimeSeries` as input, this method generates a PSD according to the parameters given, and then calculates the range **over the full span of that PSD**.
> If the input data were recorded from a real system, this may include frequency-domain artifacts from data acqusition (e.g. downsampling/antialiasing filter roll-off), so it is strongly encouraged that ``fmin`` and ``fmax`` parameters are used to constrain the range estimate to a valid interval.

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1573, please join us on gitlab to continue your contribution!
