### ISSUE TITLE
Help!  I'm mixing up hdf5.losc and hdf5.gwosc

### ISSUE THREAD

**Issue by jkanner** [gwpy/gwpy#1584]
Hi,

I got this interesting error message, using a fresh build of the IGWN-py39 conda environment.  It looks like the code is using both the names `hdf5.losc` and `hdf5.gwosc`, and so failing to read in a GWOSC HDF5 file.  I wonder if this is a bug, or some issue related to the particular file.  Any advice would be appreciated.  Thank you!

```
astropy.io.registry.base.IORegistryError: No reader defined for format 'hdf5.losc' and class 'TimeSeries'.

The available formats are:

   Format    Read Write Auto-identify
------------ ---- ----- -------------
         csv  Yes   Yes           Yes
         gwf  Yes   Yes           Yes
gwf.framecpp  Yes   Yes            No
  gwf.framel  Yes   Yes            No
gwf.lalframe  Yes   Yes            No
        hdf5  Yes   Yes           Yes
  hdf5.gwosc  Yes    No            No
         txt  Yes   Yes           Yes
         wav  Yes   Yes           Yes
```

**Comment by duncanmmacleod** [comment]
@jkanner, as the error message shows, `hdf5.losc` is not a valid format argument. This format was deprecated by `hdf5.gwosc` in [gwpy-2.1.0](https://github.com/gwpy/gwpy/releases/tag/v2.1.0) (see https://github.com/gwpy/gwpy/pull/1392) and removed in [gwpy-3.0.0](https://github.com/gwpy/gwpy/releases/tag/v3.0.0) (see https://github.com/gwpy/gwpy/pull/1465).

**Comment by jkanner** [comment]
D'oh!  Of course the bug is in my script.  Silly of me to not look at my own code before reporting the issue.  Thanks for the quick help!  @duncanmmacleod
