### ISSUE TITLE
There are missing variable in the function to_pycbc()

### ISSUE THREAD

**Issue by hongyp007** [gwpy/gwpy#1589]
def to_pycbc(self, copy=True):
        """Convert this `TimeSeries` into a PyCBC
        `~pycbc.types.timeseries.TimeSeries`
        Parameters
        ----------
        copy : `bool`, optional, default: `True`
            if `True`, copy these data to a new array
        Returns
        -------
        timeseries : `~pycbc.types.timeseries.TimeSeries`
            a PyCBC representation of this `TimeSeries`
        """
        from pycbc import types
        return types.TimeSeries(self.value,
                                delta_t=self.dt.to('s').value,
                                epoch=self.epoch.gps, copy=copy)

This function returns only, <self.value,  delta_t=self.dt.to('s').value, epoch=self.epoch.gps, copy=copy>.

However, Timeseries from pyCBC needs variables : self, initial_array, delta_t, epoch, dtype, copy.

For this reason, when I use the function to_pycbc(), I got error : initial_array must contain at least one sample.

Please check this issue.

**Comment by duncanmmacleod** [comment]
@hongyp007, I'm sorry, but I don't really understand the problem you are seeing. Are you able to post a snippet of python code that reproduces an error?

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1589, please join us on gitlab to continue your contribution!
