### ISSUE TITLE
TimeSeries.read with cachefile generates warnings

### ISSUE THREAD

**Issue by adrianmacquet** [gwpy/gwpy#1594]
Hi, I get  warnings when using TimeSeries.read using a cache file.

The cache file (created with `lal_cache`) looks like this:
```
H	H1_BurstBenchmark	1262307072	1024	file://localhost/home/florent.robinet/BurstBenchmark/H-H1_BurstBenchmark-1262307072-1024.gwf
```
When using `TimeSeries.read()` to read data using the cache file, e.g like this:
```
from gwpy.timeseries import TimeSeries
tsd = TimeSeries.read('H1.cache', start = 1262307072, end = 1262307080, channel='H1:STRAIN')
```
I get the following message:
```
XLAL Error - new_tagLIGOTimeGPS__SWIG_3 (swiglal_lal_python.c:11051): 'H1_BurstBenchmark' is not a valid LIGOTimeGPS
XLAL Error - new_tagLIGOTimeGPS__SWIG_3 (swiglal_lal_python.c:11051): Invalid argument
```
Note that the files are read correctly, but these warnings are annoying as they saturate the logs. 
This is done in the igwn-py39 environment with gwpy 3.0.0.

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1594, please join us on gitlab to continue your contribution!
