### ISSUE TITLE
GravitySpyTable not listed in API docs

### ISSUE THREAD

**Issue by myNameIsPatrick** [gwpy/gwpy#1597]
The only place I see GravitySpy information is in https://gwpy.github.io/docs/stable/table/io/#accessing-gravityspy-events but I can't see the API docs corresponding to the `GravitySpyTable` class.

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1597, please join us on gitlab to continue your contribution!
