### ISSUE TITLE
AttributeError: type object 'FrVect' has no attribute 'ZERO_SUPPRESS_WORD_2'

### ISSUE THREAD

**Issue by aromerorodriguez** [gwpy/gwpy#1598]
I am getting an error I had never seen before: AttributeError: type object 'FrVect' has no attribute 'ZERO_SUPPRESS_WORD_2' (retrieved from this error file in the Caltech cluster (CIT): /home/alba.romero/SGWB/Non_linear_noise_subtraction/Task2/Without_NLNS/output/condorLogs/condor_1253442015-1253447015.err) when submitting jobs to HTCondor.

Description of my runs:
1. Running in this directory: /home/alba.romero/SGWB/Non_linear_noise_subtraction/Task2/Without_NLNS/
2. Data on which I am runnnign the analysis: O3 LIGO-Virgo-KAGRA data
3. jobfile: /home/alba.romero/SGWB/Non_linear_noise_subtraction/Task2/jobfile.txt
4. paramfile: /home/alba.romero/SGWB/Non_linear_noise_subtraction/Task2/Without_NLNS/parameters.ini

**Comment by duncanmmacleod** [comment]
This was fixed in GWpy 3.0.3.
