### ISSUE TITLE
TimeSeriesDict plotting does not work as expected

### ISSUE THREAD

**Issue by rutujagurav** [gwpy/gwpy#1609]
The TimeSeriesDict `plot()` function is convenient and has several options like `sharex` and `separate`. But I have found that they don't work as expected. Consider the following example code - 

```
from gwpy.timeseries import TimeSeries, TimeSeriesDict
from gwpy.time import to_gps, from_gps
from gwpy.plot import Plot

start_gps = to_gps('2020-01-04T00:00:00')
end_gps = to_gps('2020-01-4T01:00:00')
example_chs = ['L1:ISI-GND_STS_ETMX_X_BLRMS_30M_100M.rms,s-trend', 'L1:ISI-GND_STS_ETMX_X_BLRMS_100M_300M.rms,s-trend', 'L1:ISI-GND_STS_ETMX_X_BLRMS_1_3.rms,s-trend']
data = TimeSeriesDict.get(example_chs, start=start_gps, end=end_gps, allow_tape=True)

plot = data.plot(label='key', separate=True, sharex=True)
plot.legend()
plot.show()
```

The output plot does not make separate plots for each item of the dictionary (i.e. each channel) - 
![98373592-cb84-4a1b-8607-8a627a8a15cf](https://user-images.githubusercontent.com/14856287/233891553-6b3883ea-f528-45ce-b377-399ea02404c9.png)

It's the same result if you use the Plot() function instead as I believe the data.plot() is using Plot() under the hood. 
```
plot = Plot(data, sharex=True, separate=True)
plot.show()
```

If you instead run the following code, you get the expected outcome of `separate` and `sharex` set to True but the plots are empty. 

```
plot = Plot(*data, sharex=True, separate=True)
plot.show()
```

![c3e9dbef-c12a-4c44-927f-a92fec8f0fd1](https://user-images.githubusercontent.com/14856287/233892003-4d3b4130-c1c1-4564-924c-1f824a0f0eed.png)

If you run the following code, you get the right plots and `separate` and `sharex` work as expected but there is not way to satisfactorily add an unambiguous legend or title to the subplots to identify them by the channel name. 

```
plot = Plot(*[value for key, value in data.items()], sharex=True, separate=True)
plot.legend(list(data.keys()))
plot.show()
```

![8e39415f-7cff-4e57-ba6f-8a5b5a3c9069](https://user-images.githubusercontent.com/14856287/233893014-1f35cba0-29bf-47f8-ae63-c10710534df8.png)

The expected behavior of setting `sharex` and `separate` to True for a TimeSeriesDict is a figure with subplots corresponding to the timeseries of each item in the dict where each subplot is identified (via a legend or title) with the channel name. If the legend for the separate subplots is going to be combined like in the last plot above, then the subplots need to be different colors. 

My GwPy version is 3.0.2

**Comment by rutujagurav** [comment]
Hello,

I am reopening this issue as the TimeSeriesDict().plot() still doesn't produce ideal behavior.
 
In gwpy 3.0.5, if I now run `plot = data.plot(label='key', separate=True, sharex=True)` it makes the plot shown in the last figure. As I mentioned earlier, if when `separate=True` the names of the channels are going to be placed in a single legend, then the subplots ought to be different colors. If that's too complicated then the names of the channels should instead be displayed as subplot titles and not legend. In my opinion, the latter is ideal as then all subplots can be the same color and the channels names can be easily read from the subplot titles.

**Comment by duncanmmacleod** [comment]
Hi @rutujagurav.

> if when separate=True the names of the channels are going to be placed in a single legend, then the subplots ought to be different colors.

In your example code the `plot.legend()` line is what is generating a single legend, GWpy does not generate a legend automatically. If you replace that with a call to `Axes.legend()` in a loop then you will get a single legend for each subplot:

```python
for ax in plot.axes:
    ax.legend()
```

Or you can, as you suggest, use the channel name as the axes title:

```python
for ax, channel in zip(plot.axes, example_chs):
    ax.set_title(channel)
```

[UNTESTED]

Please let me know if that works for you.

**Comment by rutujagurav** [comment]
Ah, I see! Thanks for helping me out.

Following code produces the plot I expect

```
plot = data.plot(separate=True, sharex=True)
for ch_name, ax in zip(data.keys(), plot.axes):
  ax.set_title(ch_name)
plot.tight_layout()
plot.show()
``` 
![image](https://github.com/gwpy/gwpy/assets/14856287/139cff71-a5e9-457e-b025-1aabac5852be)
