### ISSUE TITLE
_dynamic_scaled() causing issues with H0 and L0 data

### ISSUE THREAD

**Issue by dethodav** [gwpy/gwpy#1627]
While investigating data normalization issues for the public summary pages, I noticed that at least some H0 and L0 data no longer require ADC scaling, similar to the H1 and L1 channels. Hence, the default behavior when using framecpp is to mis-scale the data. To resolve this, either `_dynamic_scaling` should get removed and the default scaled value should always be set to False or there should be a date-related switch to account for the change in ADC scaling. 

I will note that I haven't extensively checked all H0 and L0 channels, only the temperature channels shown on the summary pages. The scaling of these channels changed in Sept 2020, corresponding to a CDS upgrade at the sites. More checks may be needed before we decide how to resolve this issue. 

@duncanmmacleod @eagoetz

**Comment by dethodav** [comment]
For reference, here is the `_dynamic_scaling` function I am talking about and where it interacts with `framecpp`

https://github.com/gwpy/gwpy/blob/7c0593799cf0f2548156771c6d58f02bbae6ed06/gwpy/timeseries/core.py#L83-L111

https://github.com/gwpy/gwpy/blob/7c0593799cf0f2548156771c6d58f02bbae6ed06/gwpy/timeseries/io/gwf/framecpp.py#L192-L193

**Comment by dethodav** [comment]
Looking through the issue history - perhaps Virgo data still requires the ADC bias and scaling to be applied? https://github.com/gwpy/gwpy/issues/749

**Comment by duncanmmacleod** [comment]
@dethodav, can you please post a snippet of code that demonstrates the problem, and include a description of what you think the result _should_ be.

**Comment by duncanmmacleod** [comment]
I see that that the code you linked explicitly talks about at `H1` and `L1` and **not** `H0` and `L0`, which is probably just an oversight on my part:

https://github.com/gwpy/gwpy/blob/7c0593799cf0f2548156771c6d58f02bbae6ed06/gwpy/timeseries/core.py#L111

If you post a code block I can look at a quick fix patch.

**Comment by dethodav** [comment]
@duncanmmacleod I've opened #1628 to address this.

At the time of the original PR, the H0 and L0 channels still needed scaling, but it seems that this changed the following year.

**Comment by duncanmmacleod** [comment]
This was fixed in #1628, which will be released in 3.0.5.
