### ISSUE TITLE
Replace GWpy's bilinear_zpk function with scipy's

### ISSUE THREAD

**Issue by duncanmmacleod** [gwpy/gwpy#1630]
GWpy has an implementation of a bilinear transform for ZPK filter coefficients. This was written before [`scipy.signal.bilinear_zpk`](https://docs.scipy.org/doc/scipy-1.1.0/reference/generated/scipy.signal.bilinear_zpk.html) was available, but should probably now just be dropped (or hollowed out with a deprecation warning) in favour of the Scipy version.

**Comment by vbaws** [comment]
The present implementation actually casts poles and zeroes to floats, which breaks all sorts of functionality.
```
.../gwpy/signal/filter_design.py:284: ComplexWarning: Casting complex values to real discards the imaginary part
  zeros = numpy.array(zeros, dtype=float, copy=False)
.../gwpy/signal/filter_design.py:286: ComplexWarning: Casting complex values to real discards the imaginary part
  poles = numpy.array(poles, dtype=float, copy=False)
```
This makes it impossible to replicate LIGO front end filter banks to replicate responses. to signals. These must be cast to np.complex128

**Comment by asouthgate** [comment]
Hi, Duncan and I discussed this recently but I have not gotten around to fixing it. I think the idea was to just drop this for scipy's implementation. But it probably requires updating some unit tests.

Will fix on Monday unless urgent.

**Comment by vbaws** [comment]
Not urgent.

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1630, please join us on gitlab to continue your contribution!
