### ISSUE TITLE
ValueError when reading  local GW  data from Virgo (V1.cache)

### ISSUE THREAD

**Issue by weizmannk** [gwpy/gwpy#1635]
I tried to read a   local   data,  Virgo's  raw data, using ,

 **data = TimeSeriesDict.read(cache_file, channels=channels, start=t0, end=t1, nproc=4, format='gwf')**
with cache_file = [V1.cache](https://ldas-jobs.ligo.caltech.edu/~weizmann.kiendrebeogo/V1.cache)

But I got this  error "ValueError: TimeSeries units do not match: weight vs weight".

and 

WARNING: UnitsWarning: weight is not a valid unit. Mathematical operations using this unit should work, but conversions to other units will not. [gwpy.detector.units]

For more information : the individual files read in properly.
Does anyone have any idea what's going wrong? 

Thanks

**Comment by duncanmmacleod** [comment]
@weizmannk, thanks for the report. Can you give some more information about how I can reproduce this? What are the values of each of `channels`, `t0`, and `t1`?

As for the `WARNING` that is just because `'weight'` isn't recognised as a unit by Astropy. The unit should be something like `kg` instead. I'll contact Virgo staff to see if that can be corrected.

**Comment by weizmannk** [comment]
Hi @duncanmmacleod , Thanks , sure, 

My data  are on **CIT**,  at  /home/weizmann.kiendrebeogo/O3b/V1

The 

from gwpy.timeseries import  TimeSeriesDict

t0 = 1263000000
t1 = 1263001100

cache_file = '/home/weizmann.kiendrebeogo/DeepClean/deepclean/Virgo/V1.cache' 
channels = ['V1:Hrec_hoft_16384Hz',  'V1:Hrec_hoft_16384Hz_Gate', 'V1:Hrec_hoft_16384Hz_GateMinRange',
                                         'V1:Hrec_hoft_16384Hz_Gated', 'V1:Hrec_hoft_16384Hz_GateRange']

data = TimeSeriesDict.read(cache_file,  channels=channels, start=t0, end=t1, nproc=4, format='gwf')


Thank you.

**Comment by weizmannk** [comment]
@duncanmmacleod  You are right , Thanks 
I remove my channels and replace it by another channels ,
 I used this channel  'V1:Hrec_hoft_16384Hz' , plus  PEM and ASC witness channels, and it's work fine. Then there is no more `WARNING`` . 
 channels = ['V1:Hrec_hoft_16384Hz', 'V1:ENV_CEB_UPS_VOLT_S', 'V1:SPRB_B4_56MHz_Q', 'V1:SIB2_B2_8MHz_I'] 
 
 By the way I am still interest to know why  , those  channels : ** 'V1:Hrec_hoft_16384Hz_Gate', 'V1:Hrec_hoft_16384Hz_GateMinRange', 'V1:Hrec_hoft_16384Hz_Gated', 'V1:Hrec_hoft_16384Hz_GateRange'**
 
 generate the `''WARNING``
 
 Thank you so.

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1635, please join us on gitlab to continue your contribution!
