### ISSUE TITLE
Add TimeSeries data-access method to read data from a directory

### ISSUE THREAD

**Issue by duncanmmacleod** [gwpy/gwpy#1638]
@stuartthebruce has suggested a new data-discovery method that is half-way between `TimeSeries.read` (which requires a list of files) and `TimeSeries.find` (which calls out to gwdatafind) which does 'here's a directory and some parameters, go find my data in there and read them'.

The use case for LIGO is point GWpy at `/dev/shm{/kafka}` and have it read the data from there for a given GPS interval.

**Comment by stuartthebruce** [comment]
For example, extend `TimeSeries.read` to support accepting a directory and add a `Frame Type` that assumes the LIGO frame file naming convention applies (OBS-TYPE-GPS_START-DURACTION.gwf).

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1638, please join us on gitlab to continue your contribution!
