### ISSUE TITLE
Unexpected behavoir when using crop function

### ISSUE THREAD

**Issue by dethodav** [gwpy/gwpy#1656]
This issue was first mentioned in #1601 and fix was merged in #1621. Using gwpy==3.0.5, I still see unexpected behavior related to floating point precision with the `crop()` function. 

The following example shows the problem: 
```
len = 100
right = 0
wrong = 0
for x_max in list(numpy.random.random(100)) :
  x_series = numpy.linspace(0,x_max, len)
  series = Series([0]*len, xindex=x_series)
  expected = series.xindex[-2]
  if series.crop(end=x_max).xindex[-1] == expected:
    right += 1
  else:
    wrong += 1

print('RIGHT', right)
print('WRONG', wrong)
```
In this example, I generate a series with 100 samples and a final index between 0 and 1. I then crop the Series at the chosen final index. Whether the new series will crop 1 or 2 points from the original Series is random. Cropping 1 point happens ~95% of the time and cropping 2 points happens ~5% of the time.

**Comment by asouthgate** [comment]
It's occasionally cutting off one too many values for regular spaced arrays. I suspect it is a precision issue with float division in Series.py:1030. 

`idx1 = floor((xtype(end) - x0) / self.dx.value)`

For example if L=500, end=0.508463154883984, dx=0.001018964238244457, this gives 498.99999999999994, which is then truncated to 498, but we want i * dx for element i+1, so 499 * dx = end for the 500th element.

The example code above passes by replacing floor with round. But some more tests would be good.

**Comment by duncanmmacleod** [comment]
@dethodav, the example you post is, in my opinion, not an ideal example of the more general problem, since the extreme precision of the random float is critical to the operation. Are you able to post a more 'real-world' example where this issue arises?

**Comment by dethodav** [comment]
@duncanmmacleod Here is a simpler example that shows the behavior: 

```
import numpy
from gwpy.types import Series

def check_val(x_max):
      x_series = numpy.linspace(0,x_max, 100)
      series = Series([0]*100, xindex=x_series)
      expected = series.xindex[-2]
      print(expected, series.crop(end=x_max).xindex[-1], expected == series.crop(end=x_max).xindex[-1])

check_val(10)
check_val(1)
```

This returns 
```
>>> check_val(10)
9.8989898989899 9.8989898989899 True
>>> check_val(1)
0.98989898989899 0.9797979797979799 False
```

Hence, we are still susceptible to floating point issues with "normal" numbers.

**Comment by dethodav** [comment]
In good news, I no longer see any issues when running both examples with the current main branch (which includes #1658). Closing issue.
