### ISSUE TITLE
TimeSeries / IO / nds2.py Progress Bar Inaccurate

### ISSUE THREAD

**Issue by jeffrey-kissel** [gwpy/gwpy#1670]
I'm grabbing data from the control room, and asking for 20 minutes (1500 sec) of 16 Hz channel data from July 26 2023 at 01:10 UTC (channel list below).

While I'm patiently waiting for the data, I get a lot of either unknown or mixed messaging from what I guess is the nds.py fetch method underneath what I'm realy using -- the over-arching TimeSeriesDict method from gwpy ver 3.0.4 (under Python 3.9.13).

Namely, repeating the same call to TimeSeries dict several times in the course of a few minutes, I get the data returned in an apparently random amount of time, from as large as ~10 minutes (yes, 10 minutes!) to within a few seconds -- and the progress bar is entirely unhelpful during that time -- holding at "0%", with an ETA of "?" for quite a long time. If/when it does pick up data, it estimates 35 minutes, 10 minutes, or just finishes, none of which are (anecdotally) accurate.

No idea what's really going on underneath the hood, and *definitely* have no idea how to solve it; just wanted to bring it y'all's attention, since I didn't see any open or closed issues reflecting this issue.

**Comment by jeffrey-kissel** [comment]
Here's my code snippet:
```
from gwpy.timeseries import TimeSeriesDict as tsd

utctime_LHO72622 = '2023-07-26 01:10 UTC'
gpstime_LHO72622 = 1374369018
start = gpstime_LHO72622 - 300
end = gpstime_LHO72622 + 1200
chanList = ['H1:GRD-ISC_LOCK_STATE_N',
            'H1:CAL-CS_TDEP_KAPPA_C_OUTPUT',
            'H1:CAL-CS_TDEP_F_C_OUTPUT',
            'H1:CAL-CS_TDEP_KAPPA_UIM_REAL_OUTPUT',
            'H1:CAL-CS_TDEP_KAPPA_PUM_REAL_OUTPUT',
            'H1:CAL-CS_TDEP_KAPPA_TST_REAL_OUTPUT',
            'H1:GDS-CALIB_KAPPA_C',
            'H1:GDS-CALIB_F_CC',
            'H1:GDS-CALIB_KAPPA_UIM_REAL',
            'H1:GDS-CALIB_KAPPA_PUM_REAL',
            'H1:GDS-CALIB_KAPPA_TST_REAL']

tdcfs = tsd.get(chanList, start, end, frametype='R',verbose=True) 

```

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1670, please join us on gitlab to continue your contribution!
