### ISSUE TITLE
Fix inconsistency with TimeSeries.resample

### ISSUE THREAD

**Issue by vbaws** [gwpy/gwpy#1673]
gwpy.timeseries.TimeSeries.resample should at least replicate LIGO's up-sampling functionality of copying samples when resampling to a higher sample rate.

In my testing asking for a higher sample rate does nothing presently.

**Comment by asouthgate** [comment]
Hi @vbaws, sounds like a bug. It shouldn't do nothing. Could you provide a snippet for a circumstance that fails?

`
from gwpy.timeseries import TimeSeries
import matplotlib.pyplot as plt
from gwpy.plot import Plot
from numpy import random

series = TimeSeries(random.random(1000), sample_rate=100, unit='m')
resamp = series.resample(series.sample_rate * 1.1)

assert series.sample_rate < resamp.sample_rate

Plot(series, resamp)

plt.show()
`

Seems to upsample okay.

**Comment by asouthgate** [comment]
Sure, no problem. I am on leave next week but will take a look afterward.

**Comment by vbaws** [comment]
Regarding "Can I ask more specifically on the reason this particular upsampling method is needed or a reference for my information? We could add this as a feature request." : 

This is how upsampling operates in the LIGO front ends. I needed to utilise it in an attempt to debug the signal flow from some my channels after they are upsampled. Creating imaging of the signal of through these means is genuinely something we make use of when trying to actuate on something at a frequency far above our sampling rate. Filtering above f_s/2 isn't "real" in the digital system and is done through anti-imaging analog chassis. These have their own filter responses that can be modeled independently, or in my case, there might not be any anti-imaging deliberately.

**Comment by asouthgate** [comment]
Okay sure, I am happy to add this as a feature early next week.

**Comment by duncanmmacleod** [comment]
This use case seems extremely specific to the way the LIGO analog<->digital controls system is configured.

GWpy basically relies on Scipy for all of its actual signal processing routines (that's not _entirely_ true, but I would like it to be), so am hesitant to implement something that may require significant testing/maintenance.

However, if the code is simple enough to understand, to test, and to maintain, I may be convinced.

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1673, please join us on gitlab to continue your contribution!
