### ISSUE TITLE
DataQualityFlag subtraction operator does not do exactly what the documentation tells

### ISSUE THREAD

**Issue by adrianmacquet** [gwpy/gwpy#1700]
In this page of the documentation: https://gwpy.github.io/docs/stable/segments/#subtraction, it is told that the subtraction operator "returns the union of the known segments, and the difference of the active segment lists."
However it seems that it actually returns the intersection of known segments, as shown in the following piece of code:

```
from gwpy.segments import DataQualityFlag

a = DataQualityFlag(known=[(0, 15)], active=[(1, 5), (10, 12)])
b = DataQualityFlag(known=[(0, 5)], active=[(0,1)])

print(a-b)
>> <DataQualityFlag(None,
                 known=[[0 ... 5)]
                 active=[[1 ... 5)]
                 description=None)>
```
Therefore the segment (10,12) is removed from a despite not being active in b. For me, this created an issue when using the subtract operator to remove segments associated with DQflags from science segments.

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1700, please join us on gitlab to continue your contribution!
