### ISSUE TITLE
DataQualityFlag (start,end) parameters or crop functionality

### ISSUE THREAD

**Issue by rutujagurav** [gwpy/gwpy#1704]
Hello, 

If I have a HDF5 file containing the active segments for, say, a whole observing run and for some analysis I only want to select a smaller interval of time within the full time that that HDF5 file spans, how would I only read some (start, end) sub-interval into a DataQualityFlag?

**Comment by duncanmmacleod** [comment]
Hi @rutujagurav 👋🏻. Short answer: you can't really. The closest thing you _can_ do is to read the file and the immediately restrict via an intersection operation from a second `DataQualityFlag` that just represents the interval:

```python
from gwpy.segments import (DataQualityFlag, Segment, SegmentList)
span = Segment(<start>, <end>)
segs = DataQualityFlag.read(<hdf5 file>) & DataQualityFlag(active=[span], known=[span])
```

It's not pretty, but should work.

**Comment by rutujagurav** [comment]
Thank so much @duncanmmacleod ! That worked!
