### ISSUE TITLE
'times' argument accepts 2-dimensional data when creating a TimeSeries object

### ISSUE THREAD

**Issue by rmacas** [gwpy/gwpy#1705]
There is no check (or the check is incomplete) for the 'times' argument to accept only 1-dimensional data when creating a TimeSeries object. This causes various issues down the line, eg resampling.

```
import numpy as np
from gwpy.timeseries import TimeSeries

vals = [1, 2, 3, 4]
arr1 = np.array(vals)
arr2 = np.array(vals).reshape(-1, 1)

ts1 = TimeSeries(arr2, times=arr1)
```
Produces an error "ValueError: Cannot generate TimeSeries with 2-dimensional data".

However, this does not which causes errors elsewhere in the code, e.g. resampling:

```
import numpy as np
from gwpy.timeseries import TimeSeries

vals = [1, 2, 3, 4]
arr1 = np.array(vals)
arr2 = np.array(vals).reshape(-1, 1)

ts1 = TimeSeries(arr1, times=arr2)
ts1.resample(4096)
```
"AttributeError: 'numpy.ndarray' object has no attribute 'is_integer'"

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1705, please join us on gitlab to continue your contribution!
