### ISSUE TITLE
Using interpolated images for spectrograms would be nice

### ISSUE THREAD

**Issue by jrsmith02** [gwpy/gwpy#172]
For visualizing short, quickly varying things, using spectrograms with high overlap and interpolation, and plotting them as images is quite useful. For scatter plotting, I have been using NonUniformImage (note: I thought this allows both lin and log y-axis, but perhaps that depends on python version because currently at LLO I'm only able to make lin). 

Here is an example of scattering fringes at LLO: 
![l1-lsc-srcl_in1_dq-1129118930-30](https://cloud.githubusercontent.com/assets/7536082/10975814/92ad9b76-839d-11e5-9512-8bed1f940d94.png)

And here is a complete, sloppy, python script to reproduce this result.

``` python
from gwpy.timeseries import TimeSeries
from gwpy.time import from_gps
from numpy import sqrt, array, arange, nonzero, argmax, log10
from pylab import savefig, specgram
import sys, string 
import matplotlib.pyplot as plt
from matplotlib.image import NonUniformImage
import matplotlib.mlab as mlab
from os import makedirs, path

# read input argumentsi (update this to use argparse)
ifo = 'L1'
start_time = 1129118930
startutc = str(from_gps(start_time)) # get UTC time
dur = 30 # duration in seconds
end_time = int(start_time) + int(dur)
witness_base = 'LSC-SRCL_IN1_DQ'
witness_chan = ifo + ':' + witness_base
# load timeseries for witness channel
witness=TimeSeries.fetch(witness_chan, start_time, start_time+dur, verbose=True)
witness=witness.highpass(10,gpass=3) # highpass the witness data
# Calculate spectrogram 
secsPerFFT = 1.0 # Hz
overlap = 0.9 # fractional overlap
Fs = witness.sample_rate.value
NFFT = int(round(Fs*secsPerFFT))
noverlap = int(round(overlap*NFFT))
Pxx, freq, t, im = specgram(witness.value,NFFT=NFFT,Fs=witness.sample_rate.value,noverlap=noverlap,scale_by_freq='magnitude',detrend=mlab.detrend_linear,window=mlab.window_hanning)

fig = plt.figure(figsize=(12,12))
ax1 = fig.add_subplot(111)
# Plot Spectrogram
im1 = NonUniformImage(ax1, interpolation='bilinear',extent=(min(t),max(t),10,55),cmap='jet')
im1.set_data(t,freq,20.0*log10(Pxx))
im1.set_clim(-160,-20)
ax1.images.append(im1)
cbar1 = fig.colorbar(im1)
plt.yscale('linear')
plt.ylabel('Frequency [Hz]',fontsize=24)
xlab = 'Time [seconds] from ' + str(startutc) + ' UTC'
plt.xlabel(xlab,fontsize=24)
plt.title(witness_chan,fontsize=24)
plt.xlim(0,max(t))
plt.ylim(1,25)

# save figure
dir = ifo + '-' + str(start_time) + '-' + str(dur) + '/'
if not path.exists(dir):
    makedirs(dir)
filename = dir + ifo + '-' + witness_base + '-' + str(start_time) + '-' + str(dur) + '.png'
savefig(filename)
plt.close(fig)
```

**Comment by duncanmmacleod** [comment]
@jrsmith02: what's the reason you're not using the [`TimeSeries.spectrogram2`](https://gwpy.github.io/docs/stable/timeseries/#gwpy.timeseries.TimeSeries.spectrogram2) method to calculate the spectrogram?

**Comment by jrsmith02** [comment]
I believe the reason is that it doesn't produce an image as an output.

**Comment by duncanmmacleod** [comment]
Can you also edit the above comment to include the variables need to run this code end-to-end: `witness_chan`, `start_time`, ... Thanks.

**Comment by duncanmmacleod** [comment]
@jrsmith02: I can't run this example and produce an image. I get the following error:

```python
>>> fig.savefig('gwpy-172.png')
...
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/image.py", line 752, in make_image
    raise RuntimeError('You must first set the image array')
RuntimeError: You must first set the image array
```

Can repost a fully working example?

**Comment by duncanmmacleod** [comment]
@jrsmith02 you mentioned the abillity to make logarithmic scale images? matplotlib has never supported proper log-scale images, but can easily change the axes to show log scale (but the image itself is not scaled). Do you have an example of a log-scaled image?

I am happy to allow users to generate Spectrogram plots using this method, whilst explicitly disallowing log scales.
