### ISSUE TITLE
Inconsistent handling of negative epoch in FrequencySeries  

### ISSUE THREAD

**Issue by FrankOhme** [gwpy/gwpy#1739]
@MaxMelching found the following inconsistent behaviour when storing a negative epoch in `FrequencySeries` .

When a `FrequencySeries` epoch is set to a negative value of the same type it is returned, the epoch that is actually stored is greater than the input epoch by unity. In particular, setting a negative FrequencySeries epoch equal to itself results in an inconsistent output.

### Minimal example
```python
from gwpy.frequencyseries import FrequencySeries

fs = FrequencySeries(np.arange(10), epoch=-2.3)
print('epoch 1: \t{}'.format(fs.epoch))
fs.epoch = fs.epoch
print('epoch 2: \t{}'.format(fs.epoch))
```
This produces the following output.
```
epoch 1: 	-2.299999999991087
epoch 2: 	-1.299999999994128
```

### Suspected cause

The epoch setter converts the input `epoch` to gps here: https://github.com/gwpy/gwpy/blob/ffffb8664c83e44fe349cda5d078bce0f40176f1/gwpy/types/array.py#L324

When returned, epoch is converted to astropy's Time: https://github.com/gwpy/gwpy/blob/ffffb8664c83e44fe349cda5d078bce0f40176f1/gwpy/types/array.py#L314

The issue arises when `to_gps` receives an input of the type `astropy.Time`. See the following minimal example
```python
from gwpy.time import (Time, to_gps)

t = Time(-2.3, format='gps', scale='utc')
print(to_gps(t))
```
The output is
```
-1.3
```
However, 
```python
t = Time(-2.3, format='gps', scale='utc')
print(to_gps(t.to_string()))
```
yields the correct result
```
-2.3
```

### Further notes
This is not an issue when the epoch is positive or provided in a different format (e.g., float). This is also not an issue for `TimeSeries`, as the setter does not invoke the same type conversions as `FrequencySeries`.

### Code information

This was tested on Linux/ubuntu 23.10,  GWPy version 3.0.7, python 3.11.7, ipython 8.20.0, astropy 6.0.0, numpy 1.26.3

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/1739, please join us on gitlab to continue your contribution!
