### ISSUE TITLE
Interactive plotting in notebooks

### ISSUE THREAD

**Issue by rutujagurav** [gwpy/gwpy#1741]
Matplotlib widgets let us interact with plots. When I simply plot a timeseries (see figure), the standard interactions work as expected and the plot's x-axis, which is in epoch+offset style, is adjusted appropriately. See below an example where the time resolution of ticks on x-axis went from days to hours upon selecting and zooming in on a shorter window of data as well as the epoch went from the first day of the entire timeseries to the day the zoomed-in window beings. Similarly, when I pan left/right, the timestamp in the xlabel shifts from the first day of the entire timeseries to the day the panned window begins at. 

Example TimeSeries plot:
<img width="689" alt="image" src="https://github.com/gwpy/gwpy/assets/14856287/00440ac7-1794-4c8e-85dc-7ad10462922b">

Select:
<img width="695" alt="image" src="https://github.com/gwpy/gwpy/assets/14856287/fa947527-a58f-4144-9673-ed0c3c147e2c">

Pan: 
<img width="703" alt="image" src="https://github.com/gwpy/gwpy/assets/14856287/b5f67f3f-9166-4b3e-8594-b7fe07c531be">

However,

When I add a segments plot to this timeseries plot with `.add_segments_bar()` all these action don't produce the same results for automatic x-axis adjustments anymore. See below the same example where the x-axis epoch seems to be stuck on the first day of the entire timeseries i.e. the original timeseries epoch instead of updating to the epoch to which I selected / panned.

Example TimeSeries plot with segments bar:
<img width="686" alt="image" src="https://github.com/gwpy/gwpy/assets/14856287/13fad44c-66ba-4a2e-9367-f76eb96924d6">

Select: 
<img width="694" alt="image" src="https://github.com/gwpy/gwpy/assets/14856287/fdd34274-ca12-44d6-bbb2-b6855491cafa">

Pan:
<img width="691" alt="image" src="https://github.com/gwpy/gwpy/assets/14856287/b3d059cf-3500-46a7-af2a-aa5ae5b54c74">

Why does this happen?

**Comment by duncanmmacleod** [comment]
Migrated to <https://gitlab.com/gwpy/gwpy/-/issues/1741>, please join us on gitlab to continue your contribution!
