### ISSUE TITLE
Appropriate way of reading minute-trend data stored in files

### ISSUE THREAD

**Issue by rutujagurav** [gwpy/gwpy#1742]
I am facing issues reading minute-trend data that I download and store in files locally in TimeSeries object.

When I am downloading the data using the following lines of code I get a warning message saying - 

`/gwpy/timeseries/io/nds2.py:122: UserWarning: Requested at least one minute trend, but start and stop GPS times are not multiples of 60. Times will be expanded outwards to compensate`

```
from gwpy.timeseries import TimeSeries, TimeSeriesDict
from gwpy.time import to_gps, from_gps

channels = ['L1:ISI-GND_STS_ETMX_X_BLRMS_100M_300M',
 'L1:ISI-GND_STS_ETMX_Y_BLRMS_100M_300M',
 'L1:ISI-GND_STS_ETMX_Z_BLRMS_100M_300M',
 'L1:ISI-GND_STS_ETMX_X_BLRMS_10_30',
 'L1:ISI-GND_STS_ETMX_Y_BLRMS_10_30',
 'L1:ISI-GND_STS_ETMX_Z_BLRMS_10_30',
 'L1:ISI-GND_STS_ETMX_X_BLRMS_1_3',
 'L1:ISI-GND_STS_ETMX_Y_BLRMS_1_3',
 'L1:ISI-GND_STS_ETMX_Z_BLRMS_1_3',
 'L1:ISI-GND_STS_ETMX_X_BLRMS_300M_1',
 'L1:ISI-GND_STS_ETMX_Y_BLRMS_300M_1',
 'L1:ISI-GND_STS_ETMX_Z_BLRMS_300M_1',
 'L1:ISI-GND_STS_ETMX_X_BLRMS_30M_100M',
 'L1:ISI-GND_STS_ETMX_Y_BLRMS_30M_100M',
 'L1:ISI-GND_STS_ETMX_Z_BLRMS_30M_100M',
 'L1:ISI-GND_STS_ETMX_X_BLRMS_3_10',
 'L1:ISI-GND_STS_ETMX_Y_BLRMS_3_10',
 'L1:ISI-GND_STS_ETMX_Z_BLRMS_3_10']

channels = [f"{ch}.rms,m-trend" for ch in channels]

day1_data = TimeSeriesDict.get(channels, to_gps("2019-11-10T00:00:00"), to_gps("2019-11-11T00:00:00"), verbose=True)
day2_data = TimeSeriesDict.get(channels, to_gps("2019-11-11T00:00:00"), to_gps("2019-11-12T00:00:00"), verbose=True)
day3_data = TimeSeriesDict.get(channels, to_gps("2019-11-12T00:00:00"), to_gps("2019-11-13T00:00:00"), verbose=True)

day1_data.write('test/day1_data.hdf5', format='hdf5')
day2_data.write('test/day2_data.hdf5', format='hdf5')
day3_data.write('test/day3_data.hdf5', format='hdf5')
```
But when I try to read back a subset of the downloaded data using following lines of code, it gives me the following error - 

```
filepaths = ['test/day1_data.hdf5', 'test/day2_data.hdf5', 'test/day3_data.hdf5']
data = TimeSeriesDict.read(filepaths, channels, format='hdf5', pad=0, start=to_gps("2019-11-10T12:00:00"), end=to_gps("2019-11-12T12:00:00"))
```

_ValueError: Cannot append TimeSeries that starts before this one:
    TimeSeries 1 span: [1257422399.9156716 ... 1257465599.8313432)
    TimeSeries 2 span: [1257465600.0 ... 1257551999.831343)_

What am I doing wrong? When I run the same process for second-trend I don't face this issue. 

(Side note: It would be pretty good to have the timestamps in the error messages in human-readable form)

**Comment by duncanmmacleod** [comment]
Migrated to <https://gitlab.com/gwpy/gwpy/-/issues/1742>, please join us on gitlab to continue your contribution!
