### ISSUE TITLE
Unit handling in frequencyseries.interpolate()

### ISSUE THREAD

**Issue by MaxMelching** [gwpy/gwpy#1743]
Hello,

I have noticed that the units of the output of the `frequencyseries.interpolate()` method do not match the units of its input. The output always seems to be dimensionless (at least in my tests), not matter what the input unit is.

## Minimal Example
Running
```python
test = FrequencySeries(
    [1,2,3] * u.kg,
    frequencies=[-1,0,1] * u.Hz
)

print(test.interpolate(0.5))
```
yields the following output:
```python
FrequencySeries([1. , 1.5, 2. , 2.5, 3. ]
                unit: dimensionless,
                f0: -1.0 Hz,
                df: 0.5 Hz,
                epoch: None,
                name: None,
                channel: None)
```

Everything works fine, except for the unit.

## Potential Fix
In case this is not intended (which I would assume now), it can be fixed by simply multiplying the output of `numpy.interp` with the unit, for example by changing
```python
out = type(self)(numpy.interp(fsamples, self.frequencies.value,
                                      self.value))
```
to
```python
out = type(self)(numpy.interp(fsamples, self.frequencies.value,
                                      self.value) << self.unit)
```
in [this](https://github.com/gwpy/gwpy/blob/ffffb8664c83e44fe349cda5d078bce0f40176f1/gwpy/frequencyseries/frequencyseries.py#L305) line.

I am pretty sure this should work and also that it should not have unwanted side effects.

## Further information
I am using Ubuntu 22.04, Python 3.11.5, numpy 1.26.3, astropy 6.0.0, gwpy 3.0.8

**Comment by duncanmmacleod** [comment]
Migrated to <https://gitlab.com/gwpy/gwpy/-/issues/1743>, please join us on gitlab to continue your contribution!
