### ISSUE TITLE
gwpy should prompt for segment auth, as it does for NDS auth

### ISSUE THREAD

**Issue by jrollins** [gwpy/gwpy#1744]
Some data fetch operations require gwpy to interact with segdb, which is a LIGO.ORG authenticated service.  If a cert is not available it's currently a pretty opaque failure for both new and old users.

gwpy should prompt the user to acquire a proxy cert should one be needed, similar to how gwpy currently prompts the user for kerberos credentials for NDS fetch if they are needed.

This would be a big improvement for something that is currently a time consuming failure for many people.

**Comment by duncanmmacleod** [comment]
Migrated to <https://gitlab.com/gwpy/gwpy/-/issues/1744>, please join us on gitlab to continue your contribution!
