### ISSUE TITLE
Add "si" attritute to "strain" unit?

### ISSUE THREAD

**Issue by Ceciliogq** [gwpy/gwpy#1748]
Hi  @duncanmmacleod.

The current definition of the unit "strain" is:
```
units.def_unit('strain', namespace=_ns)
```
This definition seems not to support the "si" attribute of the unit object.  I was wondering if this could be added, since it is read in LALSimulation to transform the gwpy series into lal when using the C interface for an external python model.

**Comment by duncanmmacleod** [comment]
Migrated to <https://gitlab.com/gwpy/gwpy/-/issues/1748>, please join us on gitlab to continue your contribution!
