### ISSUE TITLE
TimeSeries.fetch_open_data downloading data from tutorial error

### ISSUE THREAD

**Issue by harryyeh-astro** [gwpy/gwpy#1757]
Hi, this is my first time using this package and I was trying to go through the tutorial. Following the tutorial, I was trying to execute this: 

hdata = TimeSeries.fetch_open_data('H1', 1126259446, 1126259478)

but after a long while an error was returned: 

<urlopen error File was supposed to be 130158262 bytes but we only got 129977000 bytes. Download failed.>

Please help!

Thanks,
Harry

**Comment by duncanmmacleod** [comment]
Hi @harryyeh-astro, thanks for reaching out. The error looks like a temporary network/connection issue that happens from time to time. Do you get the same error if you try again?

Can you also describe _where_ you see the error, i.e. whether you are just trying in a console/notebook on your own laptop, or whether it's on Google CoLab or an online notebook provider?

**Comment by harryyeh-astro** [comment]
Hello @duncanmmacleod, oh yes indeed it was internet issues. In response to your question, I am running this on jupyter-lab. But now that my internet connection works well, the codes are running smoothly. Thanks a lot!

**Comment by duncanmmacleod** [comment]
Migrated to <https://gitlab.com/gwpy/gwpy/-/issues/1757>, please join us on gitlab to continue your contribution!
