### ISSUE TITLE
Using gwpy.Spectrogram.plot with an existing axis

### ISSUE THREAD

**Issue by tttiago** [gwpy/gwpy#1758]
Is it possible to plot a `gwpy.Spectrogram` using the `.plot()` method in an already existing axis? This would be useful to create figures with multiple spectrograms.

 I tried
```python
time_windows = (0.5, 1.0, 2.0, 4.0)
specsgrams = {0.5: ..., 1.0: ..., 2.0: ..., 4.0: ...)
fig, axes = plt.subplots(nrows=2, ncols=2, figsize=(10, 15))
for i, time_window in enumerate(time_windows):
   ax = axes.flatten()[i]
   specsgrams[time_window].plot(ax=ax)
```
but I get
```python
TypeError: Axes.pcolormesh() got multiple values for argument 'ax'
```

Is there any alternative which does not involve directly calling `ax.imshow()` or `ax.pcolormesh()` and writing all the boilerplate code to handle ticks, scales, etc. ?

**Comment by duncanmmacleod** [comment]
Migrated to <https://gitlab.com/gwpy/gwpy/-/issues/1758>, please join us on gitlab to continue your contribution!
