### ISSUE TITLE
Problem reading trends of channels in llhoft frames

### ISSUE THREAD

**Issue by areeda** [gwpy/gwpy#1766]
The problem was reported to me as an  ldvw issue creating [this plot](https://ldas-jobs.ligo.caltech.edu/~joseph.areeda/plots/4evan2.png)
gwpy plot produces the following error:
```
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Proxy Error for url: http://datafind.ldas.cit:80/LDR/services/data/v1/gwf/L/L1_llhoft/1402617618,1403539218/file.json
```
I have been unable to nail down where the the problem is. As far as I can tell the data requested has to cross the line where LL frames are no longer in the disk cache. I reduced it to the following snippet run at CIT (/home/joseph.areeda/python/snippets/min_trend_ll.py):
```
"""
Reading long minute trends of channels in llhoft frames seems to fail in datafind

"""
from gwpy.time import tconvert
from gwpy.timeseries import TimeSeries

now = tconvert()
start = now - 10 * 24 * 3600
end = now - 4 * 3600
chan = 'L1:CAL-PCALX_RX_PD_OUT_DQ.mean'

data = TimeSeries.get(chan, start, end, verbose=True)
print(f'{len(data)} values read')
```
To produce the plot I created a disk cache using `gw_data_find -o L -t L1_M` and changing `/ceph/mirror` to archive (another ticket going to help desk). Then passing the cache to gwpy-plot.

**Comment by duncanmmacleod** [comment]
@areeda, the failed datafind query is, I think, because you are attempting to request ~1e6 seconds of 1-second frame files, and the server is panicking when trying to return the 1e6 file paths via JSON.

However, that frame type doesn't contain any trend channels anyway, so isn't helpful in your use case.

The easiest solution is for you to pass `frametype='L1_M'` to your `TimeSeries.get` call, which will stop GWpy having to work out what dataset (frametype) to use.

Long term the `TimeSeries.get` call should be able to handle failed datafind queries and just ignore that dataset.

**Comment by areeda** [comment]
I should have put in the ldvw channel name of L1:CAL-PCALX_RX_PD_OUT_DQ.mean,m-trend which is more like 15K frames.

It will be a big change to get ldvw to discover frame types but probably not too bad if it's only for minute and second trends
Changing the get statement to:
```
chan = 'L1:CAL-PCALX_RX_PD_OUT_DQ.mean'
data = TimeSeries.get(chan, start, end, verbose=True, frame_type='L-L1_M')
```
Results in the same error:
```
requests.exceptions.HTTPError: 502 Server Error: Proxy Error for url: http://datafind.ldas.cit:80/LDR/services/data/v1/gwf/L/L1_llhoft/1402769775,1403619375/file.json
```
Do I need another parameter?

**Comment by areeda** [comment]
Oh and it is one of ldvw's bigger problems that users can ask for more than we can provide. I have no idea how to predict the limit.

**Comment by eagoetz** [comment]
@areeda Should this line be:
```python
data = TimeSeries.get(chan, start, end, verbose=True, frametype='L1_M')
```

**Comment by areeda** [comment]
That is a good question. I did try both with the same result. 
I have seen "frametype" used both ways.

**Comment by duncanmmacleod** [comment]
Migrated to <https://gitlab.com/gwpy/gwpy/-/issues/1766>.
