### ISSUE TITLE
error in lsctables.py

### ISSUE THREAD

**Issue by danhoak** [gwpy/gwpy#178]
I think this is the right way to get the SNR of omicron triggers, but it looks like there's a typo in the gwpy code:

```python
>>> events = SnglBurstTable.fetch('H1:GDS-CALIB_STRAIN','omicron',1126259461,1126259464)
>>> events.get_z()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.6/site-packages/glue/ligolw/lsctables.py", line 1308, in get_z
    return numy.asarray([row.get_z() for row in self])
NameError: global name 'numy' is not defined
```

This is on the LHO cluster, I am sourcing /home/detchar/opt/gwpysoft/etc/gwpy-user-env.sh.  Should I be sourcing a more recent version of glue?

**Comment by duncanmmacleod** [comment]
So, you have found a bug in glue, not gwpy, but that has already been fixed in development. Presumably we need to ask for a release of glue, @rpfisher is the right contact for that. 

However, the correct way to access the snr of omicron triggers is to use

```python
events.get_column('snr')
```

since that is stored directly in the `sngl_burst` table.

**Comment by danhoak** [comment]
Aha!  Thanks.  Ryan's down the hall at the moment, I'll bug him about it...:)

**Comment by rpfisher** [comment]
Yes, this is fixed on master it seems.  How urgently should I make the release?  Another group asked for a new release for another reason, but I was hesitant to request a change to any packages in the middle of the run.  I can probably convince people that this is a needed bug release either way.

**Comment by danhoak** [comment]
It's not urgent for me, no worries!

**Comment by duncanmmacleod** [comment]
@rpfisher: if the other group asked for a bug-fix release, I would encourage you to release sooner rather than later. Presumably at most the other group asked for a backwards-compatible 1.50 release, which shouldn't affect anyone presume the unit tests resolve fine.
