### ISSUE TITLE
Bug with `bartlett` window in spectrogram

### ISSUE THREAD

**Issue by paulaltin** [gwpy/gwpy#186]
There seems to be a bug when using the `bartlett` window to make a `spectrogram`. When I run the example on this page: https://gwpy.github.io/docs/v0.1/examples/spectrogram/plot.html with `method='bartlett'` (and without an `overlap` argument), it returns `TypeError: welch() got multiple values for keyword argument 'noverlap'`.

​I think this can be fixed by adding `kwargs.pop('noverlap', None)` to line 57 of spectrum/scipy_.py.

**Comment by duncanmmacleod** [comment]
@paulaltin: do you fancy setting up a PR to fix this bug, since you seem to have the problem understood?

**Comment by paulaltin** [comment]
Sure, will do.
