### ISSUE TITLE
always pops me up the authentication

### ISSUE THREAD

**Issue by orozcohsu** [gwpy/gwpy#206]
I just follow the simple test at 
https://gwpy.github.io/docs/stable/examples/timeseries/public.html

when I type 
**from gwpy.timeseries import TimeSeries**
it always prompts the authentication
The glue.auth.saml module requires the python-kerberos Python module to
be installed. On both Debian and RedHat-based systems like CentOS and
Scientific Linux the name of the package to install is 'python-kerbero

**Comment by duncanmmacleod** [comment]
@orozcohsu this is an unfortunate problem inherited by `gwpy` from the `glue` module. The error message is telling you what you need to, which is install the `python-kerberos` package. If you tell me what operating system you are using, I can try and help you install that package (if needed).

**Comment by orozcohsu** [comment]
thanks, the authentication prompts disappear because I install the packages below.
apt-get install python-dev libkrb5-dev
pip install kerberos

my os is ubuntu 14.04
