### ISSUE TITLE
TimeSeries for plot is missing the module named externals

### ISSUE THREAD

**Issue by orozcohsu** [gwpy/gwpy#207]
same as I follow the page https://gwpy.github.io/docs/stable/examples/timeseries/public.html

I do it in the jupyter

Everything is fine, I grab the data from the site, and parse the text as a list of floats, and generate a TimeSeries by supplying the necessary metadata.

but when I 
plot = ts.plot()
it failed, and message said,
ImportError: No module named externals

I am sure I have installed all required packages and moreover I also tested the 
matplotlib in the jupyter for a simple test, it is fine.

![default](https://cloud.githubusercontent.com/assets/1077656/13043423/02e848ea-d403-11e5-9a99-6e5b330625f3.JPG)

**Comment by duncanmmacleod** [comment]
@orozcohsu, what version of matplotlib do you have installed, can you post the output of

```bash
python -c "import matplotlib; print(matplotlib.__version__, matplotlib.__file__)"
```

It could be that this problem is created by updating matplotlib using pip, but not updated the axes_grid toolkit.

**Comment by orozcohsu** [comment]
@duncanmmacleod thanks,
my version is 1.3.1, axes_grid is included in matplotlib (at least from version 0.99)
![default](https://cloud.githubusercontent.com/assets/1077656/13052023/6c0c6a0c-d437-11e5-8019-e269299ad336.JPG)

**Comment by duncanmmacleod** [comment]
it looks as if you have a version of `axes_grid` that is newer than that of `matplotlib`. GWpy should be requiring `matplotlib >= 1.4.1` so should consider updating your installation to at least that level.

**Comment by orozcohsu** [comment]
@duncanmmacleod 
I reinstall all of those packages, matplotlib is 1.5.1
but the error message change to new_figure_manager_given_figure
![default](https://cloud.githubusercontent.com/assets/1077656/13118211/2fc20568-d5de-11e5-96ab-c7f07022de99.JPG)

**Comment by duncanmmacleod** [comment]
I haven't seen this error presented in this way before. Can you post the backend you are using with matplotlib?

```python
>>> import matplotlib
>>> print(matplotlib.get_backend())
```

**Comment by orozcohsu** [comment]
@duncanmmacleod 
this is the outputs for your reference, thanks

one in the console, and the other one in the jupyter

![1](https://cloud.githubusercontent.com/assets/1077656/13131223/116eb2ea-d625-11e5-8fb1-9b856b60da64.JPG)
![2](https://cloud.githubusercontent.com/assets/1077656/13131228/19966396-d625-11e5-807e-524d647aea91.JPG)

**Comment by duncanmmacleod** [comment]
aha, I haven't worked with `jupyter` before, and the `ipykernel` backend is built differently to those shipped with `matplotlib`. I'll need to take a look at the code and work out a patch. Thanks for bringing this up!

**Comment by orozcohsu** [comment]
I change to ipykernel, but it is still the same error message.

Could you post step by step (especially the package name and  version) how to install it?
Thanks a lot.

**Comment by duncanmmacleod** [comment]
@orozcohsu, the problem is that the `ipykernel` backend used by `jupyter` in your setup is build slightly differently to those backends in regular `matplotlib`. I need to patch `gwpy` to work for this specific case. Can you confirm that you don't see this problem using the standard `python` interpreter, or basic `ipython`?
