### ISSUE TITLE
read() method doesn't handle frame metadata for class that inherits `TimeSeries`

### ISSUE THREAD

**Issue by pmeyers279** [gwpy/gwpy#241]
When I try to create a new class that inherits the TimeSeries class I can use the `read` function on a frame, but the metadata does not carry over.

i.e. if I define a class like this:
```python
from gwpy.timeseries import TimeSeries
class Trace(TimeSeries):
    def mymethod():
        pass
```
then data read in with `Trace` class is the same as that with the `TimeSeries` class, but metadata like `channel`, `epoch`, `name`, and `sample_rate` do not get defined (whereas they do get defined in the `TimeSeries.read()` case).

**Comment by duncanmmacleod** [comment]
this was resolved by #294.
