### ISSUE TITLE
series object "append" loses precision when setting dx

### ISSUE THREAD

**Issue by cpankow** [gwpy/gwpy#257]
In coalescing a `TimeSeriesList`, I've noticed that the `dx` returned after the first `append` is slightly different than the original, causing subtle floating point errors (e.g.):

```
ValueError: TimeSeries sample sizes do not match: 0.000999927520752 s vs 0.001 s.
```

This is caused by a loss of precision in `seres.py:append()` on line 509 where the new dx is calculated. It is correct before it is recalculated.

Two questions:
1. Why does the dx get recalculated?
2. Can the dx be determined without loss of precision.

Assuming (1) has a reason, I'll look into (2).

I should note that the reason that precision is lost is xindex are gps values with a large number of significant digits:

```
(Pdb) self.xindex[1] - self.xindex[0]
<Quantity 0.0009999275207519531 s>
(Pdb) p self.xindex[1], self.xindex[0]
(<Quantity 1142726468.001 s>, <Quantity 1142726468.0 s>)
```

**Comment by duncanmmacleod** [comment]
@cpankow, can you attach a standalone snippet to that reproduces the problem?

**Comment by duncanmmacleod** [comment]
@cpankow, this is now over a year old, with no updates, so I will close, please re-open if this is still an issue.
