### ISSUE TITLE
Required features for Q-transform

### ISSUE THREAD

**Issue by duncanmmacleod** [gwpy/gwpy#258]
Summary
-------------
This issue serves as an evolving list of features required to improve the `TimeSeries.q_transform` function.

Currently the function allows the user to specify the following parameters for the Q transform itself:

- `qrange` - minimum and maximum Q
- `frange` - minimum and maximum frequency

which is certainly a bit restrictive. Please post comments below and I will attempt to capture them here:

@andrew-lundgren, @jlmciver, @scottcoughlin2014, @lauranuttall, etc, please comment.

Requested features
------------------

| Feature | Possible solution |
| --- | --- |
| custom whitening | add an `asd` kwarg that allows the user to supply their own spectrum against which to whiten |
| provide simple function to transform single (q, f) tile | |

**Comment by andrew-lundgren** [comment]
My requirements may be a little idiosyncratic. I'm coming at it from the perspective of trying to improve the Omega scan algorithm itself. Mostly, I'd like the code to be a little more modular, and allow testing of the different parts. I think q_transform should be a wrapper of the following modular pieces:

1. Condition the data (do the whitening and Fourier transform). It would be very helpful to be able to specify an asd.
2. Generate the tiling. This is already nicely encapsulated as QTiling.
3. Do a Q transform for a single time, and return the full output (the timeseries including phase).
4. Do all the Q transforms, and downselect the result.
5. Make the standard Omega plot.

I'll try to do some of this myself and make a pull request.

**Comment by duncanmmacleod** [comment]
@andrew-lundgren, I'll respond to each point in turn

1. I'm happy to allow a custom ASD, and calculating the FFT is trivial from there

2. done
3. do you mean for a single Q and frequency? this is already in the feature list, and can be tuned to return the complex output of the ifft, not the normalised energy

4. that's what we have now, so...done

5. this is left to the standard `Spectrogram.plot` routines, although we might want something custom to make interpolated images that people are more used to (and are faster, at the expensive of native log support)
