### ISSUE TITLE
TimeSeries.filter shouldn't accept scipy.signal.lti

### ISSUE THREAD

**Issue by e-q** [gwpy/gwpy#279]
The `scipy.signal.lti` class is really only meant to represent continuous-time systems in the s-plane (i.e. laplace domain), whereas parameters for discrete time filtering, as is performed in `lfilter` and `sosfilt`, are specified in the z-plane. 

In practice the class it is often just used as a container for the numerator and denominator of the filter in TF representation, and if z-plane coefficients were used as the input, it'll still work, but one could easily run into the case of using inappropriate conversion functions or something like that, since all of the class methods are written with continuous time systems in mind.

A discrete time class is in the works, and will hopefully land with scipy v0.18.

**Comment by duncanmmacleod** [comment]
@e-q, sounds reasonable, if you want to write up a PR that removes the support for that object in `TimeSeries.filter` (and likely `FrequencySeries.filter` as well), I'll gladly take a look.

**Comment by duncanmmacleod** [comment]
this code has been refactored, so this is not an issue any more
