### ISSUE TITLE
install breaks MacTex / Tex Live

### ISSUE THREAD

**Issue by rxa254** [gwpy/gwpy#282]
The Macports install of texlive stuff breaks the texlive install done by downloading MacTex from tug.org :(
- Rana

**Comment by duncanmmacleod** [comment]
@rxa254, you don't have to use macports to use gwpy, you can probably install of the dependencies using homebrew if you like. Either way this is not really a bug in gwpy, I encourage you to file a bug report with either MacTex or the texlive port maintainers.
