### ISSUE TITLE
Documentation for generating a frame cache doesn't match the required args

### ISSUE THREAD

**Issue by tjma12** [gwpy/gwpy#297]
The documentation details the `find_frame_urls` method for generating a frame cache. The frametype argument is listed as requiring a single character frame type (for example, 'R'). The method itself requires the full frame type ('H1_R').

Using a single character returns missing frames:
```
cache = connection.find_frame_urls('H','R',1135166384,1135166384+1000,urltype='file')
Missing segments: 
[1135166384 ... 1135167384)
```

Using the full frame type, 'H1_R', returns the expected frames:

```
cache = connection.find_frame_urls('H','H1_R',1135166384,1135166384+1000,urltype='file')

for ce in cache:
    print(ce)
     
H H1_R 1135166336 64 file://localhost/hdfs/frames/O1/raw/H1/H-H1_R-11351/H-H1_R-1135166336-64.gwf
```

**Comment by duncanmmacleod** [comment]
turns out this documentation was removed in at v0.1.
