### ISSUE TITLE
resample() phase shift

### ISSUE THREAD

**Issue by RoyWilliams** [gwpy/gwpy#301]
Duncan
The method
    gwpy.timeseries.StateVector.resample
would be better if it ensured zero-phase shift between input and output.
Roy

**Comment by duncanmmacleod** [comment]
@RoyWilliams, the `StateVector.resample` method includes no filtering and so has no potential phase issues. 

Presumably you mean the `TimeSeries.resample` method? In which case the latest version includes a `filtfilt` keyword argument that can be used to ensure zero-phase filtering. I can definitely do one of two things

- make `filtfilt=True` the default
- improve the documentation for the method to declare that zero-phase filtering can be enabled by setting `filtfilt=True` manually

**Comment by duncanmmacleod** [comment]
With no response to my query, I will close this issue. I'm happy for it to be reopened at a later date.
