### ISSUE TITLE
Time series fetch seems to have trouble with with odd prefixes

### ISSUE THREAD

**Issue by areeda** [gwpy/gwpy#31]
The following code snippet fails with the latest pull from dev, it did work in previous versions:
```python
from gwpy.timeseries import TimeSeries
chan = 'LVE-EX:X3_810BTORR.mean,m-trend'
dur = 36000
start = 1072539420
data = TimeSeries.fetch(chan, start, start+dur, verbose=True)

produces the error:
```AttributeError: 'Channel' object has no attribute '_ifo' ```

This is one of the examples in gwpy-plot documentation.  The plot from a previous version looks like: 

https://ligodv.areeda.com/gwpy/cli_examples/cli-ts-02.png

**Comment by duncanmmacleod** [comment]
This is related to the parsing of channel names in the `Channel` class. The code assumes that the IFO prefix is a single upper-case character and a single integer, e.g. `'X1'`. I can modify the parsing to accept this alternative, old format.

**Comment by areeda** [comment]
Just to be pedantic, some of these "ifo" values are old but many are current.  For example John Worden plots HVE* and LVE* channels regularly during pump downs.
