### ISSUE TITLE
Default TimeSeries.get operation refuses tape from NDS2

### ISSUE THREAD

**Issue by duncanmmacleod** [gwpy/gwpy#317]
The `TimeSeries.get` operation by default doesn't allow access from tape, even if that is the only option. The idea is that if the local data are on tape the `find` call will fail, so the `fetch` method will get invoked, but if the NDS2 server doesn't want to read tape, then that fails as well, despite the data actually being available.

The solution would be to set the `NDS2_CLIENT_ALLOW_DATA_ON_TAPE` environment variable if the `find` call fails, so that something is returned, but I'm not sure whether that needs to be done before the `nds2` module is imported for the first time.

**Comment by duncanmmacleod** [comment]
this was fixed by a recent release (I can't remember which one)

**Comment by brettlv** [comment]
when i try the example 

from gwpy.timeseries import TimeSeries
white = TimeSeries.get(
    'L1:OAF-CAL_DARM_DQ', 'March 2 2015 12:00', 'March 2 2015 12:30')
to get data , i got this result,however i,m not sure what is the matter with nds2

/Users/brettlv/anaconda3/lib/python3.6/site-packages/gwpy/io/nds2.py in auth_connect(host, port)
    296     """
    297     if not HAS_NDS2:
--> 298         raise ImportError("No module named nds2")
    299 
    300     # set default port for NDS1 connections (required, I think)

ImportError: No module named nds2

**Comment by duncanmmacleod** [comment]
@brettlv, how did you install the nds2 client? Can you run

```python
>>> import nds2
>>> print(nds2.__file__)
```

from an independent python session? Or this (from the shell, not python):

```bash
$ nds-client-config --py27dir
```

and post the results?

**Comment by brettlv** [comment]
alright, i found i have not installed the non-python extras yet.
but i have another question that i am used to anaconda3 jupyter notebook  in mac, and python3, and i would not like to come back to use python2,

After installation you will need to make the MacPorts python the active version, so the appropriate modules can be found, by running:
sudo port select --set python python27

I,m not sure that whether the  python version  would have to be changed or whether the gwpy  function well, so is the gwpy fully based on python27？

**Comment by brettlv** [comment]
i have install nds2 by
sudo port install nds2-client
the version of nds2-client is 0.14.2

but when i try:
import nds2

no module name "nds2"

**Comment by duncanmmacleod** [comment]
@brettlv, the python bindings of the NDS2 client were separated into their own port, so you need to install the `pyXY-nds2-client` port for your relevant X.Y version of python, e.g.

```bash
sudo port install py27-nds2-client
```

Please post here if that doesn't resolve the issue.
