### ISSUE TITLE
Method to nicely measure transfer function from two TimeSeries

### ISSUE THREAD

**Issue by andrew-lundgren** [gwpy/gwpy#321]
This is a feature request to add a method similar to `TimeSeries.coherence` that would measure a transfer function from one time series to another.

The usual method to reduce noise is like the Welch method, breaking the data into shorter chunks, measuring the transfer function of each chunk, and averaging together. The LIGO seismic group prefers another method called ASD2 or the Hua method. Just take the transfer function of the whole set of data, then average over bins to reduce noise and make the resolution more reasonable.

See the seismic alog entry https://alog.ligo-la.caltech.edu/SEI/index.php?callRep=111 and also search for 'ASD2' for other entries.

I have some code that does this, I'll try to find it and put it in a form that it can be merged in.

**Comment by duncanmmacleod** [comment]
No response, closing.

**Comment by eagoetz** [comment]
@duncanmmacleod I might be able to help on this, if you are interested. I'd be keen to have this feature as part of gwpy. 

It should be something like:
```
csdData = ch1.csd(ch2, fftlength=<>, overlap=<>, window='hann')
ch1psd = ch1.psd(fftlength=<>, overlap=<>, window='hann')
ch2psd = ch2.psd(fftlength=<>, overlap=<>, window='hann')
txfr = csdData / ch2psd
```
If you want, I could submit some actual code via a merge request
