### ISSUE TITLE
Installation on OS X requires two extra packages for frame reading [docs]

### ISSUE THREAD

**Issue by pmeyers279** [gwpy/gwpy#332]
The docs for install GWpy on OS X don't appear to complete if you want to read `.gwf` frames.

To get frame reading to work properly for GWpy on OS X I also had to run 

`port install py27-lal py27-lalframe`

and then make sure to add these explicitly to my python path in the case where I was working in a virtualenv. 

This was in addition to the rest of the current OS X installation instructions documented [here](https://gwpy.github.io/docs/stable/install.html).

**Comment by duncanmmacleod** [comment]
Thanks @pmeyers279, the docs are outdated referencing the old `lal` and `lalframe` ports, rather than the new `py27-lal` versions.
