### ISSUE TITLE
GWpy plots are clipping on the edges after trimming whitespace

### ISSUE THREAD

**Issue by jrsmith02** [gwpy/gwpy#340]
We have noticed (primarily using the ligoDV-web interface) that after a recent update to trim whitespace, often the x- and y-axis labels are clipping their text (i.e. they do not have enough space to show the text). Here are some examples: 
spectrum: https://ldvw.ligo.caltech.edu/ldvw/view?act=getImg&imgId=151618
spectrogram (maybe very slightly clipped at bottom): https://ldvw.ligo.caltech.edu/ldvw/view?act=getImg&imgId=151627 
I think this may be exacerbated because the plots were tuned for the summary pages, where the labels are given as inline fractions m/\sqrt{Hz} but ligoDV-web is requesting labels using stacked fractions such as \frac{m}{\sqrt{Hz}}. So a possible solution could be either Joe and Duncan should agree to use inline labels, or more white space should be added back.

**Comment by duncanmmacleod** [comment]
this should have been resolved by #429
