### ISSUE TITLE
The order of plot lines and legend items is not the order given by the user

### ISSUE THREAD

**Issue by jrsmith02** [gwpy/gwpy#341]
Using GWpy plots in the ligoDV-web interface I cannot specify the order that items should appear in the legend or the plot itself currently. I would like them to appear in the order I enter them. First entered gets plotted first and is first in the legend. Then in order after that. The attached screenshot shows that the order specified by me was sent to GWpy in the command but the plot came out with a different order (not chronological either). 
![ldvw-spectrum-order](https://cloud.githubusercontent.com/assets/7536082/21904247/d67b948c-d8b7-11e6-9299-4fe8355566f0.png)

**Comment by duncanmmacleod** [comment]
@jrsmith02, the command at the bottom of the screenshot you linked references a different channel than is shown in the figure, can you post a `gwpy-plot` command that clearly shows the poor ordering?

**Comment by jrsmith02** [comment]
@duncanmmacleod I *think* if you just replace the MICH channel in that command with H1:GDS-CALIB_STRAIN that should work. But I've created a fresh one for you here. This should illustrate that the order in the plot has nothing to do with the ordering sent to gwpy, it's randomly different. 
<img width="1228" alt="screen shot 2017-01-31 at 4 42 48 pm" src="https://cloud.githubusercontent.com/assets/7536082/22490868/90adb864-e7d4-11e6-8a29-7d4a02af2790.png">
@areeda

**Comment by duncanmmacleod** [comment]
@jrsmith02, thanks for this, I can reproduce the plot with the essentially random ordering of spectra, and will work up a fix
