### ISSUE TITLE
plot axis labels/digits of precision

### ISSUE THREAD

**Issue by areeda** [gwpy/gwpy#343]
Example: https://ldvw.ligo.caltech.edu/ldvw/view?act=getImg&imgId=152122

A 5-min Spectrogram with 13 significant digits on x axis label

**Comment by duncanmmacleod** [comment]
@areeda, can you post the `gwpy-plot` command used to generate that image, if you have it handy?

**Comment by areeda** [comment]
/usr/local/ldvw/bin/gwpy-plot spectrogram --chan 'C1:PEM-SEIS_BS_Z_OUT_DQ' --start 1168585216 --duration 300 --out '/var/cache/tomcat/temp/ldvw804514862420256954.png' --secpfft '16.000'

that should do it.

**Comment by duncanmmacleod** [comment]
This should have been fixed in #522, @areeda, please confirm.
