### ISSUE TITLE
Trouble creating Bode plots from concatenated SOSs

### ISSUE THREAD

**Issue by areeda** [gwpy/gwpy#344]
The notebook at https://git.ligo.org/joseph-areeda/FilterDesignPOC/blob/master/FilterWorkbench.ipynb demonstrates the problem.  The Bode plot attempt is at the vry end

The rest of it defines various filters an concatenates them.

The error message is "ValueError: freqresp() requires a SISO (single input, single output) system."

**Comment by duncanmmacleod** [comment]
@areeda, please post the full traceback for the `ValueError`.
