### ISSUE TITLE
Clearer documentation of where the write functions for the TimeSeries class are defined

### ISSUE THREAD

**Issue by rpfisher** [gwpy/gwpy#360]
Could a bit more documentation please be added inside the timeseries.py file to indicate where the TimeSeries.write methods exist in the code tree?

I believe the right place might be in the docstring for the write method, here:

https://github.com/gwpy/gwpy/blob/master/gwpy/timeseries/timeseries.py#L166

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/360, please join us on gitlab to continue your contribution!
