### ISSUE TITLE
NDS2 server selection doesn't work for LVE-EX-style channels

### ISSUE THREAD

**Issue by duncanmmacleod** [gwpy/gwpy#39]
Each of the LIGO sites uses a number of channels such as `LVE-EX:X3_810BTORR` for monitoring the vacuum system. Since the prefix `LVE-EX` doesn't parse as a proper IFO prefix, the default NDS2 server is selected as that at CIT.

While the prefix doesn't identify the IFO, it does identify the site, since they are either e.g. `LVE-EX` or `HVE-EX`, for LLO and LHO respectively.

The NDS2 server selection algorithm should be able to select a server for these channels as well.

**Comment by duncanmmacleod** [comment]
We might want to add a `site` property to the `Channel` object, giving the interferometer-independent observatory ID, probably just a single upper-case character. E.g.:

```python
>>> test = Channel('L1:LDAS-STRAIN')
>>> print(test.ifo, test.site)
('L1', 'L')
>>> test2 = Channel('LVE-EX:X3_810BTORR')
>>> print(test2.ifo, test2.site)
(None, 'L')
```
We would then need to modify the NDS2 server selection algorithm to operator using the site prefix, not the IFO.

**Comment by areeda** [comment]
The complete list of channel prefixes from the ldvw database is:

C1
G1
H0
H1
H2
H3
HVE-EX
HVE-EY
HVE-LX
HVE-LY
HVE-MR
HVE-MX
HVE-MY
L0
L1
LVE-BX
LVE-BY
LVE-EX
LVE-EY
LVE-LX
LVE-LY
LVE-MR
LVE-MX
LVE-MY
V1

**Comment by areeda** [comment]
Another thing we **might** want to consider in selecting a server is the secondary nds2 servers available at LLO and CIT and hopefully soon at LHO.  nds.ligo is the primarey while ldas-pcdev1 is also an NDS2 server that should have access to all the same data.

In the rare case the primary server is down and the secondary server is up we can find data rather than give an error.

**Comment by duncanmmacleod** [comment]
This hasn't been touched in a while, so I'll close and people can reopen if this is still an issue at a later time.
