### ISSUE TITLE
gwpy-plot can't display simple GPS times on time axis

### ISSUE THREAD

**Issue by duncanmmacleod** [gwpy/gwpy#41]
The `gwpy-plot` command-line interface doesn't expose any time-axis scale options to the user, meaning they can't choose between the (default) human-readable 'Time (some unit) from epoch', and just displaying the GPS times.

I'm not sure if GWpy can actually display just GPS times, without matplotlib imposing an offset, but this should be workable pretty quickly.

**Comment by duncanmmacleod** [comment]
The GWpy plotter allows for showing raw GPS numbers, as follows:

```python
ax.set_xscale('gps')
ax.set_epoch(0)
```

The first will display raw GPS times from some epoch, while the second will reset the epoch back to GPS time 0.

I think the only thing for this issue is the expose this to the user of `gwpy-plot` somehow, and then onto the LDVW interface. @areeda, can you take this on?

**Comment by areeda** [comment]
I believe that is what gwpy-plot is doing now.  See https://ligodv.areeda.com/ldvw/view?act=getImg&imgId=47978

If I understood Tom Dent's comment he wants both Δt and GPS time on the axis the way the older Spectrograms did it.  IE 2 x-axis labels, See https://ligodv.areeda.com/ldvw/view?act=getImg&imgId=47977.

Is that possible?  If so how do we specify another row of labels?
If that's not what you understood, let's clarify with Tom.

**Comment by duncanmmacleod** [comment]
I'm confused, the plot you linked has human-readable time scaling, i.e. time in some unit from the epoch. I was asking if you could implement a user option to display raw GPS times?

However, I think Tom was probably asking for both, like the second image you have linked. I will have a think about how to achieve this.

**Comment by areeda** [comment]
I'm sorry, you did say set the epoch to zero.  We already have a way to set epoch to either a GPS time or as an offset to the start.  I can easily make 0 mean absolute GPS time.

I'll do that, and expand the description of the field.

**Comment by areeda** [comment]
I have added these changes to gwpy-plot and ldvw.  So setting the epoch (called x-axis zero in ldvw) to 0 displays gps times
