### ISSUE TITLE
TimeSeries with float arrays

### ISSUE THREAD

**Issue by mcoughlin** [gwpy/gwpy#413]
When I pass a floating point array to gwpy.timeseries.TimeSeries, I seem to get an int array back:

```python
dataLowpass = gwpy.timeseries.TimeSeries(np.array(lowpassdata).astype(float), unit=dataFull.unit, sample_rate = 1/dataFull.dx.value, epoch = dataFull.epoch, dtype=float)

print np.array(dataLowpass.data).astype(float)
print np.array(lowpassdata).astype(float)
```

gives:

```
[ 221.   12.  198. ...,   75.   87.   64.]
[ 95.8642189   95.8642189   95.8642189  ...,  93.18118333
  93.18118333  93.18118333]
```

So a conversion seems to be happening in gwpy.timeseries.TimeSeries. Am I passing the wrong args?

**Comment by duncanmmacleod** [comment]
@mcoughlin, the [`.data`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.data.html#numpy.ndarray.data) attribute is a pointer to a memory location, and does not contain the actual [`value`](https://gwpy.github.io/docs/stable/timeseries/index.html#gwpy.timeseries.TimeSeries.value) of the array. Please modify your code to use `dataLowpass.value` and not `dataLowpass.data`, and confirm whether an issue is still present.

**Comment by mcoughlin** [comment]
Ok perfect!
