### ISSUE TITLE
whitening options for Q-scans

### ISSUE THREAD

**Issue by astroclark** [gwpy/gwpy#414]
It would be useful to be able to pass in a specific ASD or GPS time to use for whitening data in q-transforms (e.g., if one is trying to compare q-scans for a loud signal, which easily corrupts the PSD estimation, against its residuals).

Much of the desired behaviour could presumably (?) be achieved by adding to, or replacing, the psdkwargs with a whitenkwargs.

**Comment by duncanmmacleod** [comment]
this was fixed by #471 and will be packaged with the next release
