### ISSUE TITLE
TimeSeries.fetch() broken for minute trends on nds2 v. 13.2

### ISSUE THREAD

**Issue by stefco** [gwpy/gwpy#417]
`TimeSeries.fetch` and related `fetch` methods fail for minute trend data on the latest version of NDS2 (13.2), which is installed on the ldas servers. The problem does not appear on e.g. NDS2 v. 12.2 and is the result of a change in SWIG bindings for iteratively fetching data in NDS2. 

When fetching trend data, at line 912 of /gwpy/timeseries/core.py, `nds2.connection.iterate` gets called with `gps_start`, `gps_end`, and the `channel_name`. This was acceptable in NDS2 12.2 because the swig bindings were overloaded to handle `iterate` calls with 3 arguments. But in the latest NDS2 swig bindings, the user **must** supply exactly 4 arguments. Mor specifically, the user must provide a stride value (i.e. number of seconds to fetch at once) as the third argument to `connection.iterate`. Since the current `TimeSeries.fetch` method still uses the 3 argument binding of NDS2's `connection.iterate`, an error get's raised every time you try to fetch trend data on a system with NDS2 v. 13.2.

(I don't know why the problem only happens for trend data and not for full data; I suspect that `connection.fetch` is used for non-trend data, which would avoid the change in arity, but I don't know why that is.)

Unfortunately, I don't have time to fix this myself. But it seems that a simple fix would be to find all instances of `connection.iterate` and include a default stride value (or maybe a dynamically calculated one; I don't know if lower bitrate channels can be fetched in larger chunks of time, but if so, that would be useful to take advantage of).

**Comment by duncanmmacleod** [comment]
@stefco, can you post an example of the call and the failure as presented by python? Your explanation is complete, the only thing missing is the code to reproduce the error.

**Comment by duncanmmacleod** [comment]
@stefo, I'm having troubling reproducing this problem. On `ldas-pcdev4.ligo.caltech.edu` I see NDS2 version 0.13.2 and can use `TimeSeries.fetch` without any issues:

```bash
$ nds-client-config --version
0.13.2
$ python -c "from gwpy.timeseries import TimeSeries; print(TimeSeries.fetch('L1:IMC-PWR_IN_OUT_DQ.mean,m-trend', 1175212800, 1175213400, verbose=True))"
Connecting to nds.ldas.cit:31200... Connected.
Success.ing data... 50%
TimeSeries([ 25.41812151, 25.41708955, 25.41630342, 25.4144342 ,
             25.41449893, 25.41244411, 25.41276263, 25.41382498,
             25.41362385, 25.41355494]
           unit: Unit(dimensionless),
           t0: 1175212800.0 s,
           dt: 60.0 s,
           name: L1:IMC-PWR_IN_OUT_DQ.mean,
           channel: L1:IMC-PWR_IN_OUT_DQ.mean)
```

**Comment by stefco** [comment]
@duncanmmacleod Thanks for checking on this. I investigated a bit further and found that this strangely only happens on NDS2 v. 13.2 and it *only happens when the channel name is a unicode string!* Imagine that. From `ldas-pcdev2.ligo.caltech.edu`:

```bash
 ldas-pcdev2  ~/slow-channel-scratch/PPSOFFSET  >  python -c 'import gwpy.timeseries; print gwpy.timeseries.TimeSeries.fetch("L1:SYS-TIMING_C_GPS_A_PPSOFFSET.max,m-trend", 1172275200, 1172361600, verbose=True)'
Connecting to nds.ldas.cit:31200... Connected.
Success.ing data... 50%
TimeSeries([ 11.84124184, 11.53732967,  9.6450882 ,...,
             83.35564423, 16.49843407, 11.77472496]
           unit: Unit(dimensionless),
           t0: 1172275200.0 s,
           dt: 60.0 s,
           name: L1:SYS-TIMING_C_GPS_A_PPSOFFSET.max,
           channel: L1:SYS-TIMING_C_GPS_A_PPSOFFSET.max)
 ldas-pcdev2  ~/slow-channel-scratch/PPSOFFSET  >  python -c 'import gwpy.timeseries; print gwpy.timeseries.TimeSeries.fetch(u"L1:SYS-TIMING_C_GPS_A_PPSOFFSET.max,m-trend", 1172275200, 1172361600, verbose=True)'
Connecting to nds.ldas.cit:31200... Connected.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/utils/deps.py", line 84, in wrapper
    return func(*args, **kwargs)
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/timeseries/core.py", line 279, in fetch
    allow_tape=allow_tape, type=type, dtype=dtype)[str(channel)]
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/utils/deps.py", line 84, in wrapper
    return func(*args, **kwargs)
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/timeseries/core.py", line 802, in fetch
    allow_tape=allow_tape)
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/utils/deps.py", line 84, in wrapper
    return func(*args, **kwargs)
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/timeseries/core.py", line 913, in fetch
    [c.ndsname for c in qchannels])
TypeError: in method 'connection_iterate', argument 4 of type 'connection::channel_names_type const &'
```

I had previously had no trouble with unicode channel names (I like JSON config files), so I didn't think to explicitly convert anything. I still don't know why it would fail in this way, but fortunately this is an easy fix in my code.

Thanks!
