### ISSUE TITLE
`TimeSeries.crop()` sometimes catches the sample before the time that is supplied

### ISSUE THREAD

**Issue by pmeyers279** [gwpy/gwpy#450]
I am trying to crop several `TimeSeries` objects for different channels to the start and end times of a given day and then fill them into a `TimeSeriesDict` (which will then be written to a frame). 

The times passed to `crop` for each of these, when printed, are the same for each `TimeSeries` object. However, the resulting cropped `TimeSeries` sometimes starts the sample before I want it to (see output at the bottom).

If I had to guess, then I'd say this has to do with the `gwpy.types.series.Series` `crop` method using `int((start - self.xspan[0])/self.dx)` which will truncate to a lower index if the division lands just below an integer number of samples. Perhaps something like `int(round((start - self.xspan[0])/self.dx))` would be more appropriate? (Then again, if you gave a time that doesn't fall at the same time as a sample, then maybe you'd prefer to include the extra sample...I don't know)

Example of resultant `TimeSeriesDict` is below. This comes from a relatively hefty workflow but i'll try to get a smaller working example if you'd like. For the sake of completeness, it's probably worth mentioning that the `TimeSeries` objects that are cropped are of varying sizes when I crop them.

```
TimeSeriesDict([('C4850:HHZ', <TimeSeries([1629,1637,1636,..., 1825,1821,1817]
            unit=Unit(dimensionless),
            t0=<Quantity 1111104015.99 s>,
            dt=<Quantity 0.01 s>,
            name=None,
            channel=<Channel("C4850:HHZ", None) at 0x7f1214a42d50>)>), ('C4850:HHE', <TimeSeries([654,654,651,..., 488,478,487]
            unit=Unit(dimensionless),
            t0=<Quantity 1111104015.99 s>,
            dt=<Quantity 0.01 s>,
            name=None,
            channel=<Channel("C4850:HHE", None) at 0x7f1224b3fa90>)>), ('C4850:HHN', <TimeSeries([344,346,351,..., 358,363,355]
            unit=Unit(dimensionless),
            t0=<Quantity 1111104015.99 s>,
            dt=<Quantity 0.01 s>,
            name=None,
            channel=<Channel("C4850:HHN", None) at 0x7f1214a58490>)>), ('B4850:HHZ', <TimeSeries([1131,1249,1167,..., 1323,1216,1345]
            unit=Unit(dimensionless),
            t0=<Quantity 1111104016.0 s>,
            dt=<Quantity 0.01 s>,
            name=None,
            channel=<Channel("B4850:HHZ", None) at 0x7f1214a58b90>)>), ('B4850:HHE', <TimeSeries([545,553,542,..., 336,325,336]
            unit=Unit(dimensionless),
            t0=<Quantity 1111104016.0 s>,
            dt=<Quantity 0.01 s>,
            name=None,
            channel=<Channel("B4850:HHE", None) at 0x7f1214a58610>)>), ('B4850:HHN', <TimeSeries([318,803,619,..., 605,196,398]
            unit=Unit(dimensionless),
            t0=<Quantity 1111104015.99 s>,
            dt=<Quantity 0.01 s>,
            name=None,
            channel=<Channel("B4850:HHN", None) at 0x7f1214a58a10>)>)])
```

**Comment by duncanmmacleod** [comment]
@pmeyers279, apologies for the delay in getting to this. Do you have any code that I can use a minimal example that reproduces the bug?

**Comment by pmeyers279** [comment]
Here's a smaller example with version `0.8.1`

```python
In [1]: import gwpy

In [2]: print gwpy.__version__
0.8.1

In [3]: from gwpy.timeseries import TimeSeries

In [4]: import numpy as np

In [5]: data = TimeSeries(np.arange(10), times=np.arange(10))

In [6]: print data
TimeSeries([0,1,2,3,4,5,6,7,8,9]
           unit: Unit(dimensionless),
           t0: 0.0 s,
           dt: 1.0 s,
           name: None,
           channel: None)

In [7]: cropped_data = data.crop(2.9, 5.1) # would probably expect 3,4,5

In [8]: print cropped_data
TimeSeries([2,3,4]
           unit: Unit(dimensionless),
           t0: 2.0 s,
           dt: 1.0 s,
           name: None,
           channel: None)
```

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/450, please join us on gitlab to continue your contribution!
