### ISSUE TITLE
pip install failed in windows

### ISSUE THREAD

**Issue by PeterSpiegler** [gwpy/gwpy#569]
I can not install gwpy on Windows 7x64, because the installation of lscsoft-glue failed with:   

glue/ligolw/tokenizer.Tokenizer.c(579): error C2057: expected constant expression  
glue/ligolw/tokenizer.Tokenizer.c(579): error C2466: cannot allocate an array of constant size 0  
glue/ligolw/tokenizer.Tokenizer.c(579): error C2133: 'ascii_buffer': unknown size  
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.11.25503\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

The problem in tokenizer.Tokenizer.c(579) is the code:  
`		char ascii_buffer[end - start + 1];  
`
The compiler  need a constant array size.
Is there a workaround?

**Comment by duncanmmacleod** [comment]
@PeterSpiegler, I don't think any attempt has ever been made to make `lscsoft-glue` run under Windows, and that's currently a blocker to having Windows support for GWpy. You can download the tarball for `lscsoft-glue` from pypi [here](https://pypi.python.org/pypi/lscsoft-glue/) - if you happen to find a workaround, please let me know.

**Comment by PeterSpiegler** [comment]
I could compile it.
The errors
glue/ligolw/ilwd.c(301): error C2057: expected constant expression
glue/ligolw/tokenizer.Tokenizer.c(579): error C2057: expected constant expression
src/segments/segment.c(458): error C2099: initializer is not a constant
can resolved by malloc() and free().

The source of the errors
src/segments/segment.c(458): error C2099: initializer is not a constant
src/segments/segmentlist.c(1384): error C2099: initializer is not a constant
is .tp_base = &PyList_Type   or .tp_base = &PyTuple_Type, 
I dont know how to convert to a constant expression, so I commentet it out. Then the default base type is &PyBaseObject_Type.

The source of error
src/segments/segmentlist.c(199): error C2059: syntax error: '<parameter-list>'
src/segments/segmentlist.c(218): error C2059: syntax error: '<parameter-list>'

are the window macros min & max, which must undefined by 
#undef min  // see http://www.suodenjoki.dk/us/archive/2010/min-max.htm
#undef max


[segmentlist.c.txt](https://github.com/gwpy/gwpy/files/1479751/segmentlist.c.txt)
[segment.c.txt](https://github.com/gwpy/gwpy/files/1479752/segment.c.txt)
[tokenizer.Tokenizer.c.txt](https://github.com/gwpy/gwpy/files/1479754/tokenizer.Tokenizer.c.txt)
[ilwd.c.txt](https://github.com/gwpy/gwpy/files/1479755/ilwd.c.txt)

**Comment by PeterSpiegler** [comment]
The initialization of .tp_base is necessary. Otherwise python crashed. 
I initialized it in PyMODINIT_FUNC PyInit___segments(void) in 
```
	if(!segments_Segment_Type.tp_base) 
		segments_Segment_Type.tp_base = &PyTuple_Type; 
	if(!segments_SegmentList_Type.tp_base) 
		segments_SegmentList_Type.tp_base = &PyList_Type;	 
```
[segments.c.txt](https://github.com/gwpy/gwpy/files/1481820/segments.c.txt)

**Comment by duncanmmacleod** [comment]
@PeterSpiegler, thanks so much for taking the time to carefully test these mods, I'll pass them on to the relevant developers and hopefully we can get something Windows-compliant in the future!
