### ISSUE TITLE
gwpy-plot cli_examples don't link correctly to documentation

### ISSUE THREAD

**Issue by duncanmmacleod** [gwpy/gwpy#58]
The `cli_examples/` directory generated during `make html` doesn't link properly to the finished HTML.

**Comment by areeda** [comment]
I'm don't see the problem.  Pages like https://gwpy.github.io/docs/stable/cli/index.html look correct to me.

Please add an example so I can dig into it.
Joe

**Comment by duncanmmacleod** [comment]
The docs on gwpy.github.io were hand-edited to fix the problem. However, I can't seem to replicate it at the moment, so I will close the issue, and can reopen whenever I find a good, reproducable example.
