### ISSUE TITLE
cli: Setting only one frequency axis limit causes Quantity vs Float conflict

### ISSUE THREAD

**Issue by areeda** [gwpy/gwpy#66]
Bitten once again by this. I guess floats can't walk like a Quantity and Quantities can't walk like a float.

**Comment by duncanmmacleod** [comment]
Astropy used to support `float(quantity)`, but they removed it, sadly. You can cast to `numpy.float64`, but GWpy uses `Quantity` objects predictably, so we should be able to know what is a `Quantity` and what is not.

@areeda, can you post a minimal example to reproduce the bug?

**Comment by areeda** [comment]
The follow command demonstrates the error
`gwpy-plot spectrum --chan L1:OAF-CAL_DARM_DQ  --start 1110940463 --fmax 900`
It produces:
`astropy.units.core.UnitsError: 'Unit("Hz")' is not a scaled version of 'Unit(dimensionless)'`

If you add --fmin 1 or remove the --fmax 900 parameter it succeeds.

**Comment by duncanmmacleod** [comment]
I am preparing a significant rebuild of the data structures in GWpy that will include a resolution for this issue. I'll ask @areeda to review the relevant PR from a `gwpy.cli` perspective.
