### ISSUE TITLE
SnglBurstTable.fetch does not return error messages

### ISSUE THREAD

**Issue by andrew-lundgren** [gwpy/gwpy#72]
Trying to get Omicron triggers using the fetch method of SnglBurstTable, I found that no error message is returned if the channel is not analyzed by Omicron (or if the channel name is wrong). Also no error message is given if the name of the ETG is wrong, and the help message doesn't list the possible ETGs, or specify formatting (e.g. omicron vs Omicron).

Examples:

SnglBurstTable.fetch('H1:NOT-A_CHANNEL','omicron',1111230000,1111240000)

SnglBurstTable.fetch('H1:LSC-DARM_IN1_DQ','iota',1111230000,1111240000)

Both return an empty list.

**Comment by duncanmmacleod** [comment]
I will modify the file location algorithm to raise an exception if a channel-level directory is not found. There isn't a bullet-proof way of distinguishing between the channel being wrong or the ETG being wrong (without `stat`ing the entire directory every time), but I think an error saying that one of them is wrong is probably enough.

**Comment by andrew-lundgren** [comment]
Yes, looks good.
