### ISSUE TITLE
For Gravity Spy Table object make sure all unicode gets converted to string to allow for easy write to HDF5

### ISSUE THREAD

**Issue by scottcoughlin2014** [gwpy/gwpy#721]
In order to comply with new data format recommendations that suggest that tabular data be writable to HDF5, unicode column of GravitySpyTable need to be string. 

For instance, the current functionality of say
`In [42]: Blip = EventTable.fetch('gravityspy', 'glitches', selection=['Label=Blip','ImageStatus=Retired'], columns=['snr','Label', 'peakGPS'])`

In [43]: Blip.write('new_file.hdf5', path='blip')`

returns

`TypeError: No conversion path for dtype: dtype('<U4')`

**Comment by scottcoughlin2014** [comment]
I would assign myself to this issue @duncanmmacleod but i cannot haha

**Comment by duncanmmacleod** [comment]
@scottcoughlin2014, was this fixed by #727?

**Comment by scottcoughlin2014** [comment]
yes @duncanmmacleod
