### ISSUE TITLE
FrequencySeries doesn't have function `whiten`

### ISSUE THREAD

**Issue by sudughonge** [gwpy/gwpy#723]
I'm writing code which calculates the correlation between two channels' time series. This computation is performed in the frequency domain and using whitened data. I'm fetching the data from the frame files using `gwpy.timeseries.TimeSeries.read()`, whitening it and then taking it's FFT (and a subsequent bunch of operations) before calculating the correlation. There's a redundant IFFT and FFT in this process. It'd be computationally more efficient if `FrequencySeries` class had a whiten function.

I'd like to request the addition of the `whiten`  to 'gwpy.frequencyseries.FrequencySeries'. It'd mean a minor change to https://github.com/gwpy/gwpy/blob/761c31222a127eac1de68e4844de0b660ad55599/gwpy/timeseries/timeseries.py#L1444
and perhaps make ASD a necessary argument.

**Comment by sudughonge** [comment]
@duncanmmacleod ah, you're right. Having the ASD would make it a trivial task - and won't need a separate function.

My request boils down to something like the following:
I have an 8 second timeseries vector. Under the current scheme the following is happening:
1. `gwpy.timeseries.TimeSeries.whiten` divides the vector into  chunks, say 8 (or more in case of overlaps), and computes the FFT for each.
2. Computes the ASD from them
For each chunk, 
  3. Computes the FFT
  4. Divide by the ASD
  5. Compute the IFFT
6. Output the whitened timeseries by stitching outputs of step 5
7. My function takes the FFT of output in step 6 using the entire vector length as segment length

I was wondering if step 5-6 could be modified so that the whole process isn't going into taking FFTs (and IFFTs) too many times. I realize the segment size in step 3 and step 7 is different but I wanted to know if after step 4, a direct jump to step 7 is possible to get the final FFT I desire.

**Comment by duncanmmacleod** [comment]
@sudughonge, apologies for the lack of attention to this ticket, is it still relevant these days?

**Comment by sudughonge** [comment]
@duncanmmacleod thanks for checking in. I had forgotten about this. It's not relevant anymore as taking the PSD over the trigger segment alone essentially drowns out the excess power. I'll close the ticket.
