### ISSUE TITLE
LAL incompatibility

### ISSUE THREAD

**Issue by maxisi** [gwpy/gwpy#73]
As of today, the latest version of LAL in master does not jive well with GWpy. It seems that `from lal import lal` doesn't work anymore (although `import lal` does). For instance:

```
>>> from gwpy.timeseries import TimeSeries
>>> data = TimeSeries.read("/archive/frames/trend/minute-trend/40m/C-M-11/C-M-1111554000-3600.gwf", "C1:LSC-DARM_OUT_DQ.mean")
>>> spectrum = data.asd(method='median-mean')
  File "<stdin>", line 1, in <module>
  File "/home/max.isi/.local/lib/python2.6/site-packages/gwpy-0.1b1.dev17-py2.6.egg/gwpy/timeseries/core.py", line 492, in asd
    overlap=overlap, **kwargs) ** (1/2.)
  File "/home/max.isi/.local/lib/python2.6/site-packages/gwpy-0.1b1.dev17-py2.6.egg/gwpy/timeseries/core.py", line 459, in psd
    psd_ = method_func(self, nfft, **kwargs)
  File "/home/max.isi/.local/lib/python2.6/site-packages/gwpy-0.1b1.dev17-py2.6.egg/gwpy/spectrum/lal_.py", line 220, in _spectrum
    return lal_psd(*args, **kwargs)
  File "/home/max.isi/.local/lib/python2.6/site-packages/gwpy-0.1b1.dev17-py2.6.egg/gwpy/utils/deps.py", line 81, in wrapper
    stacklevel=2)
  File "/home/max.isi/.local/lib/python2.6/site-packages/gwpy-0.1b1.dev17-py2.6.egg/gwpy/utils/deps.py", line 50, in import_method_dependency
    return __import__(module, fromlist=[''])
ImportError: Cannot import lal.lal required by the _spectrum() method: 'No module named lal'
```

**Comment by duncanmmacleod** [comment]
@maxisi, I can't reproduce this bug. Can you give me a full example of how to reproduce (including login host, any source commands, and all python commands)?

**Comment by maxisi** [comment]
Maybe it was some transient problem with LAL, I will check again and let you know.

**Comment by duncanmmacleod** [comment]
@maxisi can you confirm this problem is no longer a problem? If so, please close.

**Comment by yech1990** [comment]
I got the similar problem
```python
>>> from gwpy.timeseries import TimeSeries
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/gwpy/timeseries/__init__.py", line 27, in <module>
    from .core import *
  File "/usr/local/lib/python2.7/dist-packages/gwpy/timeseries/core.py", line 45, in <module>
    from ..data import (Array2D, Series)
  File "/usr/local/lib/python2.7/dist-packages/gwpy/data/__init__.py", line 29, in <module>
    from glue.lal import (Cache, CacheEntry)
ImportError: No module named lal
```

**Comment by yech1990** [comment]
I install gwpy on ubuntu server by `pip install --pre gwpy`

**Comment by yech1990** [comment]
Executing ``import glue`` doesn't raise any error.

**Comment by yech1990** [comment]
same error occur when runing the installation on ubuntu 15.10 desktop

**Comment by duncanmmacleod** [comment]
sorry, I've left this sitting for two long, can you post the output of

```
from glue import git_version
```

There is a good chance that you have installed 

https://pypi.python.org/pypi/glue/0.11.1

and not

http://software.ligo.org/lscsoft/source/glue-1.49.1.tar.gz

Unfortunately LIGO uses a package with an identically named but completely different package registerd on pypi, so you might have to be careful.

**Comment by duncanmmacleod** [comment]
@yech1990, did you resolve this problem? If not, do you have an answer to the above questions?

**Comment by brettlv** [comment]
yes i met the same problem

**Comment by duncanmmacleod** [comment]
@brettlv, can you post the error you are seeing, as well as the output of the above `glue` test?

**Comment by brettlv** [comment]
@duncanmmacleod 

import random
import matplotlib
import matplotlib.pyplot as plt
import time
import glue
import gwpy
from gwpy.timeseries import TimeSeriesDict
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-b21f178a00c1> in <module>()
----> 1 from gwpy.timeseries import TimeSeriesDict

C:\Users\Administrator\AppData\Roaming\Python\Python27\site-packages\gwpy\timeseries\__init__.py in <module>()
     22 __author__ = "Duncan Macleod <duncan.macleod@ligo.org>"
     23 
---> 24 from .core import *
     25 from .timeseries import *
     26 from .statevector import *

C:\Users\Administrator\AppData\Roaming\Python\Python27\site-packages\gwpy\timeseries\core.py in <module>()
     42                             nds2.channel.CHANNEL_TYPE_STATIC)
     43 
---> 44 from ..data import (Array2D, Series)
     45 from ..detector import (Channel, ChannelList)
     46 from ..io import (reader, writer, datafind)

C:\Users\Administrator\AppData\Roaming\Python\Python27\site-packages\gwpy\data\__init__.py in <module>()
     24 
     25 
---> 26 from glue.lal import (Cache, CacheEntry)
     27 
     28 from .array import *

ImportError: No module named lal

**Comment by brettlv** [comment]
so how to get glue test?
just command "glue.test()"?,which doesnot make sense.
thank you~

here are some results below,and there is no problem when import,but the first command "from gwpy.timeseries import TimeSeriesDict" makes error

@duncanmmacleod

import random
import matplotlib
import matplotlib.pyplot as plt
import time
import glue
import gwpy

from gwpy.timeseries import TimeSeriesDict

ImportError Traceback (most recent call last)
in ()
----> 1 from gwpy.timeseries import TimeSeriesDict

C:\Users\Administrator\AppData\Roaming\Python\Python27\site-packages\gwpy\timeseries__init__.py in ()
22 author = "Duncan Macleod duncan.macleod@ligo.org"
23
---> 24 from .core import *
25 from .timeseries import *
26 from .statevector import *

C:\Users\Administrator\AppData\Roaming\Python\Python27\site-packages\gwpy\timeseries\core.py in ()
42 nds2.channel.CHANNEL_TYPE_STATIC)
43
---> 44 from ..data import (Array2D, Series)
45 from ..detector import (Channel, ChannelList)
46 from ..io import (reader, writer, datafind)

C:\Users\Administrator\AppData\Roaming\Python\Python27\site-packages\gwpy\data__init__.py in ()
24
25
---> 26 from glue.lal import (Cache, CacheEntry)
27
28 from .array import *

ImportError: No module named lal

在2016-09-17 03:32:11，吕兵u201210249@hust.edu.cn写道：

@brettlv, can you post the error you are seeing, as well as the output of the above glue test?

**Comment by duncanmmacleod** [comment]
@brettlv, it looks like you have installed [this package called glue](https://pypi.python.org/pypi/glue/0.11.1), which is what you will get if you run `pip install glue`. However, the dependency for GWpy is a completely different package, produced by the LIGO Scientific Collaboration, that is also called `glue`. You should remove the other package:

```
pip uninstall glue -y
```

then install LSCSoft `glue`:

```
pip install -y http://software.ligo.org/lscsoft/source/glue-1.50.0.tar.gz
```

Then please repeat the tests you posted above. Please also try to execute this from inside python and post the result:

```python
>>> from glue import git_version
>>> print(git_version.verbose_msg)
```

Thanks.

**Comment by brettlv** [comment]
@duncanmmacleod 
no such option: -y

when i do this:
pip install -y http://software.ligo.org/lscsoft/source/glue-1.50.0.
tar.gz

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

**Comment by duncanmmacleod** [comment]
@brettlv, sorry, typo, that should be `pip install -q`.

**Comment by brettlv** [comment]
that makes error too...

**Comment by brettlv** [comment]
whether i could use it in windows python?

**Comment by duncanmmacleod** [comment]
@brettlv, can you be more precise about the error you get? Which command is failing, and how? Please post the traceback you get.

Also, there is little hope for support for windows, at least one of the upstream dependencies doesn't build on windows, and I don't have the expertise (or the time) to make it work.

**Comment by brettlv** [comment]
alright, maybe i have to buy a mac... hahaa... thanks a lot...i just wanna try it

**Comment by gianthawk** [comment]
I'm also having the same issue. I'm using MacOSX and I installed the LSCSoft glue as mentioned above, along with lal, lalframe and the dependencies mentioned on the website through MacPorts. I can import glue, glue.lal and gwpy but when I try to do 'from gwpy.timeseries import TimeSeriesDict', I receive the ImportError: no module named lal.

**Comment by duncanmmacleod** [comment]
@gianthawk, the LALSuite ports were recently separated to have independent ports for the SWIG-python bindings of the relevant packages. So, you need to install `py27-lal` (or similar) to get the `lal` python package.

This change is reflected on the [latest install docs](https://gwpy.github.io/docs/latest/install.html), but not the stable page, which is in desperate need of an update.

**Comment by gianthawk** [comment]
Thanks! I did what the latest docs suggested, but I am still getting the same ImportError?

**Comment by gianthawk** [comment]
Never mind!

**Comment by brettlv** [comment]
can we use gwpy with python3 in default?

**Comment by duncanmmacleod** [comment]
@brettlv, GWpy itself should work with python3, but a few of the optional dependencies that enable extra functionality are not, e.g. PyCBC. Give it a go and post new tickets if you run into problems.

**Comment by brettlv** [comment]
but i cannot import gwpy when I use jupyter notebook in  python3.6 with anaconda3

**Comment by duncanmmacleod** [comment]
@brettlv, please open a new ticket with a description of the problem and a link to the code you are trying to run and the errors you are seeing. thanks.

**Comment by ssalam21** [comment]
I write the following lines and then enter get the error message 
 import random
>>> import matplotlib
>>> import matplotlib.pyplot as plt
>>> import time
>>> import glue
>>> import gwpy
>>> from gwpy.timeseries import TimeSeriesDict

then I got the error below 
    from astropy.io.registry import (  # noqa: F401
ImportError: cannot import name '_get_valid_format' from 'astropy.io.registry'

**Comment by duncanmmacleod** [comment]
@ssalam21, this ticket was closed more than 4 years ago, and refers to a different problem. In future please post your problem as a new ticket. However, this looks like a duplicate of #1432, for which a fix has been implemented, and will be released today.
