### ISSUE TITLE
Value of a TimeSeries.epoch is incorrect

### ISSUE THREAD

**Issue by andrew-lundgren** [gwpy/gwpy#74]
I have a time series whose .value property is 35 seconds before the correct answer. I did

data2 = TimeSeries.fetch('H1:SUS-MC2_M3_MASTER_OUT_UR_DQ', 1112015670, 1112015676, verbose=True)

Then data2.epoch gives <Time object: scale='utc' format='gps' value=1112015670.0>

but data2.epoch.value is 1112015635.0

**Comment by duncanmmacleod** [comment]
`TimeSeries.epoch` is an `astropy.time.Time` object, for which `value` is not a standard attribute. You should instead use:

```python
>>> print(data2.epoch.gps)
1112015670.0
```

**Comment by andrew-lundgren** [comment]
That attribute needs to be removed, if it gives misleading answers. It would be nice if it worked the same way sample_rate does, though. Why should it be x.sample_rate.value, x.epoch.gps, and in neither case can you just do the Pythonic thing and do float(x.sample_rate)?

**Comment by duncanmmacleod** [comment]
I would argue that `float(x.sample_rate)` is not more pythonic than `x.sample_rate.value`, it's just slightly less intuitive. The fact that `epoch` is an `astropy.time.Time` object, whereas `sample_rate` is an `astropy.units.Quantity` object is well documented,.

Both the `Time` and `Quantity` objects are themselves well documented, as part of `astropy`, and given that they are imported from a third-party dependency, attributes cannot be removed.

**Comment by andrew-lundgren** [comment]
This is a bug in astropy, then. The documentation for 0.4.5 (we have 0.4.4 on the clusters) says that the value attribute is "Time value(s) in current format". The format is gps, so .value and .gps should agree. Do you want to see if this is fixed in a later release of astropy, and if not file a bug with them?

Also, a general comment, you shouldn't expect that users read the astropy documentation.

**Comment by duncanmmacleod** [comment]
Sorry @andrew-lundgren, you are right about the documentation. However, the [GPS time format as implemented in AstroPy](http://astropy.readthedocs.org/en/stable/api/astropy.time.TimeGPS.html#astropy.time.TimeGPS) uses the TAI scaling, which is 19 seconds ahead of UTC, so when you combine that with 16 leap seconds, you get a 35-second offset from UTC with leap seconds.

So the `value` of a GPS epoch in GWpy is currently given in TAI, and not UTC scale.

I will consider sub-classing the `TimeGPS` from astropy to give UTC scaling if you think that will be more obvious.
