### ISSUE TITLE
Add support for scaled data in Frame files

### ISSUE THREAD

**Issue by basswinkels** [gwpy/gwpy#749]
At Virgo, many channels are stored as an int32, which should be scaled using floating point numbers stored inside the frames itself. This is typically done for storing environmental sensors or photodiode signals that are sampled by an ADC. I seems that gwpy is ignoring this scaling. It would be good to have a new function (or some keyword argument on an existing function that defaults to the old behavior) to scale the data when offset != 0 and gain != 1.

Relevant fields are in the FrAdcData structures in FrameL.h:

struct FrAdcData {               /* hold ADC data (or image)                 */
[...snip ...]
  float bias;                    /* DC bias on channel.  the step 
                                     size is stored in adc->data->dx;        */
  float slope;                   /* ADC calibration: input units/count       */
[... snip ...]
};

In Matlab, the difference between downloading data without or with the scaling applied is the difference between the functions frgetvect and frgetvectN (for normalized), it might be helpful to study this code.

**Comment by duncanmmacleod** [comment]
@basswinkels, sorry for the delay in getting to this. Would you consider that applying the bias and slope should be the _default_ operation?

**Comment by duncanmmacleod** [comment]
@basswinkels, can you also post an example of a channel in a specific GWF file that has non-zero bias and/or non-unity slope I can use to test any code changes?

**Comment by basswinkels** [comment]
@duncanmmacleod see [attached](https://github.com/gwpy/gwpy/files/2420627/gwf_slope_bias.txt) example.

My preference would be to always apply the gain/offset (if they are not simply 1 and 0), so that it is transparent to the user. I do however not know if these fields are set correctly for LIGO data, for which you obviously don't want to break anything.

An alternative would be to give all relevant functions a keyword `scaled`, which defaults to True if possible (so that the normal user can forget about it, but which a power user might set to False for speed in Bruco type applications), or which defaults to False if for whatever reason this causes problems at LIGO (but in that case I would have to teach users at Virgo to use `scaled=True` if they see unexpected values).

Does lalframe or frameCPP expose these fields?

**Comment by duncanmmacleod** [comment]
@basswinkels, `frameCPP` definitely exposes those fields, and applying the slope/bias when reading the data is trivial. I'm not so sure about `lalframe`, but we're likely to deprecate that interface in GWpy anyway (since the frameCPP API is enough).

I agree that we should default to applying the gain/slope, and if LIGO doesn't record those correctly, too bad. In my experience, these _are_ set correctly, but are almost universally `slope=1, bias=0`. I like the idea of `scaled=True` as a default as well. I will implement all of this, post a PR, and point you at it for a quick review. Thanks again.
