### ISSUE TITLE
gwpy-plot timeseries of constant value give error,but produces a reasonable plot

### ISSUE THREAD

**Issue by areeda** [gwpy/gwpy#75]
Example:

gwpy-plot timeseries --chan H1:LSC-Y_TR_A_LF_OUT_DQ --start 
Gives:

/home/detchar/opt/gwpysoft/lib64/python2.6/site-packages/matplotlib/axes.py:2760: UserWarning: Attempting to set identical bottom==top results
in singular transformations; automatically expanding.
bottom=615.266601562, top=615.266601562
  + 'bottom=%s, top=%s') % (bottom, top))

gwpy-plot should detect this and do some expansion of the axis.

**Comment by duncanmmacleod** [comment]
This is not an error, just a warning that the y-axis had to be extended to give a sensible output. `matplotlib` is doing exactly what it should in this case, and I don't think we have anything to worry about.

You might want to add a check in the internals of `gwpy.cli` somewhere to make sure that this warning doesn't get printed, but I'm not fussed either way.

**Comment by duncanmmacleod** [comment]
@areeda: is there an update on this issue?

**Comment by areeda** [comment]
Sorry, no there is not.  I have been buried in other projects.

**Comment by duncanmmacleod** [comment]
No worries, I just wanted to check that it hadn't fallen off the radar.

**Comment by duncanmmacleod** [comment]
This cannot be reproduced from the above information, and has sat idle for a long time, will close.
