### ISSUE TITLE
Add BLRMS to gwpy-plot

### ISSUE THREAD

**Issue by lauranuttall** [gwpy/gwpy#754]
BLRMS in gwpy and ligo-dv web are vastly different...why please?

**Comment by duncanmmacleod** [comment]
@areeda, I know you have a separate blrms plotter for LDVW that uses gwpy, can you comment on whether that could be merged into the `gwpy-plot` infrastructure?

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/754, please join us on gitlab to continue your contribution!
