### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in c:\users\...

### ISSUE THREAD

**Issue by fiziev** [gwpy/gwpy#772]
During the istalation in docker version

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: false 

the command   pip install gwpy[all]

ends with error message:

Command "python setup.py egg_info" failed with error code 1 in c:\users\fizie\appdata\local\temp\pip-install-kz3b74\root-numpy\

**Comment by fiziev** [comment]
How to overcome the problem?

**Comment by duncanmmacleod** [comment]
@fiziev, if you could provide a traceback, that would help a little, but it looks like the build is failing on `root_numpy`. This package requires the cern ROOT package to build, which you probably don't have.

I would recommend to not use `[all]` for now, or install `ROOT` .

**Comment by fiziev** [comment]
Thank you!

It seems that the problem is in the OS Windows 10.

I'l try to isntall all packages on Scientific Linux where I have CERNs
ROOT package and will inform you in the case of problems.

Maybe it will be useful to put corresponding WORNING in the instructions
for `[all]` command.
