### ISSUE TITLE
Common Data Format Compliance For Gravity Spy Tables

### ISSUE THREAD

**Issue by scottcoughlin2014** [gwpy/gwpy#773]
- [ ] Python 3.x still failing to store the whole table. simply running `convert_unicode_to_bytestring()` method of astropy tables fixes it so that you can fetch and immediately save the dataset to hdf5.
- [ ] currently that names in the Gravity Spy tables are very poorly formatted and should abide the suggestions in https://git.ligo.org/detchar/common-data-formats/T1800014

```
In [8]: from gwpy.table import EventTable

In [9]: blips_O2_L1_retired = EventTable.fetch('gravityspy', 'glitches', selection = ['"Label" = "Blip"', '"peakGPS" > 1137250000', 'ifo=L1', '"ImageStatus" = "Retired"'])

In [10]: blips_O2_L1_retired.convert_unicode_to_bytestring()

In [13]: blips_O2_L1_retired.write('tmp.hdf5',path='blips', format='hdf5')
```

**Comment by scottcoughlin2014** [comment]
Pinging myself here to work on this. just remembering this as a problem today making the gravity spy tools slides.

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/773, please join us on gitlab to continue your contribution!
