### ISSUE TITLE
interpolation kwarg doesn't do anything in Spectrogram.plot()

### ISSUE THREAD

**Issue by tjma12** [gwpy/gwpy#784]
I'm trying to plot spectrograms with interpolation and calling `Spectrogram.plot(interpolation='gaussian')` with Matplotlib 2.1.2 doesn't seem to do anything. An ipython notebook calling the plot function with and without the interpolation kwarg can be found on the CIT cluster at:

`/home/thomas.massinger/public_html/notebook/spectrogram-interp.ipynb`

An example of an alternative 2D interpolation similar to what is done in the `TimeSeries.q_transform().plot()` method is included.

**Comment by duncanmmacleod** [comment]
this is probably due to ignore keywords:

https://github.com/gwpy/gwpy/blob/84c547a71fe80847f597ab5f3539b186ab606b97/gwpy/plotter/series.py#L255-L265

this will be fixed by #790, marked for the next release.
