### ISSUE TITLE
taper method seems to not be working?

### ISSUE THREAD

**Issue by scottcoughlin2014** [gwpy/gwpy#798]
Hey @alurban,

I have a bit of a gnarly cut off from the SN waveform model I am working with (just the business of cutting off the simulation I guess). And when I try to `taper` it seems that its not quite as smoothly bring it to zero as I would like (see attached image). Any thoughts I what I should check here. Be happy to give you the `h5` file so you can see it for yourself

```
In [72]: x = TimeSeries.read('Morozova2018.hdf5', path='/Morozova2018/M19_SFHo/hp')

In [73]: taper_series = x.taper()
```
![strain-m19_sfho](https://user-images.githubusercontent.com/15366333/41379045-8c685f2c-6f26-11e8-881e-1d75ea233160.png)

**Comment by duncanmmacleod** [comment]
@scottcoughlin2014, please post an example we can use to reproduce the issue? What are you expecting to see?

**Comment by scottcoughlin2014** [comment]
@duncanmmacleod sure github does not believe the `hdf5` file that is shown in the example above qualifies as a file that can be attached here. maybe Ill upload it to slack? I guess I *thought* that the decent to zero strain would have more followed the slow but sure down ward trend you can see in the plot above, I am concerned that the drop off to zero is too quick and that a feature like that would artificially show up if one was to say inject and try to recover this signal.

**Comment by alurban** [comment]
@scottcoughlin2014 So the `TimeSeries.taper()` method is just a wrapper around `gwpy.signal.window.planck()`. The `taper()` method tapers to the second stationary point on either side of the input waveform. So, if your waveform is super high-frequency at the end (which it seems to be, just glancing by eye) then the taper length will be extremely short, but still smooth.

This reproduces the default behavior of `lal` which is mainly used in CBC injections. If you want more control of the taper length, you can try constructing your own Planck taper window by hand using `gwpy.signal.window.planck()`.

**Comment by scottcoughlin2014** [comment]
thanks @alurban I think that makes sense, I will ask Patrick if he thinks it is necessary to do something more but maybe based on your explanation it wont be a big deal in the tf-map. I will check

**Comment by alurban** [comment]
@scottcoughlin2014 I think you can attempt an answer by looking at the frequency response of a tapered vs. untapered waveform. If your signal has content above several kHz, then that's where the tapering should make a difference if it's being implemented correctly. I also noticed that your waveform isn't centered on 0 (i.e. it has nonzero DC offset). Is that expected?

**Comment by alurban** [comment]
Re: frequency response, see e.g. this plot (produced by Yuri D'Elia): https://cloud.githubusercontent.com/assets/1017726/14115608/f0793598-f5db-11e5-8c47-a783f45587eb.png

**Comment by scottcoughlin2014** [comment]
Alright these are good enough resources to look into this myself Thanks!

**Comment by duncanmmacleod** [comment]
@scottcoughlin2014, @alurban, is this ticket resolved? if so, please close.

**Comment by alurban** [comment]
@duncanmmacleod, this ticket is indeed resolved, though I don't have admin privileges so I can't close.
