### ISSUE TITLE
Virgo data has no default NDS server

### ISSUE THREAD

**Issue by areeda** [gwpy/gwpy#816]
PLUS there's a typo in the warning format string I think
```
/Users/areeda/py_envs/gwpy/lib/python2.7/site-packages/gwpy/io/nds2.py:269: UserWarning: No default host found for ifo 'V'1
  warnings.warn('No default host found for ifo %r' % ifo)
```

**Comment by duncanmmacleod** [comment]
@areeda, I'm not sure what you are asking with this ticket. The warning is as designed, are you asking that we should make the CIT server the default for Virgo?
