### ISSUE TITLE
gwpy-plot timeseries gives different plot for minute, second trend, raw data

### ISSUE THREAD

**Issue by andrew-lundgren** [gwpy/gwpy#82]
I plotted a timeseries using minute trend data. I'm looking for where the HWS camera turns off, and on the minute plot it's at 60 minutes in. When I switched to second trend for better resolution, it's at 80 minutes in. With the raw data, it never turns off. I'm not sure whether this is a bug in the plotting code or maybe in NDS2.

`gwpy-plot timeseries --chan "H1:TCS-ITMX_HWS_DALSACAMERASWITCH.mean,m-trend" "H1:TCS-ITMY_HWS_DALSACAMERASWITCH.mean,m-trend" --start 1113368400 --dur 7200 --ymin -0.1 --ymax 1.1 --out test-hws-mtrend.png`

![test-hws-mtrend](https://cloud.githubusercontent.com/assets/11574489/7247654/03bcaf38-e80c-11e4-8806-4b5d049a39fc.png)

`gwpy-plot timeseries --chan "H1:TCS-ITMX_HWS_DALSACAMERASWITCH.mean,s-trend" "H1:TCS-ITMY_HWS_DALSACAMERASWITCH.mean,s-trend" --start 1113368400 --dur 7200 --ymin -0.1 --ymax 1.1 --out test-hws-strend.png`

![test-hws-strend](https://cloud.githubusercontent.com/assets/11574489/7247665/1ffb1de2-e80c-11e4-9e46-415152ce8c73.png)

`gwpy-plot timeseries --chan "H1:TCS-ITMX_HWS_DALSACAMERASWITCH" "H1:TCS-ITMY_HWS_DALSACAMERASWITCH" --start 1113368400 --dur 7200 --ymin -0.1 --ymax 1.1 --out test-hws-raw.png`

![test-hws-raw](https://cloud.githubusercontent.com/assets/11574489/7247896/8ba09070-e80e-11e4-86eb-cb1c35a2594b.png)

**Comment by duncanmmacleod** [comment]
I have reproduced the same bug using only `lalframe` and `matplotlib`. Both GWpy and `lalframe` are faithfully representing the data as recorded in the frames.

![hws](https://cloud.githubusercontent.com/assets/1618530/7256408/94c42a30-e814-11e4-9235-5ad8aca17ce3.png)
