### ISSUE TITLE
gwpy-plot Qtransform is missing cli options

### ISSUE THREAD

**Issue by areeda** [gwpy/gwpy#820]
The cli options that changed:

`--sample_freq SAMPLE_FREQ     Downsample freq` renamed to `--sample-freq`
These 2 are missing:
```
  --erange ERANGE ERANGE        Normalized energy range
  --srange SRANGE SRANGE        Search frequency range```

**Comment by duncanmmacleod** [comment]
@areeda, was this issue resolved?

**Comment by areeda** [comment]
This has been resolved
