### ISSUE TITLE
gwpy-plot spectrogram fails if zero ffts and missing --nopct option

### ISSUE THREAD

**Issue by areeda** [gwpy/gwpy#821]
I may be the only one who uses it but the option is there so that the color bar limits can be set to a percentile value of the actual spectrogram.

 I don't understand why the histogram based background estimation works so well in the Java version and so poorly here.

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/821, please join us on gitlab to continue your contribution!
