### ISSUE TITLE
Spectrogram 2D addressing issue

### ISSUE THREAD

**Issue by areeda** [gwpy/gwpy#826]
Searching the spectrogram for the minimum nonzero value exposed a functional style indexing problem with 2D GWpy objects.

This snippet reproduces it.

```from gwpy.timeseries import TimeSeries
import numpy as np
da= TimeSeries.fetch('V1:DQ_VetoThr_VETO_DIFFP_TX5TY5,raw', 1213723471, 1213723471+30,host='nds')
da.override_unit('undef')
sp=da.spectrogram2(1,.5)

#  this works
sp.value[sp.value>0].min()

#this doesn't
sp[sp.value > 0]
```

**Comment by duncanmmacleod** [comment]
@areeda, this is a fundamental issue with the way that gwpy arrays are constructed, this operation:

```python
sp.value[sp.value>0]
```

returns a 1-Dimensional array of values, whereas gwpy is expecting all slices and index arrays to preserve shape. What should the 'correct' output of the operation `sp[sp.value > 0]`?

**Comment by duncanmmacleod** [comment]
@areeda, is this still an active issue? If not I would like to close it.

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/826, please join us on gitlab to continue your contribution!
