### ISSUE TITLE
Enhancement: timeseries.fetch() option to fail on no TGT

### ISSUE THREAD

**Issue by areeda** [gwpy/gwpy#838]
I've had the problem come up that timeseries.fetch() will hang  when called in the background (by LDVW) with an expired TGT. This leaves zombie processes.

 I can think of 2 approaches that may be easy to implement.

1.  A new keyword argument that requests the failure rather than an interactive request for username and password.

2.  A timeout, can be long, for the user to enter that information.

**Comment by duncanmmacleod** [comment]
@areeda, I think you mean that when running in the background, `gwpy` still tries to ask the user for information, which never gets entered? I'll have a think about detecting background processing and disabling prompts for those cases.

**Comment by duncanmmacleod** [comment]
@areeda, ping.
