### ISSUE TITLE
Allow for the fetching of specific uniqueIDs in EventTable.fetch

### ISSUE THREAD

**Issue by scottcoughlin2014** [gwpy/gwpy#847]
In reality, this would sort of be a nice general feature improvement to the `sql.py` and `fetch.py` functions to allow for `SQL` `IN` statements to be executes ina  more natural way. currently below is how it would have to look to do it now.
```
In [2]: selected_images = EventTable.fetch('gravityspy', 'glitches WHERE \"uniqueID\" IN (\'1miVinrpqA\', \'2Z9oUwYOEB\')')
```

But image in python you had create a list of uniqueID (or gps times or whatever) and wanted to just do something like:

`EventTable.fetch('gravityspy', 'glitches', peakGPS="somelistofgpstimes")`

**Comment by scottcoughlin2014** [comment]
ok I have 20 minutes to take a nice look at this.
So right now
```
>>> EventTable.fetch('gravityspy', 'glitches', selection='Label=Blip')
```
is the flexibility for selection which is nice.

The problem with keeping that logic for the above is that
```
>>> EventTable.fetch('gravityspy', 'glitches', selection='uniqueID=['1miVinrpqA', '2Z9oUwYOEB']')
```
Seems tough to format

I like
```
>>> EventTable.fetch('gravityspy', 'glitches', uniqueID=['1miVinrpqA', '2Z9oUwYOEB'])
```
but maybe having the columns names as `**kwargs` may be weird?

**Comment by duncanmmacleod** [comment]
@scottcoughlin2014, is this still an issue for gwpy, or has this been resolved in some way?

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/847, please join us on gitlab to continue your contribution!
