### ISSUE TITLE
Gravityspy functions should scrape environment at execution time, not import

### ISSUE THREAD

**Issue by duncanmmacleod** [gwpy/gwpy#855]
@scottcoughlin2014, currently the GravitySpy functions that scrape the environment when the module is imported for the first time, rather than at execution time:

https://github.com/gwpy/gwpy/blob/879b044f0c39c79f3d19512ba465cd61c9dea93a/gwpy/table/io/gravityspy.py#L93-L96

Using `user=None, passwd=None` as defaults and scraping the environment inside the function will allows users to manipulate their environment (via `os.environ`) on-the-fly if they wish.

**Comment by scottcoughlin2014** [comment]
@duncanmmacleod oh so that's what has been the problem. ya i mean that sounds good. I can probably do a PR for that soon?
