### ISSUE TITLE
Integrate foton.py module

### ISSUE THREAD

**Issue by eagoetz** [gwpy/gwpy#858]
@alurban Integrating foton.py into gwpy would make it easier to apply FOTON filters to data. I'm not sure the complexity of such an undertaking, but it could/would make life a lot easier for various projects, including pyDARM.

**Comment by duncanmmacleod** [comment]
@eagoetz, can you remind me, does `foton.py` come from GDS? Can you give an example of what the integration would entail? I presume you mean something like reading filters out of a FOTON file, if so can you post an example of what those filters look like, and what conventions are used in the definitions?

**Comment by eagoetz** [comment]
@duncanmmacleod Yes, foton.py is in GDS tools. Unfortunately, GDStools are a pain to install (I've never been successful installing it on my local laptop) and I think integrating foton.py with GWpy could be a good solution. It should be able to read the filters out of whatever is in the front end, ideally specifying a GPS time so that it can figure out which filter module was turned on at that time. I believe foton.py should be able to do this.

Also, the second part to this is the API in foton.py should allow one to write out their own FOTON filter file.

I don't believe there is a documented convention, but here is my code for reading a FOTON file (the foton.py code may be somewhat different):
`def readFilterFile(filename):
    """Read a filter file and return all the SOS coefficients info for the filters

    Parameters
    ----------
    filename : `str`
        Path and filename of FOTON filter file

    Returns
    -------
    out : array-like
        Data from the FOTON filter file. 
    """
    out = [filename]
    with open(filename) as file:
        for line in file:
            line = line.rstrip()
            if re.match('^#',line) and len(line)>2:
                if re.search('MODULES', line):
                    line_el = line.split(' ')
                    for n in range(2, len(line_el)):
                        new_filter_bank = cds_filter_bank(line_el[n], [cds_filter]*10)
                        for m in range(0, 10):
                            new_filter_bank.filters[m] = cds_filter('empty', np.array([1,0,0,1,0,0]), 16384, '<none>')
                        out.append(new_filter_bank)
                elif re.search('SAMPLING', line):
                    line_el = line.split(' ')
                    if line_el[2]=='RATE':
                        for n in range(1,len(out)):
                            for m in range(0, 10):
                                out[n].filters[m] = out[n].filters[m]._replace(fs=int(line_el[3]))
                elif re.search('DESIGN', line):
                    line_el = line.split()
                    fname = line_el[2]
                    index = int(line_el[3])
                    design_str = line_el[4]
                    while line_el[len(line_el)-1]=='\\':
                        line = next(file)
                        line_el = line.split()
                        if len(line_el)==1: break
                        else: design_str += line_el[1]
                    filterbank_index = 1
                    while not re.match(fname, out[filterbank_index].name):
                        filterbank_index += 1
                    out[filterbank_index].filters[index] = out[filterbank_index].filters[index]._replace(design=design_str)
            elif len(line.split())==12:
                line_el = line.split()
                fname = line_el[0]
                index = int(line_el[1])
                mname = line_el[6]
                gain = float(line_el[7])
                sos_coeff_lines = int(line_el[3])
                soscoeffs = np.ones((sos_coeff_lines, 6))
                for n in range(0, sos_coeff_lines):
                    if n==0:
                        soscoeffs[n,1] = float(line_el[10])
                        soscoeffs[n,2] = float(line_el[11])
                        soscoeffs[n,4] = float(line_el[8])
                        soscoeffs[n,5] = float(line_el[9])
                    else:
                        line = next(file)
                        line_el = line.split()
                        soscoeffs[n,1] = float(line_el[2])
                        soscoeffs[n,2] = float(line_el[3])
                        soscoeffs[n,4] = float(line_el[0])
                        soscoeffs[n,5] = float(line_el[1])
                soscoeffs[0,:] = np.multiply(soscoeffs[0,:], np.array([gain, gain, gain, 1, 1, 1]))
                filterbank_index = 1
                while not re.match(fname, out[filterbank_index].name):
                    filterbank_index += 1
                out[filterbank_index].filters[index] = out[filterbank_index].filters[index]._replace(name=mname)
                out[filterbank_index].filters[index] = out[filterbank_index].filters[index]._replace(soscoef=soscoeffs)
    return out`

And converting this into a ZPK scipy object:
`def readFilterSys(filename, bank, module, **kwargs):
    """Read a filter system from a file and return a ZPK filter and pfilt (a structure containing the filter info from the file)

    Parameters
    ----------
    filename : `str`
        Path and filename of FOTON filter file
    bank : `str`
        Name of the filter bank
    module : `int`, array-like
        Module numers ranging from 1 to 10
    data : array-like, optional
        Array containing [filename, filter .. filter]. This is passed as an optional argument in case
        the file has already been read once and you don't want to spend more I/O time re-reading this
        again

    Returns
    -------
    sysd : :obj:`scipy.signal.ZerosPolesGain`
        ZPK object of the requested FOTON filters
    pfilt : array-like
        Data from the FOTON filter file. 
        Passing this back to the same function speeds up searching more filters in the file
    """

    if len(module)==0:
        sysd = signal.ZerosPolesGain([],[],1, dt=1.0/2**14)
        if len(kwargs)>0 and kwargs['data']:
            pfilt = kwargs['data']
        else:
            pfilt = []
    else:
        if len(kwargs)==0 or not kwargs['data']:
            pfilt = readFilterFile(filename)
        elif len(kwargs)>0 and kwargs['data']:
            pfilt = kwargs['data']
            if not re.match(filename, pfilt[0]):
                raise ValueError('Wrong filter filename when using optional data input')
        filterbank_index = 1
        while not re.match(bank, pfilt[filterbank_index].name) and filterbank_index<len(pfilt):
            filterbank_index += 1
        if not re.match(bank, pfilt[filterbank_index].name):
            raise ValueError('There was no bank with this name in the filter file')
        sysd = signal.ZerosPolesGain([],[],1, dt=1.0/pfilt[filterbank_index].filters[module[0]-1].fs)
        for n in range(0, len(module)):
            index = module[n] - 1
            #[zd,pd,kd] = signal.sos2zpk(pfilt[filterbank_index].filters[index].soscoef)  #removed because this because it is not like Matlab
            [z,p,k] = sos2zp(pfilt[filterbank_index].filters[index].soscoef)  # This follows the Matlab function sos2zp()
            sysd.zeros = np.append(sysd.zeros, z)
            sysd.poles = np.append(sysd.poles, p)
            sysd.gain *= k
    return sysd, pfilt`

An example FOTON filter file is attached. 
[H1SUSETMY_1157571155.txt](https://github.com/gwpy/gwpy/files/2298820/H1SUSETMY_1157571155.txt)

**Comment by eagoetz** [comment]
And in case you want to know about that sos2zp() function:
`def sos2zp(sos):
    """Replicate the MATLAB version of sos2zp because the scipy version is not like the MATLAB version

    Parameters
    ----------
    sos : `float`, array-like
        Second order sections

    Returns
    -------
    z : `float`
        Zeros of the ZPK filter
    p : `float`, array-like
    """

    sos = np.asarray(sos)
    n_sections = sos.shape[0]
    z = np.empty(0, np.complex128)
    p = np.empty(0, np.complex128)
    k = 1
    for section in range(n_sections):
        if sos[section,5]==0 and sos[section,2]==0:
            b = sos[section,0:2]
            a = sos[section,3:5]
        else:
            b = sos[section,0:3]
            a = sos[section,3:6]
        if b[-1]==0 and a[-1]==0:
            b = b[0]
            a = a[0]
        [zt,pt,kt] = signal.tf2zpk(b,a)
        z = np.append(z, zt)
        p = np.append(p, pt)
        k *= kt
    return z, p, k`
