### ISSUE TITLE
TimeSeriesDict should include class method to instantiate from NDS2 buffer list

### ISSUE THREAD

**Issue by jrollins** [gwpy/gwpy#862]
I guess it should look something like this:
```python3
@classmethod
def from_nds2_buffers(cls, bufs):
    tsd = cls()
    for buf in nds2_bufs:
        tsd[buf.channel.name] = TimeSeries.from_nds2_buffer(buf)
    return tsd
```
Instantiation of this class is not well documented, though, so I'm not sure if there's a better way.  Presumably the appropriate code exists internally for handling the fetch() class method.

**Comment by duncanmmacleod** [comment]
@jrollins (as you might have found) the `TimeSeries.from_nds2_buffer` method exists, so it would be a trivial extension to include this in `TimeSeriesDict`. If you don't fancy adapting this yourself, I can have a look at it in the coming weeks.

**Comment by jrollins** [comment]
@duncanmmacleod yes, the from_nds2_buffer() method is what I was using in my example above.

I likely won't be able to get to it in the coming weeks, so if you can please go ahead.

Thanks so much.

**Comment by duncanmmacleod** [comment]
@jrollins, what's the use-case for this; it sounds like you are manually calling `nds2.connection.fetch` and then wrapping into a TSD, in particular, is there a reason not to just use `TimeSeriesDict.get`?

**Comment by jrollins** [comment]
Yes, because I want to control the nds interaction myself and use TimeSeriesDict as a nicer data object than the list of native nds2.Buffer objects returned by nds2-client, for instance in iterate:
```
for bufs in conn.iterate(...):
    tsd = TimeSeriesDict.from_nds2_buffers(bufs)
```
