### ISSUE TITLE
FrequencySeries should support logarithmic spacing

### ISSUE THREAD

**Issue by jrollins** [gwpy/gwpy#863]
Logarithmic spacing for frequency arrays is very common, and it would be great if this was supported for compatibility purposes.

**Comment by duncanmmacleod** [comment]
@jrollins, a `FrequencySeries` can be created with a specified set of frequencies:

```python
>>> import numpy
>>> from gwpy.frequencyseries import FrequencySeries
>>> fs = FrequencySeries(numpy.random.random(100), frequencies=numpy.logspace(1, 3, num=100))
>>> plot = fs.plot()
>>> plot.show()
```

![fs-log](https://user-images.githubusercontent.com/1618530/44206499-efa83000-a151-11e8-814d-1044c6636003.png)

Is there something else that is required, or something that doesn't work when using log-spaced frequencies? Or is it just that the documentation isn't very complete so you didn't know this was an option?

**Comment by duncanmmacleod** [comment]
@jrollins, I didn't get a response to your original post, so I am closing this issue. Please reopen if required.
