### ISSUE TITLE
TimeSeries{,Dict} objects should include method for GPS start/stop times

### ISSUE THREAD

**Issue by jrollins** [gwpy/gwpy#864]
It would be great if both the TimeSeries and TimeSeriesDict objects included methods that return the GPS start and stop of the segment.  A tuple of the form [start, stop) would be good.

**Comment by duncanmmacleod** [comment]
@jrollins, the `TimeSeries` object has a `.span` property that fills this request:

```python
>>> from gwpy.timeseries import TimeSeries
>>> a = TimeSeries(range(10))
>>> print(a.span)
[0.0 ... 10.0)
>>> print(a.span[0], a.span[1])
(0.0, 10.0)
```

The `TimeSeriesDict` currently doesn't have anything like that, but one could easily be formed on-the-fly.

If these answers are satisfying, please close the ticket.

**Comment by jrollins** [comment]
Oh yes .span() is quite useful.  Could that property be added to TimeSeriesDict as well?
