### ISSUE TITLE
TimeSeries.whiten() can easily introduce filter transients

### ISSUE THREAD

**Issue by alurban** [gwpy/gwpy#867]
While putting together the [`gwdetchar-omega`](https://github.com/gwdetchar/gwdetchar) tool, I discovered that in many cases the default whitening scheme in GWPy can easily introduce filter transients in many channels. An example is shown below:

![170817_old_whitening](https://user-images.githubusercontent.com/5273800/44008482-1c4fc344-9e59-11e8-8104-f0ad5010043a.png)

These data are from the Livingston calibration channel `L1:CAL-PCALY_RX_PD_OUT_DQ` near the time of binary neutron star merger GW170817. This channel shows reflected laser light in the photon calibrator at the Y-end station, which we use to independently monitor the calibration lines. To make this plot I used the default whitening with `fftlength=2`, `overlap=1`. Clearly, there are filter transients that recur once per overlap (i.e. once per second) near 330 and 1087 Hz, which are the locations of two of the calibration lines.

As @andrew-lundgren pointed out in #358, this behavior is not ubiquitous but it is relatively common. I believe it can be remedied by allowing users to select an alternative whitening scheme that designs and uses an FIR filter, similar to the one in [PyCBC](http://pycbc.org/pycbc/latest/html/_modules/pycbc/types/timeseries.html#TimeSeries.whiten), which is based on [FINDCHIRP](https://arxiv.org/abs/gr-qc/0509116).

I have coded this up and will post a merge request momentarily.

**Comment by alurban** [comment]
For comparison, I've remade this Q-scan using the FIR whitening scheme, which does not produce these filter transients:

![170817_new_whitening](https://user-images.githubusercontent.com/5273800/44010276-453601f8-9e66-11e8-845a-2f1823c9c6e2.png)

**Comment by jaideep11061982** [comment]
which parameter is to chose whitening scheme.
