### ISSUE TITLE
gwpy-plot no longer accepts relative epoch

### ISSUE THREAD

**Issue by areeda** [gwpy/gwpy#881]
--epoch is treated as an absolute time.  We used to be able to set it relative to start time.

**Comment by duncanmmacleod** [comment]
@areeda, please confirm that this was fixed by #882.

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/881, please join us on gitlab to continue your contribution!
