### ISSUE TITLE
Online help for get_event_urls() does not mention the "tag=" option

### ISSUE THREAD

**Issue by ecm0** [gwpy/gwpy#888]
Would be helpful to add the "tag=" option to the online help:

Signature: get_event_urls(event, format='hdf5', sample_rate=4096, **match)
Docstring: <no docstring>
File:      ~/anaconda2_501/lib/python2.7/site-packages/gwosc/locate.py
Type:      function

**Comment by duncanmmacleod** [comment]
@ecm0, should this issue have been posted in https://github.com/gwpy/gwosc?
