### ISSUE TITLE
Writing .gwf files

### ISSUE THREAD

**Issue by vivienr** [gwpy/gwpy#889]
The documentation https://gwpy.github.io/docs/stable/timeseries/io.html#id2 could mention how one specifies a channel when writing to a .gwf file. As shown below, my naive attempt did not succeed:

```
(gw) vflr:sandbox vivien$ lalframe_version 
LAL: 6.18.0.1-dev20180904 (CLEAN 48386bc466afcd0f9af14b2c30e3ea0d5ae74746)
LALFrame: 1.4.3.1-dev20180904 (CLEAN 48386bc466afcd0f9af14b2c30e3ea0d5ae74746)
(gw) vflr:sandbox vivien$ python
Python 2.7.15 (default, May  2 2018, 00:53:27) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gwpy
>>> gwpy.__version__
u'0.12.0'
>>> from numpy.random import random
>>> from gwpy.timeseries import TimeSeries
>>> t = TimeSeries(random(1000))
>>> t.channel='H1:not_a_real_channel'
>>> t.write('not_real_data.gwf')
>>> ^D
(gw) vflr:sandbox vivien$ FrDump -i not_real_data.gwf 
-----------Parameters used--------------
  Input  Files: not_real_data.gwf
  First frame  : 0 0 (GPS=0.0)
  Last  frame  : 2147483647 2147483647 (GPS=2147483647.0)
  Debug level  : 1
 Dump all Frame info
----------------------------------------
not_real_data.gwf	0 1000  0 0
File(s) summary:
 1 Frames in the requested time range (0 to 10000000000 (GPS))
     First frame start at:0 (UTC:Sun Jan  6 00:00:19 1980) length=1000.00s.
        Last frame end at:1000 (UTC:Sun Jan  6 00:16:59 1980) length=1000.00s.
 ADC :     0 type of AdcData :
 Ser :     0 type of SerData :
 Proc:     1 type of ProcData: 
 Sim :     0 type of SimData :
 Detector: 1 type of Detector: GEO_600
 StatData: 0 type of StatData:
 Event   : 0 Types of event in the file
 Simulated Event   : 0 Types of event in the file
(gw) vflr:sandbox vivien$ 
```

**Comment by duncanmmacleod** [comment]
It turns out that this is _only_ an issue when using `lalframe` as the GWF backend, rather than `LDAStools.frameCPP`. However, this has been fixed in #904.

**Comment by duncanmmacleod** [comment]
@vivienr, the `FrDetectors` shouldn't really make any difference, you should still be able to read your data out of the GWF file. Can you confirm whether that works?

**Comment by vivienr** [comment]
@duncanmmacleod with the example below, I get now LHO_4k as detector, but still an empty channel name:
```
$ FrDump -i not_real_data.gwf 
-----------Parameters used--------------
  Input  Files: not_real_data.gwf
  First frame  : 0 0 (GPS=0.0)
  Last  frame  : 2147483647 2147483647 (GPS=2147483647.0)
  Debug level  : 1
 Dump all Frame info
----------------------------------------
not_real_data.gwf	0 1000  0 0
File(s) summary:
 1 Frames in the requested time range (0 to 10000000000 (GPS))
     First frame start at:0 (UTC:Sun Jan  6 00:00:19 1980) length=1000.00s.
        Last frame end at:1000 (UTC:Sun Jan  6 00:16:59 1980) length=1000.00s.
 ADC :     0 type of AdcData :
 Ser :     0 type of SerData :
 Proc:     1 type of ProcData: 
 Sim :     0 type of SimData :
 Detector: 1 type of Detector: LHO_4k
 StatData: 0 type of StatData:
 Event   : 0 Types of event in the file
 Simulated Event   : 0 Types of event in the file
```

**Comment by duncanmmacleod** [comment]
@vivienr, the issue here is that your `TimeSeries` doesn't have a `name` attribute, which is what is actually written in to the TOC. If you add that attribute you should get the output you expect, please confirm.

I will have a look at mapping the `channel` over to `name` when no `name` is provided.

**Comment by vivienr** [comment]
Indeed, that works. What is the purpose of the `channel` attribute of a `TimeSeries` then? If `.name` should be used, it may be good add a mention of that on https://gwpy.github.io/docs/stable/timeseries/io.html#id2 ...

**Comment by duncanmmacleod** [comment]
In general the `channel` is used to document the source of the data. When reading GWF both the `name` and `channel` attributes are copied from the same input. When writing GWF the `channel` is used to identify the detectors for the `FrHeader`, but the `name` is used to populate the TOC.

I am preparing an update to the documentation that describes this.

**Comment by vivienr** [comment]
Thanks ! So in practice, the `channel` and `name` are the same string almost always...

**Comment by duncanmmacleod** [comment]
@vivienr, when reading from GWF that is true.
