### ISSUE TITLE
Length of whitened output TimeSeries (version 0.12.0)

### ISSUE THREAD

**Issue by mbejger** [gwpy/gwpy#907]
I have a problem with the length of whitened output TimeSeries, for example:  
```
import numpy as np
from gwpy.timeseries import TimeSeries 

a = TimeSeries(np.random.random(2048), sample_rate=128)
b = a.whiten()
print(len(a), len(b))
```
I get 
```
(2048, 1792)
```
Is this a desired behavior? Naively I would expect that the output should be of the same length as the input. Also, output length changes with the `sample_rate`.

**Comment by duncanmmacleod** [comment]
@mbejger, yes the difference in output series length is a deliberate change for gwpy-0.12.0. However, this decision has been reversed for gwpy-0.12.1, so when that release is finalised (tomorrow), you should see the input and output match (in size).

I'll leave this ticket open until you can verify this independently.

**Comment by duncanmmacleod** [comment]
@mbejger, gwpy-0.12.1 has been released, can you test whether the updated code does what you expect it to?

**Comment by kentblackburn** [comment]
Using GWPY 0.15.0 under Python 3.6 on SL 7 Linux, I get an error when reading hdf5 files mounted over NSF using "strain = TimeSeries.read(fn,format='hdf5.losc')" type calls. I have communicated this with Duncan via email and was advised to use "export HDF5_USE_FILE_LOCKING=FALSE", which resolved the issue. However, both Alan Weinsten and Eric Chassande-Mottin felt that an issue ticket should be filed as they were not satisfied with having to setup an environment variable. I personally have no issue with the env soln, but I'm not my own boss. ;-)
