### ISSUE TITLE
command line time series Y-axis labeling issue

### ISSUE THREAD

**Issue by areeda** [gwpy/gwpy#91]
The default plot for a constant function with a value of 10 gives
![tsaxis1](https://cloud.githubusercontent.com/assets/7607564/7938121/c1d19260-08f8-11e5-9779-b020e08f823f.png)
Setting y-axis minimum to -11 gives an error.

Setting the y-axis limits to 0, 11 gives
![tsaxis2](https://cloud.githubusercontent.com/assets/7607564/7938130/ca86ee5a-08f8-11e5-8319-21bb231781bf.png)

**Comment by duncanmmacleod** [comment]
this hasn't been touched in a while.
