### ISSUE TITLE
Unable to access data

### ISSUE THREAD

**Issue by GregoryAshton** [gwpy/gwpy#916]
Prior to the change from LOSC to GWOSC, the following script ran without failing

```python 
from gwpy.timeseries import TimeSeries
gw150914_gpstime = 1126259462 
dT = 100
hdata = TimeSeries.fetch_open_data('H1', gw150914_gpstime+dT, gw150914_gpstime+10+dT)
```

This tried to download 10 seconds of data which is 100 seconds prior to GW150914. 

It now returns the following error

```python
OSError: Failed to read LOSC data from 'https://openscience-dev.ligo.caltech.edu/archive/data/O1/1126170624/H-H1_LOSC_4_V1-1126256640-4096.hdf5': Unable to open file (file signature not found)
```

I've looked at many different times to check that this just doesn't happen to coincide with non-science-mode data. So, I feel it is most likely a GWOSC issue still, but I'm unsure how to go about testing that.

**Comment by duncanmmacleod** [comment]
@GregoryAshton, the problem is that the GWOSC API is returning private URLs for your (public) request, so GWpy can't read them properly (the request gets redirected). I have reported this to GWOSC, and will report back here when it is resolved.

**Comment by GregoryAshton** [comment]
Thanks kindly Duncan.

**Comment by duncanmmacleod** [comment]
@GregoryAshton, I believe this has been resolved upstream by the GWOSC team. Please confirm and close the ticket if appropriate. Thanks.
