### ISSUE TITLE
TimeSeries.read fails with "AttributeError: 'buffer' object has no attribute 'ndim'"

### ISSUE THREAD

**Issue by RorySmith** [gwpy/gwpy#93]
Failure occurred for 

"TimeSeries.read(c, H1_CHANNEL)"

where the cache, c = H H1_HOFT_C00 1117003776 4096 file://localhost/data/node427/frames/ER7/hoft/H1/H-H1_HOFT_C00-11170/H-H1_HOFT_C00-1117003776-4096.gwf

and H1_CHANNEL = H1:GDS-CALIB_STRAIN

**Comment by duncanmmacleod** [comment]
I think this is a problem with the way the framecpp library has been compiled (that it's failing to find the `numpy/arrayobject.h` headers). I have a PR for a workaround almost ready to go.

Which installation of GWpy are you using for the above? Is it your own, or the shared installation on `~detchar` at the LDG sites?

**Comment by RorySmith** [comment]
It's the shared installation.

Thanks!
Rory

**Comment by duncanmmacleod** [comment]
PR #92 has been merged, and I have updated the shared installation at CIT. @RorySmith: please confirm you no longer see this bug, and close this issue if appropriate.

**Comment by RorySmith** [comment]
I no longer see the bug, but I have a new error:

Traceback (most recent call last):
   File "get_data.py", line 29, in <module>
     data = TimeSeries.read(c, H1_CHANNEL)[0:dur*4096*4 + 1]
   File 
"/mnt/qfs5/detchar/opt/gwpysoft/lib64/python2.6/site-packages/astropy/io/registry.py", 
line 327, in read
     'read', cls, path, fileobj, args, kwargs)
   File 
"/mnt/qfs5/detchar/opt/gwpysoft/lib64/python2.6/site-packages/astropy/io/registry.py", 
line 412, in _get_valid_format
     "{0}".format(format_table_str))
Exception: Format could not be identified.
The available formats are:
  Format  Read Write Auto-identify
-------- ---- ----- -------------
    cache  Yes    No           Yes
      csv  Yes   Yes           Yes
framecpp  Yes    No            No
      gwf  Yes    No            No
      hdf  Yes   Yes           Yes
lalframe  Yes    No            No
      lcf  Yes    No           Yes
     losc  Yes    No            No
      txt  Yes   Yes           Yes

**Comment by duncanmmacleod** [comment]
@RorySmith, what type of object is `c`, is it a `glue.lal.CacheEntry`? PR #94 might resolve this issue, which I can push onto the shared installations sometime soon.

**Comment by duncanmmacleod** [comment]
you can always manually specify the format of your GWF source, as follows:

```
data = TimeSeries.read(c, H1_CHANNEL, format='gwf')
```

and you can also manually choose between `format='lalframe'` and `format='framecpp'` if you have a frame library preference. The 'gwf' format chooses either library depending on which is available.

**Comment by RorySmith** [comment]
Specifying the format resolved the issue, thanks!
