### ISSUE TITLE
gwpy-plot custom port setting?

### ISSUE THREAD

**Issue by SeanDS** [gwpy/gwpy#931]
I want to plot something from a frame builder behind a router, so I have opened up an SSH tunnel on a custom port. The `gwpy-plot` utility seems to lack a way to set the port in the call:
```bash
gwpy-plot timeseries --chan "MY_CHANNEL" --start "2018-10-01" --duration 1d -n "my-router"
```

Since the port I chose is not a standard NDS one, I need to explicitly set it.

**Comment by duncanmmacleod** [comment]
@SeanDS, I will work on patching this such that you can specify `-n host:port`, would that solve your problem?

In the mean time I think you should be able to work around this via the `NDSSERVER` environment variable:

```
env NDSSERVER=host:port gwpy-plot timeseries ...
```

Please confirm that this works for you.

**Comment by SeanDS** [comment]
Thanks. I can confirm that specifying it in the `NDSSERVER` environment variable works.

**Comment by duncanmmacleod** [comment]
Thanks @SeanDS, I will leave this ticket open until I get around to implementing something properly.

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/931, please join us on gitlab to continue your contribution!
