### ISSUE TITLE
Pad data in gwpy-plot

### ISSUE THREAD

**Issue by SeanDS** [gwpy/gwpy#947]
It would be nice to have the ability to specify that missing data be padded in the CLI. Right now I don't see a way to do this.

**Comment by areeda** [comment]
Sean, we probably can add that for NDS ata transfers but until then see https://www.lsc-group.phys.uwm.edu/daswg/projects/nds-client/doc/manual/ch04s02.html for how to control gap filling with environment variables.

**Comment by SeanDS** [comment]
Ok, I'll use that gap filling variable for now, thanks.

**Comment by duncanmmacleod** [comment]
@areeda, can we close this issue, or should we leave it open as a feature request?

**Comment by duncanmmacleod** [comment]
Migrated to https://gitlab.com/gwpy/gwpy/-/issues/947, please join us on gitlab to continue your contribution!
