### ISSUE TITLE
read/write gwf files with TimeSeries

### ISSUE THREAD

**Issue by matxil** [gwpy/gwpy#959]
Hi, 

Following some GWpy examples, I tried to write and then read data after getting it with 

```python
from gwpy.timeseries import TimeSeries
data = TimeSeries.fetch_open_data('L1', 968654552, 968654562)
```

So, I write the data in two formats: 

```python
data.write("writtenFile_L1.hdf5", "hdf5")
data.write('writtenFile_L1.gwf')
```

And then try to read it with: 
```python
data_1 = TimeSeries.read('writtenFile_L1.hdf5')
data_2 = TimeSeries.read('writtenFile_L1.gwf') 
```

Reading the hdf5 file goes fine, but reading the gwf file gives me the error message: 
```pytb
read_timeseries() takes at least 2 arguments (1 given)
```

From the documentation, I get one normally has to give the data-channel as well (although with hdf5 files that's not necessary), so I tried both: 
```
data_2 = TimeSeries.read('writtenFile_L1.gwf','L1:LDAS-STRAIN') 	
data_2 = TimeSeries.read('writtenFile_L1.gwf','L1:GWO-STATE_VECTOR')
```
but both cases give me an XLAL error, e.g.: 

```
Channel L1:LDAS-STRAIN not found
```

Is there a way to see all available data-channels in a gwf file or should I just restrict myself to only using hdf5 files?

Best regards, 

Machiel

**Comment by duncanmmacleod** [comment]
Hi @matxil, thanks for your post (I hope you don't mind that I modified the formatting to use python syntax highlighting, which IMO makes it a little easier to read).

To answer your last question(s) first, there absolutely is a way to see the channels in a GWF file. If we write your file as above:

```python
>>> from gwpy.timeseries import TimeSeries
>>> data = TimeSeries.fetch_open_data('L1', 968654552, 968654562)
>>> data.write('writtenFile_L1.gwf')
```

we can use the following to read the channel list from the new file:

```python
>>> from gwpy.io.gwf import get_channel_names
>>> print(get_channel_names('writtenFile_L1.gwf'))
['Strain']
```

However, this requires the python-ldas-tools-framecpp client, which is (currently) only available for Debian or RHEL (linux) operating systems, or macports. You can also see the channels inside a GWF using the `FrChannels` command-line tool (from the `libframe` package, available from conda-forge):

```bash
$ FrChannels writtenFile_L1.gwf
Strain 4096
```

So, to fix your original problem, you need to pass the `'Strain'` channel name to the GWF read function:

```python
>>> data_2 = TimeSeries.read('writtenFile_L1.gwf', 'Strain') 
>>> print(data_2)
TimeSeries([-2.86995824e-17, -2.77331804e-17, -2.67514139e-17,
            ...,  2.45383713e-18,  1.45996126e-18,
             4.54385209e-19]
           unit: dimensionless,
           t0: 968654552.0 s,
           dt: 0.000244140625 s,
           name: Strain,
           channel: Strain)
```

If the information I have provided resolves your issue, please close this ticket. If it doesn't, please just post back and I'll try and update my posts.

**Comment by matxil** [comment]
Hi Duncan, 

Thanks for your very complete reply. Yes, now it works. 
I haven't tried running FrCHannels because I'll first have to install conda. 
In any case I will close this ticket. Thanks for your help. 
One question: what is more recomendable to use: hdf5 or gwf files?

**Comment by duncanmmacleod** [comment]
@matxil, I would recommend HDF5, mainly because the `h5py` library is much easier to install than a the GWF library required by GWpy (`ldas-tools-framecpp`).
