### ISSUE TITLE
gwpy.plot not found

### ISSUE THREAD

**Issue by matxil** [gwpy/gwpy#961]
The following line: 
`from gwpy.plot import Plot`
gives me the following error: 
`ImportError: No module named plot`

The TimeSeries module of gwpy I can import without problems

**Comment by duncanmmacleod** [comment]
@matxil, which version of gwpy do you have installed:

```python
>>> import gwpy
>>> print(gwpy.__version__)
```

`gwpy.plot` was introduced first in `gwpy-0.12.0`

**Comment by matxil** [comment]
It says: 0.9.0, so that explains it. 
The way it was installed was a part of my pycbc installation. 
So, I guess I should either install GWpy outside my pycbc environment, or maybe there is an alternative way to use the same plotting methods?

I want to do the following thing. Maybe that is possible with the TimeSeries.plot command as well?
```
plot = Plot(data, white, separate=True, sharex=True)
plot.axes[0].set_ylabel('Y-arm power [counts]', fontsize=16)
plot.axes[1].set_ylabel('Whitened amplitude', fontsize=16)
plot.show()

```

**Comment by duncanmmacleod** [comment]
In older versions of gwpy, you can use something like:

```python
from gwpy.plotter import Plot
plot = Plot(data, white, sep=True, sharex=True)
...
```

If that works, please close this ticket.

**Comment by matxil** [comment]
It gives me: 
`TypeError: __init__() got an unexpected keyword argument 'sharex'`

**Comment by duncanmmacleod** [comment]
oh, right, back in `gwpy-0.9.0` there were a number of different plot classes, so you needed to pick the right one:

```python
from gwpy.plotter import TimeSeriesPlot
plot = TimeSeriesPlot(data, white, sep=True, sharex=True)
```

hopefully that works.

**Comment by matxil** [comment]
Yes, it does. Thank you very much.
