### ISSUE TITLE
Documentation TimeSeriesPlot

### ISSUE THREAD

**Issue by matxil** [gwpy/gwpy#962]
Is there a page which documents all methods for TimeSeriesPlot? I saw a few pages about TimeSeriesPlot but not with a full list of all available methods. 
For instance, I know that some plotting modules have the possibility to call "draw()" instead of "show()" to avoid blocking the program but is there something like that for TimeSeriesPlot?
Or is TimeSeriesPlot really outdated, and should I just update to a later version of GWpy?

**Comment by duncanmmacleod** [comment]
@matxil, the documentation for gwpy-0.9.0 is still available here:

https://gwpy.github.io/docs/0.9.0/

In particular for the old `gwpy.plotter` module here:

https://gwpy.github.io/docs/0.9.0/plotter/

I do encourage you to upgrade your gwpy installation, as we can't offer any support for bugs found in the old releases, we would just tell you to upgrade anyway.

**Comment by matxil** [comment]
Thank you. Okay, I will do an upgrade. 
The GWpy I have was part of the PyCBC installation, so I guess I shouldn't touch that one, it might mess pycbc, but I will try to installing it on the side.

**Comment by duncanmmacleod** [comment]
you should be able to create your own conda environment or virtualenv that includes both gwpy and pycbc.

**Comment by duncanmmacleod** [comment]
> Yes, but wouldn't a later version of gwpy than the one pycbc is using now cause problems?

No, not necessarily. It's just that pycbc haven't kept up-to-date.

> By the way, I looked at the pages you forwarded me to, but I am not sure I am looking the correct way. For instance, here:
https://gwpy.github.io/docs/0.9.0/plotter/api.html#gwpy.plotter.TimeSeriesPlot
I only see TimeSeriesPlot has 4 methods. Surely, it has more?

That page is only showing the _new_ methods for that object. If you walk back through the _Bases_ (e.g. `SeriesPlot`) you can pick up more and more methods. In general the gwpy `*Plot` objects are just `matplotlib.figure.Figure` objects.

**Comment by matxil** [comment]
Thank you, I will try out the things you suggested.
