### ISSUE TITLE
Using a non-tuple sequence for multidimensional indexing is deprecated

### ISSUE THREAD

**Issue by matxil** [gwpy/gwpy#963]
I am trying to follow the example in [https://gwpy.github.io/docs/stable/examples/signal/gw150914.html](url)

After the following lines in the code
```
notches = [filter_design.notch(line, hdata.sample_rate) for line in (60, 120, 180)]
zpk = filter_design.concatenate_zpks(bp, *notches)
hfilt = hdata.filter(zpk, filtfilt=True)

```
I get the warning: 
`Using a non-tuple sequence for multidimensional indexing is deprecated; use "arr[tuple(seq)]" instead of "arr[seq]"`

**Comment by duncanmmacleod** [comment]
@matxil, I believe that this warning comes from `scipy`, and not from gwpy itself. If you are using numpy>=1.15.0 and scipy <= 1.2.0 (which hasn't been released yet), you will get this warning, but it is harmless and can be ignored.

**Comment by matxil** [comment]
ok, thanks.
