### ISSUE TITLE
Not able to make the plot using plot = hdata.plot() in the second tutorial of gwpy. The notebook gives the following error,

### ISSUE THREAD

**Issue by zaidzaz** [gwpy/gwpy#964]

**Comment by zaidzaz** [comment]
The Error,
AttributeError                            Traceback (most recent call last)
~/anaconda3/lib/python3.7/site-packages/gwpy/plot/plot.py in _init_figure(self, **kwargs)
    127         try:
--> 128             manager = backend_mod.new_figure_manager_given_figure(num, self)
    129         except AttributeError:

AttributeError: module 'ipykernel.pylab.backend_inline' has no attribute 'new_figure_manager_given_figure'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-9-3e790ffc525f> in <module>()
----> 1 plot = hdata.plot()

~/anaconda3/lib/python3.7/site-packages/gwpy/timeseries/core.py in plot(self, method, figsize, xscale, **kwargs)
    583         """
    584         kwargs.update(figsize=figsize, xscale=xscale)
--> 585         return super(TimeSeriesBase, self).plot(method=method, **kwargs)
    586 
    587     @classmethod

~/anaconda3/lib/python3.7/site-packages/gwpy/types/series.py in plot(self, method, **kwargs)
    422 
    423         # make plot
--> 424         plot = Plot(self, method=method, **kwargs)
    425 
    426         # set default y-axis label (xlabel is set by Plot())

~/anaconda3/lib/python3.7/site-packages/gwpy/plot/plot.py in __init__(self, *data, **kwargs)
    105         figure_kw = {key: kwargs.pop(key) for key in utils.FIGURE_PARAMS if
    106                      key in kwargs}
--> 107         self._init_figure(**figure_kw)
    108 
    109         # initialise axes with data

~/anaconda3/lib/python3.7/site-packages/gwpy/plot/plot.py in _init_figure(self, **kwargs)
    129         except AttributeError:
    130             canvas = backend_mod.FigureCanvas(self)
--> 131             manager = backend_mod.FigureManagerBase(canvas, 1)
    132         manager._cidgcf = manager.canvas.mpl_connect(
    133             'button_press_event',

AttributeError: module 'ipykernel.pylab.backend_inline' has no attribute 'FigureManagerBase'

**Comment by duncanmmacleod** [comment]
@zaidzaz, thanks for your report, can you give a little bit more information on how you produced this error? From the traceback it looks like you were running in a jupyter notebook? Can you post here the version of matplotlib, jupyter-notebook, and gwpy, and the code you were trying to run within the notebook?

**Comment by zaidzaz** [comment]
@duncanmmacleod Thank you for your reply. Yes, I am using the Jupyter notebook. The version of matplotlib I am using is, 3.0.2, gwpy  version is 0.12.2. python version is 3.7. I have been attempting to do the 2nd gwpy tutorial of the LOSC workshop which was appended to your introductory talk on gwpy

**Comment by duncanmmacleod** [comment]
@zaidzaz, presuming you mean [this notebook](https://github.com/gw-odw/odw-2018/blob/master/gwpy/1%20-%20Open%20Data%20access%20with%20GWpy.ipynb), I will take a look myself with the same versions as you posted and will confirm whether I can reproduce the problem.

**Comment by zaidzaz** [comment]
@duncanmmacleod yes, This is the one..
