### ISSUE TITLE
gwpy asking for kerberos authentication even though none required

### ISSUE THREAD

**Issue by jrollins** [gwpy/gwpy#968]
The LDAS clusters are configured with internal NDS2 servers that do not require authentication when accessed from within the cluster.  The server is specified in the NDSSERVER environment variable:
```
ldas-pcdev1:~ 0$ echo $NDSSERVER
nds.ldas.cit:31200
ldas-pcdev1:~ 0$ 
```
This configuration and variable are available in all LIGO LDAS clusters (CIT, LHO, LLO).  When gwpy is using NDS in these environments it should just use/try these servers first.

This will be particularly useful in the context of the CIT jupyterhub service.

NOTE: the latest release of the nds2-client recognizes the NDSSERVER variable automatically, so specifying the server is not necessary.

**Comment by duncanmmacleod** [comment]
@jrollins, thanks for your report. All connections to `nds2` are handled internal to gwpy in `gwpy.io.nds2.auth_connect`:

https://github.com/gwpy/gwpy/blob/37af13168eac46386163d57c82f9ca684d12f48f/gwpy/io/nds2.py#L297-L332

As you can see the kerberos credentials are only required if a connection fails with a specific error message. From an SSH connection to ldas-pcdev1.ligo.caltech.edu I can get this result:

```shell
$ kdestroy
$ klist
klist: No credentials cache found (filename: /tmp/krb5cc_5308)
$ echo $NDSSERVER
nds.ldas.cit:31200
$ python -c "import nds2; nds2.connection()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/nds2.py", line 3171, in __init__
    _nds2.connection_swiginit(self, _nds2.new_connection(*args))
NotImplementedError: Wrong number or type of arguments for overloaded function 'new_connection'.
  Possible C/C++ prototypes are:
    connection::connection(connection::host_type const &,connection::port_type,connection::protocol_type)
    connection::connection(connection::host_type const &,connection::port_type)
    connection::connection(connection::host_type const &)
    connection::connection(parameters const &)

$ python -c "import nds2; nds2.connection('nds.ldas.cit', 31200)"
$ python -c "from gwpy.io import nds2 as io_nds2; io_nds2.auth_connect('nds.ldas.cit', 31200)"
```

(i.e. no error). I get the same result from jupyter.ligo.caltech.edu (python2.7.5 [Long Term - SL7]).

Can you post a reproducable example of the problem you are seeing?

**Comment by jrollins** [comment]
Huh, well, when I try now I get no authentication prompt:
```
In [1]: from gwpy.timeseries import TimeSeries
In [2]: ts = TimeSeries.fetch('L1:GRD-IFO_OK', 1164554240, 1164554241)
In [3]: 
```
So maybe this was some other NDS exception that was caught, prompting trying on a different server?
Is there a way to tell gwpy to *not* try other servers?  (Any other server should just be a subset of what's available at CIT, so when working at CIT I would prefer to not try other servers and to instead just see the NDS errors.)

I wish NDS wasn't so flaky...
