### ISSUE TITLE
AttributeError when reading GW170814 data in HDF5 format

### ISSUE THREAD

**Issue by matxil** [gwpy/gwpy#971]
Hi, 
I downloaded some data files from https://www.gw-openscience.org/events/GW170814/
and then tried to read them in a python code, using this:
`hdata = TimeSeries.read('H-H1_LOSC_C00_4_V1-1186741845-32.hdf5')`
It gives me the error: 
`ValueError: Please specify the HDF5 path via the ``path=`` keyword argument`

With hdfview, I saw the file contains a subfolder called strain, so I tried
`hdata = TimeSeries.read('H-H1_LOSC_C00_4_V1-1186741845-32.hdf5', path='strain')`
which gives me the error: 
`AttributeError: 'tuple' object has no attribute 'encode'`

How can I fix this?

Cheers, 

Machiel

**Comment by matxil** [comment]
As an alternative, the following works fine for me: 
`    hdata = TimeSeries.fetch_open_data('H1', 1186741845, 1186741877, tag='C00')`
`    hdata.write("H1_1186741845_32s.hdf5", "hdf5")`

And the next time I use the code, I can read the file in with the following without a problem:
`    hdata = TimeSeries.read('H1_1186741845_32s.hdf5') `

**Comment by duncanmmacleod** [comment]
@matxil, the problem is that the GWOSC HDF5 files use a separate internal storage layout, so by default you need to use the `format='hdf5.losc'` keyword when reading LOSC files directly with `TimeSeries.read`.

Apologies for the delay in responding.

**Comment by matxil** [comment]
Hi Duncan, 

Thank you very much. This works perfectly.
