### ISSUE TITLE
ImportError:no module named nds2

### ISSUE THREAD

**Issue by lhm315** [gwpy/gwpy#982]
```python
from gwpy.timeseries import TimeSeries
hoft = TimeSeries.get('L1:GDS-CALIB_STRAIN', 1172489751, 1172489815)
aux = TimeSeries.get('L1:PSL-ISS_PDA_REL_OUT_DQ', 1172489751, 1172489815)
```

When running in pycharm, no module named nds2 appears, what is the reason?What is the role of TimeSeries.get()?I am a newcomer to the gravitational wave. I hope the teacher will give you an answer. Thank you.

**Comment by lhm315** [comment]
Thank you very much for your answer. I am not a member of KAGRA-LIGO-Virgo. I am manually installing nsd2 on a Linux system today. Is there any other way to use nsd2?

**Comment by duncanmmacleod** [comment]
As a non-collaboration member, you can't use nds2 for data access. However, you can still access data provided through the Gravitational-Wave Open Science Centre (GWOSC). See [this page](https://gwpy.github.io/docs/stable/timeseries/remote-access.html) for some more details on how to use GWpy to access open data, or look at any of the [examples](https://gwpy.github.io/docs/stable/examples/index.html) that use `TimeSeries.fetch_open_data()`.

If you are able to access data using this method, please close the ticket.

**Comment by lhm315** [comment]
When I run another file, output: no module named lal. Does lal need to be installed manually? Is it necessary to be a member of KAGRA-LIGO-Virgo?

**Comment by duncanmmacleod** [comment]
Can you post the command you are running when you get that error? On Linux you can install LAL using `apt-get install python3-lal` (see [here](https://wiki.ligo.org/Computing/DASWG/DebianJessie)), `conda install -c conda-forge python-lal`, or `pip install lalsuite`.

**Comment by lhm315** [comment]
/usr/bin/python3 "/home/luo/桌面/4 months ago/pycbc-snr/pycbc-snr.py"
/home/luo/.local/lib/python3.6/site-packages/astropy/units/quantity.py:1153: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  out = super(Quantity, self).__getitem__(key)
/home/luo/.local/lib/python3.6/site-packages/scipy/signal/_arraytools.py:45: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  b = a[a_slice]
Traceback (most recent call last):
  File "/home/luo/桌面/4 months ago/pycbc-snr/pycbc-snr.py", line 20, in <module>
    from pycbc.waveform import get_fd_waveform
  File "/home/luo/.local/lib/python3.6/site-packages/pycbc/waveform/__init__.py", line 1, in <module>
    from pycbc.waveform.waveform import *
  File "/home/luo/.local/lib/python3.6/site-packages/pycbc/waveform/waveform.py", line 29, in <module>
    import lal, lalsimulation, numpy, copy
ModuleNotFoundError: No module named 'lal'

**Comment by duncanmmacleod** [comment]
So, this is an issue with `pycbc`, and not `gwpy`, so I recommend you post to https://github.com/gwastro/pycbc/issues`, however, the same solution will be recommended, namely to manually install `lal` (and `lalsimulation`) using one of the above methods.

**Comment by lhm315** [comment]
OK， thank you very much

**Comment by lhm315** [comment]
>>> snr = matched_filter(hp, zoom.to_pycbc(), psd=psd.to_pycbc(),
...                      low_frequency_cutoff=15)
Traceback (most recent call last):
  File "/home/luo/.local/lib/python3.6/site-packages/pycbc/scheme.py", line 173, in scheming_function
    return _import_cache[mgr.state][fn](*args, **kwds)
KeyError: <function correlate at 0x7efc4c05d840>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/luo/.local/lib/python3.6/site-packages/pycbc/filter/matchedfilter.py", line 1309, in matched_filter
    high_frequency_cutoff=high_frequency_cutoff, h_norm=sigmasq)
  File "/home/luo/.local/lib/python3.6/site-packages/pycbc/filter/matchedfilter.py", line 1227, in matched_filter_core
    correlate(htilde[kmin:kmax], stilde[kmin:kmax], qtilde[kmin:kmax])
  File "<decorator-gen-160>", line 2, in correlate
  File "/home/luo/.local/lib/python3.6/site-packages/pycbc/scheme.py", line 187, in scheming_function
    return schemed_fn(*args, **kwds)
  File "/home/luo/.local/lib/python3.6/site-packages/pycbc/filter/matchedfilter_cpu.py", line 134, in correlate_inline
    libraries=omp_libs
  File "/home/luo/.local/lib/python3.6/site-packages/pycbc/weave.py", line 71, in inline
    raise RuntimeError("Oh no! You tried to use capabilities"
RuntimeError: Oh no! You tried to use capabilities we haven't ported to python3 yet

**Comment by alurban** [comment]
@lhm315, looking at the traceback it seems the problem you're seeing is in PyCBC, so I second @duncanmmacleod's recommendation of posting to their issues board (https://github.com/gwastro/pycbc/issues).

**Comment by duncanmmacleod** [comment]
In general PyCBC is not python3 compatible, so if you really want to use it, you might have to downgrade to python2.7.
